SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[ConvertCSVToBigIntTable]
(
    @List NVARCHAR(MAX),
    @Delim CHAR
)
RETURNS
	@ParsedList TABLE
	(
			Id BIGINT NOT NULL INDEX IX_ID UNIQUE CLUSTERED
	)
AS
BEGIN
	INSERT INTO @ParsedList (ID)  
	SELECT DISTINCT CAST (Value AS BIGINT) FROM string_split(@List,@Delim)
	RETURN
END

GO
