SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[DaysDifferenceBy30360]
(
@StartDate DATETIMEOFFSET,
@EndDate DATETIMEOFFSET
)
RETURNS DECIMAL
AS
BEGIN
SET @StartDate = DATEADD(DAY,-1,@StartDate)
DECLARE @d1 INT =DATEPART(DAY,@StartDate)
DECLARE @d2 INT =DATEPART(DAY,@EndDate)
DECLARE @m1 INT =DATEPART(MONTH,@StartDate)
DECLARE @m2 INT =DATEPART(MONTH,@EndDate)
DECLARE @y1 INT =DATEPART(YEAR,@StartDate)
DECLARE @y2 INT =DATEPART(YEAR,@EndDate)
DECLARE @daysInStartDateMonth INT = DATEPART(DAY,EOMONTH(DATEFROMPARTS(@y1,@m1,1)))
DECLARE @daysInEndDateMonth INT = DATEPART(DAY,EOMONTH(DATEFROMPARTS(@y2,@m2,1)))
IF @daysInStartDateMonth = @d1
BEGIN
SET @d1 = 30;
END
IF @daysInEndDateMonth = @d2
BEGIN
SET @d2 = 30;
END
RETURN (360 * (@y2 - @y1)) + (30 * (@m2 - @m1)) + (@d2 - @d1);
END

GO
