SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[GetContentGuid](@ContentBinary VARBINARY(MAX))
RETURNS UNIQUEIDENTIFIER
AS 
BEGIN
    DECLARE @ContentGUID NVARCHAR(50)
	SET @ContentGUID = CONVERT(NVARCHAR(50), @ContentBinary)	

	RETURN CONVERT(UNIQUEIDENTIFIER, SUBSTRING(@ContentGUID, CHARINDEX(':', @ContentGUID,0) + 1, 36))
END;

GO
