SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Function [dbo].[GetOCRCodes]
(
@Input NVARCHAR(MAX)
)
RETURNS NVARCHAR(MAX)
AS
BEGIN
DECLARE @OCRCodes TABLE ([Key] NVARCHAR(2), [Value] NVARCHAR(3))
INSERT INTO @OCRCodes SELECT '0', '00';INSERT INTO @OCRCodes SELECT '1', '01';INSERT INTO @OCRCodes SELECT '2', '02';INSERT INTO @OCRCodes SELECT '3', '03';
INSERT INTO @OCRCodes SELECT '4', '04';INSERT INTO @OCRCodes SELECT '5', '05';INSERT INTO @OCRCodes SELECT '6', '06';INSERT INTO @OCRCodes SELECT '7', '07';
INSERT INTO @OCRCodes SELECT '8', '08';INSERT INTO @OCRCodes SELECT '9', '09';INSERT INTO @OCRCodes SELECT 'A', '10';INSERT INTO @OCRCodes SELECT 'B', '11';
INSERT INTO @OCRCodes SELECT 'C', '12';INSERT INTO @OCRCodes SELECT 'D', '13';INSERT INTO @OCRCodes SELECT 'E', '14';INSERT INTO @OCRCodes SELECT 'F', '15';
INSERT INTO @OCRCodes SELECT 'G', '16';INSERT INTO @OCRCodes SELECT 'H', '17';INSERT INTO @OCRCodes SELECT 'I', '18';INSERT INTO @OCRCodes SELECT 'J', '19';
INSERT INTO @OCRCodes SELECT 'K', '20';INSERT INTO @OCRCodes SELECT 'L', '21';INSERT INTO @OCRCodes SELECT 'M', '22';INSERT INTO @OCRCodes SELECT 'N', '23';
INSERT INTO @OCRCodes SELECT 'O', '24';INSERT INTO @OCRCodes SELECT 'P', '25';INSERT INTO @OCRCodes SELECT 'Q', '26';INSERT INTO @OCRCodes SELECT 'R', '27';
INSERT INTO @OCRCodes SELECT 'S', '28';INSERT INTO @OCRCodes SELECT 'T', '29';INSERT INTO @OCRCodes SELECT 'U', '30';INSERT INTO @OCRCodes SELECT 'V', '31';
INSERT INTO @OCRCodes SELECT 'W', '32';INSERT INTO @OCRCodes SELECT 'X', '33';INSERT INTO @OCRCodes SELECT 'Y', '34';INSERT INTO @OCRCodes SELECT 'Z', '35';
INSERT INTO @OCRCodes SELECT ' ', '39';INSERT INTO @OCRCodes SELECT '!', '40';INSERT INTO @OCRCodes SELECT '@', '41';INSERT INTO @OCRCodes SELECT '#', '42';
INSERT INTO @OCRCodes SELECT '$', '43';INSERT INTO @OCRCodes SELECT '%', '44';INSERT INTO @OCRCodes SELECT '&', '45';INSERT INTO @OCRCodes SELECT '*', '46';
INSERT INTO @OCRCodes SELECT '(', '47';INSERT INTO @OCRCodes SELECT ')', '48';INSERT INTO @OCRCodes SELECT '_', '49';INSERT INTO @OCRCodes SELECT '-', '50';
INSERT INTO @OCRCodes SELECT '+', '51';INSERT INTO @OCRCodes SELECT '=', '52';INSERT INTO @OCRCodes SELECT '{', '53';INSERT INTO @OCRCodes SELECT '}', '54';
INSERT INTO @OCRCodes SELECT '¢', '55'; INSERT INTO @OCRCodes SELECT ':', '56';INSERT INTO @OCRCodes SELECT ';', '57';INSERT INTO @OCRCodes SELECT '"','58';
INSERT INTO @OCRCodes SELECT '<', '59';INSERT INTO @OCRCodes SELECT '>', '60';INSERT INTO @OCRCodes SELECT '?', '61';INSERT INTO @OCRCodes SELECT ',', '62';
INSERT INTO @OCRCodes SELECT '.', '63';INSERT INTO @OCRCodes SELECT '/', '64';INSERT INTO @OCRCodes SELECT '’', '65';INSERT INTO @OCRCodes SELECT '\', '66';
DECLARE @End INT;
DECLARE @Output NVARCHAR(MAX) = ''
--DECLARE @Input NVARCHAR(MAX) = 'AB¢DE'; Select @Input
WHILE LEN(@Input) > 0
BEGIN
SELECT @Output = @Output+ Value FROM @OCRCodes WHERE [Key] = SUBSTRING(@Input, 1, 1)
SET @Input = SUBSTRING(@Input, 2, LEN(@Input))
END
--Select @Output
RETURN @Output
END

GO
