SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CreditBureauRqstBusinesses](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[BureauCustomerName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[BureauCustomerNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerBureauReport_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[CustomerBureauReport_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[CustomerBureauReport_Content] [varbinary](82) NULL,
	[TotalScore] [decimal](5, 2) NULL,
	[BusinessBureauScore] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsCorporate] [bit] NOT NULL,
	[RequestedCompanyName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[RequestedFirstName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RequestedLastName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RequestedAddress] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[RequestedCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RequestedState] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RequestedZip] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[LBXmlRequest] [varbinary](max) NULL,
	[DBXmlReportData] [varbinary](max) NULL,
	[LBXmlResponse] [varbinary](max) NULL,
	[Active] [bit] NOT NULL,
	[BusinessLegalName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[BusinessAddress] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[BusinessCity] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[BusinessState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[BusinessZip] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AbnormalBusinessReportIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BankruptciesIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BusinessReportDerogatoryRating] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DaysBeyondTermsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[JudgmentsIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SicCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[StandardPercentile] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TotalEmployeesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ModelReason] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ReasonCode] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[MessageCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MessageText] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AccountBalance60PlusDbtPercent] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AccountBalance90PlusDbtPercent] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AccountBalanceCurrentPercent] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BadTradeLinesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BankruptcyRelationshipIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BusinessCollectionsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CreditRatingCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BusinessReportTimeAsCurrentOwner] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BusinessRiskScoreTypeCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BusinessStartDate] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ClosedPaidCollectionsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ClosedUnpaidCollectionsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CollectionsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CollectionsMostRecent6MonthCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CompositePaydexCurrent12MonthAverageAmount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CompositePaydexPrior12MonthAverageAmount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ContinuouslyReportedTradeLinesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CurrentManagementControlYear] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CurrentMinusIndustryNormPaydexScore] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DaysBeyondTermsIntelliscore] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DaysContinuouslyReportedTradeLinesDbtCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DelinquentPaymentExperiencesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DerogatoryPublicRecordsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DerogatoryUccFilingsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ExperiencesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ExperiencesInPaydexCalculationCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FileEstablishedDate] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FinancialConditionIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[HistoryIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IndustryDaysBeyondTermsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IndustryNormPaydexScore] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InquiriesMostRecent6MonthsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InquiriesMostRecent9MonthsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BankruptciesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IntelliscoreCreditUtilization] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IntelliscorePercentSatisfactoryTradelines] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[JudgementLienCollectionCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[JudgementsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LiensIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MonthsSinceBusinessFileEstablished] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MostRecent12MonthsHighestCreditAmount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MostRecentDerogatoryPublicRecordDate] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MostRecentUnpaidCollectionDate] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[NegativePaymentExperiencesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[NetWorthAmount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[NoTradeIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[OpenUnpaidCollectionsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[OriginalUccFilingsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[OtherTradeLinesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[OutOfBusinessIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PaydexFirmScore] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PercentAccountBalance61plusDays] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PercentSatisfactoryExperiences] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PercentSlowNegativeExperiences] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PercentUnpaidBusinessReportCollections] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SatisfactoryPaymentExperiencesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SlowAndNegativePaymentExperiencesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SlowPaymentExperiencesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SuitsIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TaxLiensCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TimeSinceMostRecentBusinessDerogPublicRecord] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TimeSinceMostRecentUnpaidBusinessCollection] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TotalDelinquentAmount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TotalJudgmentsBalanceAmount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TotalTaxLiensBalanceAmount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TradeExperienceAccountsBalance] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TradeExperiencesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TradeLinesPaymentAccountBalance] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TradeLinesWithBalance0DaysDeliquentCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TrendIndicatorCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[WorstDbtMostRecent5QuartersCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[WorstDbtMostRecent6MonthsCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[YearsInBusinessCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ZeroBalanceTradeLinesCount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[HighCredit] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Model] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ManualCustomerSelection] [bit] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[RowVersion] [timestamp] NOT NULL,
	[CreditBureauRequestId] [bigint] NOT NULL,
	[FullReport] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[CustomerCreditBureauId] [bigint] NOT NULL,
	[PartyId] [bigint] NULL,
	[IsDefault] [bit] NOT NULL,
	[RelationshipType] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[RequestedTaxId_CT] [varbinary](48) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)

GO
ALTER TABLE [dbo].[CreditBureauRqstBusinesses]  WITH CHECK ADD  CONSTRAINT [ECreditBureauRequest_CreditBureauRqstBusinesses] FOREIGN KEY([CreditBureauRequestId])
REFERENCES [dbo].[CreditBureauRequests] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CreditBureauRqstBusinesses] CHECK CONSTRAINT [ECreditBureauRequest_CreditBureauRqstBusinesses]
GO
ALTER TABLE [dbo].[CreditBureauRqstBusinesses]  WITH CHECK ADD  CONSTRAINT [ECreditBureauRqstBusiness_CustomerCreditBureau] FOREIGN KEY([CustomerCreditBureauId])
REFERENCES [dbo].[CreditBureauConfigs] ([Id])
GO
ALTER TABLE [dbo].[CreditBureauRqstBusinesses] CHECK CONSTRAINT [ECreditBureauRqstBusiness_CustomerCreditBureau]
GO
ALTER TABLE [dbo].[CreditBureauRqstBusinesses]  WITH CHECK ADD  CONSTRAINT [ECreditBureauRqstBusiness_Party] FOREIGN KEY([PartyId])
REFERENCES [dbo].[Parties] ([Id])
GO
ALTER TABLE [dbo].[CreditBureauRqstBusinesses] CHECK CONSTRAINT [ECreditBureauRqstBusiness_Party]
GO
