SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PostReceivableToGLJobExtracts](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ReceivableId] [bigint] NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ReceivableCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AccountingTreatment] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[EntityType] [nvarchar](2) COLLATE Latin1_General_CI_AS NULL,
	[DueDate] [date] NULL,
	[PostDate] [date] NULL,
	[ProcessThroughDate] [date] NULL,
	[CustomerId] [bigint] NULL,
	[IsIntercompany] [bit] NULL,
	[IsDSL] [bit] NULL,
	[IsSundryBlendedItemFAS91] [bit] NULL,
	[AcquisitionId] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DealProductTypeId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[APGLTemplateId] [bigint] NULL,
	[SundryBlendedItemBookingGlTemplateId] [bigint] NULL,
	[ReceivableForTransferId] [bigint] NULL,
	[ReceivableForTransferType] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[GLTransactionType] [nvarchar](29) COLLATE Latin1_General_CI_AS NULL,
	[SyndicationGLTransactionType] [nvarchar](29) COLLATE Latin1_General_CI_AS NULL,
	[GLTemplateId] [bigint] NULL,
	[SyndicationGLTemplateId] [bigint] NULL,
	[FunderId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[IncomeType] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[TotalAmount] [decimal](16, 2) NULL,
	[PrepaidAmount] [decimal](16, 2) NULL,
	[FinancingTotalAmount] [decimal](16, 2) NULL,
	[FinancingPrepaidAmount] [decimal](16, 2) NULL,
	[Currency] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ContractType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[ContractId] [bigint] NULL,
	[IsChargedOffContract] [bit] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[BookingGLTemplateId] [bigint] NULL,
	[LineOfBusinessId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[LeaseInterimInterestIncomeGLTemplateId] [bigint] NULL,
	[LeaseInterimRentIncomeGLTemplateId] [bigint] NULL,
	[LoanIncomeRecognitionGLTemplateId] [bigint] NULL,
	[LoanInterimIncomeRecognitionGLTemplateId] [bigint] NULL,
	[CommencementDate] [date] NULL,
	[DiscountingId] [bigint] NULL,
	[ReceivableTaxId] [bigint] NULL,
	[TaxTotalAmount] [decimal](16, 2) NULL,
	[TaxBalanceAmount] [decimal](16, 2) NULL,
	[TaxCurrencyCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TaxGlTemplateId] [bigint] NULL,
	[SecurityDepositId] [bigint] NULL,
	[IsCashBased] [bit] NULL,
	[ErrorMessage] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[TaskChunkServiceInstanceId] [bigint] NULL,
	[JobStepInstanceId] [bigint] NOT NULL,
	[IsSubmitted] [bit] NOT NULL,
	[RowVersion] [timestamp] NOT NULL,
	[IsReceivableValid] [bit] NOT NULL,
	[IsReceivableTaxValid] [bit] NOT NULL,
	[BlendedItemId] [bigint] NULL,
	[IsContractSyndicated] [bit] NOT NULL,
	[StartDate] [date] NULL,
	[ReceivableGlTransactionType] [nvarchar](29) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableIsCollected] [bit] NULL,
	[IsVendorOwned] [bit] NOT NULL,
	[IsTiedToDiscounting] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)

GO
