SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReceivableDetailsForReversalProcess_Extract](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[TaskChunkServiceInstanceId] [bigint] NULL,
	[ChunkStatus] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableTaxId] [bigint] NULL,
	[IsCashPosted] [bit] NOT NULL,
	[ReceivableDetailId] [bigint] NOT NULL,
	[Currency] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxAreaId] [bigint] NULL,
	[Cost] [decimal](16, 2) NOT NULL,
	[ExtendedPrice] [decimal](16, 2) NOT NULL,
	[FairMarketValue] [decimal](16, 2) NOT NULL,
	[TaxBasisType] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[AssetId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[DueDate] [date] NOT NULL,
	[ReceivableId] [bigint] NOT NULL,
	[ReceivableCodeId] [bigint] NULL,
	[IsInvoiced] [bit] NOT NULL,
	[IsExemptAtLease] [bit] NOT NULL,
	[IsExemptAtAsset] [bit] NOT NULL,
	[IsExemptAtSundry] [bit] NOT NULL,
	[Company] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Product] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ContractType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LeaseType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LeaseTerm] [decimal](18, 8) NULL,
	[TitleTransferCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TransactionCode] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[AmountBilledToDate] [decimal](16, 2) NOT NULL,
	[AssetLocationId] [bigint] NULL,
	[ToState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[FromState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SundryReceivableCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsExemptAtReceivableCode] [bit] NOT NULL,
	[TransactionType] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableType] [nvarchar](21) COLLATE Latin1_General_CI_AS NULL,
	[IsRental] [bit] NOT NULL,
	[CustomerId] [bigint] NOT NULL,
	[ContractId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[EntityType] [nvarchar](2) COLLATE Latin1_General_CI_AS NULL,
	[CountryTaxExempt] [bit] NOT NULL,
	[StateTaxExempt] [bit] NOT NULL,
	[CityTaxExempt] [bit] NOT NULL,
	[CountyTaxExempt] [bit] NOT NULL,
	[CountryTaxExemptRule] [nvarchar](27) COLLATE Latin1_General_CI_AS NULL,
	[StateTaxExemptRule] [nvarchar](27) COLLATE Latin1_General_CI_AS NULL,
	[CityTaxExemptRule] [nvarchar](27) COLLATE Latin1_General_CI_AS NULL,
	[CountyTaxExemptRule] [nvarchar](27) COLLATE Latin1_General_CI_AS NULL,
	[Country] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[MainDivision] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[StateId] [bigint] NULL,
	[City] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[LocationCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsVertexSupportedLocation] [bit] NOT NULL,
	[ClassCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CustomerNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[TaxRegistrationNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ISOCountryCode] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[PartyName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[GrossVehicleWeight] [int] NULL,
	[AssetType] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SaleLeasebackCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsElectronicallyDelivered] [bit] NOT NULL,
	[TaxRemittanceType] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SalesTaxExemptionLevel] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsSyndicated] [bit] NOT NULL,
	[AssetCatalogNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetTypeId] [bigint] NULL,
	[LeaseUniqueId] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ContractTypeValue] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[LocationEffectiveDate] [date] NULL,
	[LienCredit] [decimal](16, 2) NOT NULL,
	[ReciprocityAmount] [decimal](16, 2) NOT NULL,
	[IsTaxExempt] [bit] NOT NULL,
	[ReceivableTaxDetailId] [bigint] NULL,
	[ReceivableTaxDetailRowVersion] [bigint] NULL,
	[ReceivableTaxRowVersion] [bigint] NULL,
	[ReceivableDetailRowVersion] [bigint] NULL,
	[AssetLocationRowVersion] [bigint] NULL,
	[VertexBilledRentalReceivableId] [bigint] NULL,
	[VertexBilledRentalReceivableRowVersion] [bigint] NULL,
	[JobStepInstanceId] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[RowVersion] [timestamp] NOT NULL,
	[Usage] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[UpfrontTaxSundryId] [bigint] NULL,
	[AcquisitionLocationTaxAreaId] [bigint] NULL,
	[AcquisitionLocationCity] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionLocationMainDivision] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionLocationCountry] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AssetSerialOrVIN] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AssetUsageCondition] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[SalesTaxRemittanceResponsibility] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[MaturityDate] [date] NULL,
	[CommencementDate] [date] NULL,
	[IsSKU] [bit] NOT NULL,
	[IsExemptAtAssetSKU] [bit] NOT NULL,
	[AssetSKUId] [bigint] NULL,
	[UpfrontTaxAssessedInLegacySystem] [bit] NOT NULL,
	[BusCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)

GO
