SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReceiptPostByFileExcel_Extract](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FileReceiptNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[RowNumber] [bigint] NULL,
	[LegalEntity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EntityType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[Entity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptAmount] [decimal](16, 2) NULL,
	[ReceivedDate] [date] NULL,
	[BankAccount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CheckNumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[NameOnCheck] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BankName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CheckDate] [date] NULL,
	[IsApplyCredit] [bit] NOT NULL,
	[Comment] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[CashType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LineOfBusiness] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InstrumentType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BankBranchName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CostCenter] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[GUID] [uniqueidentifier] NULL,
	[JobStepInstanceId] [bigint] NULL,
	[HasError] [bit] NOT NULL,
	[ErrorMessage] [nvarchar](4000) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptId] [bigint] NULL,
	[ComputedInvoiceCustomerId] [bigint] NULL,
	[ComputedCustomerId] [bigint] NULL,
	[ComputedReceiptEntityType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ComputedReceiptTypeId] [bigint] NULL,
	[ComputedBankAccountId] [bigint] NULL,
	[ComputedCashTypeId] [bigint] NULL,
	[ComputedLegalEntityId] [bigint] NULL,
	[ComputedLineOfBusinessId] [bigint] NULL,
	[ComputedCostCenterId] [bigint] NULL,
	[ComputedInstrumentTypeId] [bigint] NULL,
	[ComputedPortfolioId] [bigint] NULL,
	[ComputedContractId] [bigint] NULL,
	[ComputedDiscountingId] [bigint] NULL,
	[ComputedCurrencyId] [bigint] NULL,
	[ComputedBankAccountCurrencyId] [bigint] NULL,
	[ComputedContractCurrencyId] [bigint] NULL,
	[ComputedInvoiceCurrencyId] [bigint] NULL,
	[ComputedCurrencyCodeISO] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ComputedIsDSL] [bit] NOT NULL,
	[ComputedGLTemplateId] [bigint] NULL,
	[ComputedReceivableInvoiceId] [bigint] NULL,
	[ComputedContractLegalEntityId] [bigint] NULL,
	[ComputedIsFullPosting] [bit] NOT NULL,
	[ComputedIsGrouped] [bit] NOT NULL,
	[RowVersion] [timestamp] NOT NULL,
	[GroupNumber] [bigint] NULL,
	[IsInvoiceInMultipleReceipts] [bit] NULL,
	[NonAccrualCategory] [nvarchar](24) COLLATE Latin1_General_CI_AS NULL,
	[IsStatementInvoice] [bit] NULL,
	[PayOffId] [bigint] NULL,
	[PayDownId] [bigint] NULL,
	[CreateUnallocatedReceipt] [bit] NOT NULL,
	[ReceivableTaxType] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)

GO
