SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VertexWSTransaction_Extract](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ReceivableId] [bigint] NULL,
	[ReceivableDetailId] [bigint] NULL,
	[AmountBilledToDate] [decimal](16, 2) NULL,
	[City] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[LineItemNumber] [bigint] NULL,
	[CustomerCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Cost] [decimal](16, 2) NULL,
	[CompanyCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[DueDate] [date] NULL,
	[MainDivision] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Country] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ExtendedPrice] [decimal](16, 2) NULL,
	[FairMarketValue] [decimal](16, 2) NULL,
	[LocationCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Product] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[TaxAreaId] [bigint] NULL,
	[TransactionType] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CustomerClass] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Term] [decimal](16, 2) NULL,
	[GrossVehicleWeight] [int] NULL,
	[ReciprocityAmount] [decimal](16, 2) NULL,
	[LienCredit] [decimal](16, 2) NULL,
	[LocationEffectiveDate] [date] NULL,
	[TransCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ContractTypeName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ShortLeaseType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TaxBasis] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LeaseUniqueID] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TitleTransferCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SundryReceivableCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AssetType] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SaleLeasebackCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsElectronicallyDelivered] [bit] NOT NULL,
	[TaxRemittanceType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FromState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ToState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AssetId] [bigint] NULL,
	[SalesTaxExemptionLevel] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TaxReceivableName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsSyndicated] [bit] NOT NULL,
	[BusCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[HorsePower] [decimal](16, 2) NULL,
	[AssetCatalogNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsTaxExempt] [bit] NOT NULL,
	[TaxExemptReason] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsPrepaidUpfrontTax] [bit] NOT NULL,
	[IsCapitalizedSalesTaxAsset] [bit] NOT NULL,
	[IsExemptAtAsset] [bit] NOT NULL,
	[IsExemptAtReceivableCode] [bit] NOT NULL,
	[IsExemptAtSundry] [bit] NOT NULL,
	[LocationId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[LocationStatus] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[BatchStatus] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[TaskChunkServiceInstanceId] [bigint] NULL,
	[JobStepInstanceId] [bigint] NOT NULL,
	[Usage] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RowVersion] [timestamp] NOT NULL,
	[IsCapitalizedRealAsset] [bit] NOT NULL,
	[AssetLocationId] [bigint] NULL,
	[GLTemplateId] [bigint] NULL,
	[IsCapitalizedFirstRealAsset] [bit] NOT NULL,
	[SalesTaxRemittanceResponsibility] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionLocationTaxAreaId] [bigint] NULL,
	[AcquisitionLocationCity] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionLocationMainDivision] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionLocationCountry] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[MaturityDate] [date] NULL,
	[AssetSerialOrVIN] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AssetUsageCondition] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[CommencementDate] [date] NULL,
	[IsSKU] [bit] NOT NULL,
	[AssetSKUId] [bigint] NULL,
	[IsExemptAtAssetSKU] [bit] NOT NULL,
	[ReceivableSKUId] [bigint] NULL,
	[UpfrontTaxAssessedInLegacySystem] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)

GO
