CREATE TYPE [dbo].[AcceleratedBalanceQuote] AS TABLE(
	[QuoteDate] [date] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[QuoteGoodThrough] [date] NULL,
	[Comment1] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[PerDiem_Amount] [decimal](16, 2) NULL,
	[PerDiem_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[LateCharges_Amount] [decimal](16, 2) NULL,
	[LateCharges_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NSFOrProcessFeesOrOther_Amount] [decimal](16, 2) NULL,
	[NSFOrProcessFeesOrOther_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[InsuranceFees_Amount] [decimal](16, 2) NULL,
	[InsuranceFees_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ChaseOrInspectionFees_Amount] [decimal](16, 2) NULL,
	[ChaseOrInspectionFees_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[EquipmentRelatedExpenses_Amount] [decimal](16, 2) NULL,
	[EquipmentRelatedExpenses_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[LegalFeesOrCost_Amount] [decimal](16, 2) NULL,
	[LegalFeesOrCost_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[DocumentationFees_Amount] [decimal](16, 2) NULL,
	[DocumentationFees_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Waivers_Amount] [decimal](16, 2) NULL,
	[Waivers_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Credits_Amount] [decimal](16, 2) NULL,
	[Credits_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[DirectAllInquiriesTo] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[TotalDue_Amount] [decimal](16, 2) NULL,
	[TotalDue_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Comment2] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Comment3] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[BuyerAddress] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[PayableTo] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[ToId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
