CREATE TYPE [dbo].[ACHBatchHeader] AS TABLE(
	[ACHBatchHeaderRecordTypeCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ACHBatchHeaderServiceClassCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PrivateLableName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TaxID] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SEC] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ACHBatchHeaderCompanyEntryDescription] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Settlementdate] [date] NULL,
	[ACHBatchHeaderOriginatorStatusCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[OrigDFIID] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[JobStepInstanceId] [bigint] NULL,
	[ACHBatchControlRecordTypeCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[ACHBatchControlServiceClassCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[GenerateBalancedACH] [bit] NOT NULL,
	[ReceiptLegalEntityBankAccountId] [bigint] NULL,
	[ReceiptLegalEntityBankAccountCreditCode] [bigint] NULL,
	[ReceiptLegalEntityBankAccountNumber_CT] [varbinary](48) NULL,
	[ReceiptLegalEntityBankAccountACHRoutingNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[Origin] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[OriginName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FileHeaderId] [bigint] NULL,
	[BatchHeaderId] [bigint] NULL,
	[ACHFileHeaderId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
