CREATE TYPE [dbo].[ACHEntryDetail] AS TABLE(
	[ACHEntryDetailRecordTypeCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ACHEntryDetailTransactionCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[CustomerBankDebitCode] [bigint] NULL,
	[CustomerBankAccountACHRoutingNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ACHAmount] [decimal](16, 2) NULL,
	[CustomerBankAccountNumber_CT] [varbinary](48) NULL,
	[EntityId] [bigint] NULL,
	[PartyName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[ACHEntryDetailAddendaRecordIndicator] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[TraceNumber] [bigint] NULL,
	[PAPEntryDetailRecordTypeCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PAPEntryDetailPaymentNumber] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PAPEntryDetailLanguageCode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PAPEntryDetailDestinationCountry] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PAPEntryDetailOptionalRecordIndicator] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PAPEntryDetailClientShortName] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[OrigDFIID] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Currency] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerBankAccountId] [bigint] NULL,
	[CostCenterId] [bit] NOT NULL,
	[JobStepInstanceId] [bigint] NULL,
	[ACHScheduleExtractIds] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[EntryDetailId] [bigint] NULL,
	[ACHBatchHeaderId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
