CREATE TYPE [dbo].[ACHReturn_Extract] AS TABLE(
	[ACHRunId] [bigint] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ACHRunDetailId] [bigint] NULL,
	[ACHRunFileId] [bigint] NULL,
	[ReceiptId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[ACHScheduleId] [bigint] NULL,
	[OneTimeACHId] [bigint] NULL,
	[EntryDetailLineNumber] [bigint] NULL,
	[ReturnReasonCodeLineNumber] [bigint] NULL,
	[JobStepInstanceId] [bigint] NULL,
	[IsOneTimeACH] [bit] NULL,
	[ReceivedDate] [date] NULL,
	[ReceiptClassification] [nvarchar](23) COLLATE Latin1_General_CI_AS NULL,
	[Status] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptAmount_Amount] [decimal](16, 2) NULL,
	[ReceiptAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ReturnFileReceiptAmount_Amount] [decimal](16, 2) NULL,
	[ReturnFileReceiptAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[EntityType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[TraceNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[FileName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[ReasonCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ReACH] [bit] NULL,
	[IsNSFChargeEligible] [bit] NULL,
	[NSFCustomerId] [bigint] NULL,
	[NSFLocationId] [bigint] NULL,
	[NSFBillToId] [bigint] NULL,
	[GUID] [uniqueidentifier] NULL,
	[IsPending] [bit] NOT NULL,
	[CustomerBankAccountId] [bigint] NULL,
	[LegalEntityACHFailureLimit] [bigint] NULL,
	[CurrentACHFailureCount] [int] NULL,
	[AccountOnHoldCount] [int] NULL,
	[CurrentOnHoldStatus] [bit] NOT NULL,
	[ContractId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
