CREATE TYPE [dbo].[ACHSchedule_Extract] AS TABLE(
	[IsOneTimeACH] [bit] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[OneTimeBankAccount] [bit] NOT NULL,
	[OneTimeACHId] [bigint] NULL,
	[OneTimeACHInvoiceId] [bigint] NULL,
	[OneTimeACHReceivableId] [bigint] NULL,
	[OneTimeACHScheduleId] [bigint] NULL,
	[ReceivableDetailId] [bigint] NULL,
	[ACHScheduleId] [bigint] NULL,
	[ACHAmount] [decimal](16, 2) NOT NULL,
	[UnAllocatedAmount] [decimal](16, 2) NOT NULL,
	[CheckNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ACHPaymentNumber] [bigint] NULL,
	[ACHSchedulePaymentType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[SettlementDate] [date] NULL,
	[RemitToId] [bigint] NULL,
	[RemitToName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CashTypeId] [bigint] NOT NULL,
	[BranchId] [bigint] NULL,
	[ReceiptTypeName] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptTypeId] [bigint] NOT NULL,
	[GLTemplateId] [bigint] NOT NULL,
	[GLConfigurationId] [bigint] NOT NULL,
	[ReceiptClassificationType] [nvarchar](23) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceiptGLTemplateName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[CurrencyId] [bigint] NOT NULL,
	[CurrencyName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[CurrencyCode] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[CurrencySymbol] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[ContractId] [bigint] NULL,
	[SequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InstrumentTypeId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[DiscountingId] [bigint] NULL,
	[SyndicationDate] [date] NULL,
	[IsPrivateLabel] [bit] NOT NULL,
	[ContractType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[PrivateLabelName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[CustomerId] [bigint] NOT NULL,
	[CustomerNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsConsolidated] [bit] NOT NULL,
	[CustomerName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[CustomerBankAccountId] [bigint] NOT NULL,
	[CustomerBankAccountNumber_CT] [varbinary](48) NOT NULL,
	[CustomerBankAccountDebitCode] [bigint] NOT NULL,
	[CustomerBankAccountACHRoutingNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[CostCenterId] [bigint] NULL,
	[ReceivableId] [bigint] NULL,
	[ReceivableInvoiceId] [bigint] NULL,
	[PaymentScheduleId] [bigint] NULL,
	[ReceivableDetailAmount] [decimal](16, 2) NOT NULL,
	[ReceivableDetailTaxAmount] [decimal](16, 2) NOT NULL,
	[ReceivableLegalEntityId] [bigint] NULL,
	[IsNonAccrual] [bit] NOT NULL,
	[ReceiptLegalEntityId] [bigint] NOT NULL,
	[ReceiptLegalEntityNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceiptLegalEntityName] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceiptBankAccountId] [bigint] NOT NULL,
	[ReceiptBankAccountNumber_CT] [varbinary](48) NOT NULL,
	[ReceiptBankGenerateBalancedACH] [bit] NOT NULL,
	[ReceiptBankGenerateControlFile] [bit] NOT NULL,
	[ReceiptBankBranchName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceiptBankSourceofInput] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptBankACISCustomerNumber] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptBankACHRoutingNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptBankAccountCreditCode] [bigint] NOT NULL,
	[ReceiptBankAccountACHOperatorConfigId] [bigint] NULL,
	[FileFormat] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[PaymentThresholdEmailId] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[PaymentThresholdAmount] [decimal](16, 2) NOT NULL,
	[ACHPaymentThresholdDetailId] [bigint] NULL,
	[PaymentThreshold] [bit] NOT NULL,
	[JobStepInstanceId] [bigint] NOT NULL,
	[ReceiptBankAccountType] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[IsTaxAssessed] [bit] NOT NULL,
	[HasMultipleContractReceivables] [bit] NOT NULL,
	[HasPendingDSLOrNANSDLReceipt] [bit] NOT NULL,
	[EmailTemplateName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ErrorCode] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[NACHAFilePaddingOption] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[InvalidOpenPeriodFromDate] [date] NULL,
	[InvalidOpenPerionToDate] [date] NULL,
	[PendingReceiptIds] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[LateFeeInvoiceNumbers] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[LateFeeReceiptIds] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[BankAccountIsOnHold] [bit] NOT NULL,
	[ErrorMessage] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
