CREATE TYPE [dbo].[Activity] AS TABLE(
	[Name] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Description] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Solution] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[CreatedDate] [date] NOT NULL,
	[CompletionDate] [datetimeoffset](7) NULL,
	[IsFollowUpRequired] [bit] NOT NULL,
	[FollowUpDate] [datetimeoffset](7) NULL,
	[DefaultPermission] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[EntityId] [bigint] NULL,
	[EntityNaturalId] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[InitiatedTransactionEntityId] [bigint] NULL,
	[CloseFollowUp] [bit] NOT NULL,
	[ClosingComments] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[TargetCompletionDate] [datetimeoffset](7) NULL,
	[OwnerId] [bigint] NULL,
	[ActivityTypeId] [bigint] NULL,
	[StatusId] [bigint] NOT NULL,
	[PortfolioId] [bigint] NOT NULL,
	[OwnerGroupId] [bigint] NULL,
	[DocumentListId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
