CREATE TYPE [dbo].[ActivityForCustomer] AS TABLE(
	[PaymentDate] [date] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[PaymentMode] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[IsCustomerContacted] [bit] NOT NULL,
	[PromiseToPayDate] [date] NULL,
	[ContactReference] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[SourceUsed] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PaymentAmount_Amount] [decimal](16, 2) NULL,
	[PaymentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ReferenceInvoiceNumber] [bigint] NULL,
	[CurrentChapter] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[Chapter] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[JudgmentDate] [date] NULL,
	[Fee_Amount] [decimal](16, 2) NULL,
	[Fee_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TotalAmount_Amount] [decimal](16, 2) NULL,
	[TotalAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[DateContractCopySent] [date] NULL,
	[SentTo] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[LeaseTerminationOption] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[PayoffAssetStatus] [nvarchar](21) COLLATE Latin1_General_CI_AS NULL,
	[PaydownReason] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[VendorId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[CollectionAgentId] [bigint] NULL,
	[PersonContactedId] [bigint] NULL,
	[NewCustomerId] [bigint] NULL,
	[CurrencyId] [bigint] NULL,
	[CourtFilingId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
