CREATE TYPE [dbo].[AdditionalCharge] AS TABLE(
	[RowNumber] [int] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[VATAmount_Amount] [decimal](16, 2) NOT NULL,
	[VATAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Capitalize] [bit] NOT NULL,
	[CreateSoftAsset] [bit] NOT NULL,
	[Recurring] [bit] NOT NULL,
	[ReceivableDueDate] [date] NULL,
	[RecurringNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[FirstDueDate] [date] NULL,
	[DueDay] [int] NULL,
	[Frequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[ChargeApplicable] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[SourceType] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[FeePercent] [decimal](5, 2) NULL,
	[FeeId] [bigint] NOT NULL,
	[AssetTypeId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[GLTemplateId] [bigint] NULL,
	[AssetLocationId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
