CREATE TYPE [dbo].[AssetSale] AS TABLE(
	[TransactionNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TransactionDate] [date] NULL,
	[PostDate] [date] NULL,
	[DueDate] [date] NULL,
	[Status] [nvarchar](13) COLLATE Latin1_General_CI_AS NOT NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxAmount_Amount] [decimal](16, 2) NOT NULL,
	[TaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerPurchaseOrderNumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[InvoicePreference] [nvarchar](18) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[NumberofInstallment] [int] NOT NULL,
	[SaleOfInvestorAsset] [bit] NOT NULL,
	[IsInstallmentQuote] [bit] NOT NULL,
	[IsGenerateInstallmentPerformed] [bit] NOT NULL,
	[IsTaxAssessed] [bit] NOT NULL,
	[IsAllowTradeIn] [bit] NOT NULL,
	[IsCompletePayableInvoice] [bit] NOT NULL,
	[IsPayableNetoff] [bit] NOT NULL,
	[InvoiceReceivableGroupingOption] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceFile_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceFile_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceFile_Content] [varbinary](82) NULL,
	[Discounts_Amount] [decimal](16, 2) NOT NULL,
	[Discounts_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[RetainedDiscounts_Amount] [decimal](16, 2) NOT NULL,
	[RetainedDiscounts_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BookGainLossAmount_Amount] [decimal](16, 2) NULL,
	[BookGainLossAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TaxGainLossAmount_Amount] [decimal](16, 2) NULL,
	[TaxGainLossAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NetSaleAmount_Amount] [decimal](16, 2) NULL,
	[NetSaleAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsAssignAtAssetLevel] [bit] NOT NULL,
	[PayableWithholdingTaxRate] [decimal](5, 2) NULL,
	[LegalEntityId] [bigint] NULL,
	[GLConfigurationId] [bigint] NULL,
	[BuyerId] [bigint] NOT NULL,
	[BillToId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[TaxLocationId] [bigint] NULL,
	[AssetSaleReceivableCodeId] [bigint] NULL,
	[CashBasedAssetSaleReceivableCodeId] [bigint] NULL,
	[AssetSaleGLTemplateId] [bigint] NULL,
	[AssetSaleTaxGLTemplateId] [bigint] NULL,
	[TaxDepDisposalTemplateId] [bigint] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[PayableCodeId] [bigint] NULL,
	[PayableInvoiceId] [bigint] NULL,
	[SaleGLJournalId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[CountryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
