CREATE TYPE [dbo].[Asset] AS TABLE(
	[Alias] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[AcquisitionDate] [date] NOT NULL,
	[PartNumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[UsageCondition] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[Description] [nvarchar](500) COLLATE Latin1_General_CI_AS NOT NULL,
	[Quantity] [int] NOT NULL,
	[InServiceDate] [date] NOT NULL,
	[IsEligibleForPropertyTax] [bit] NOT NULL,
	[Status] [nvarchar](17) COLLATE Latin1_General_CI_AS NOT NULL,
	[FinancialType] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[MoveChildAssets] [bit] NOT NULL,
	[AssetMode] [nvarchar](19) COLLATE Latin1_General_CI_AS NOT NULL,
	[PropertyTaxCost_Amount] [decimal](16, 2) NOT NULL,
	[PropertyTaxCost_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PropertyTaxDate] [date] NULL,
	[ProspectiveContract] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyCode] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsTaxExempt] [bit] NOT NULL,
	[ModelYear] [decimal](4, 0) NULL,
	[CustomerPurchaseOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[OwnershipStatus] [nvarchar](19) COLLATE Latin1_General_CI_AS NULL,
	[PropertyTaxResponsibility] [nvarchar](16) COLLATE Latin1_General_CI_AS NOT NULL,
	[PurchaseOrderDate] [date] NULL,
	[GrossVehicleWeight] [int] NULL,
	[WeightMeasure] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsOffLease] [bit] NOT NULL,
	[IsElectronicallyDelivered] [bit] NOT NULL,
	[IsSaleLeaseback] [bit] NOT NULL,
	[IsParent] [bit] NOT NULL,
	[IsOnCommencedLease] [bit] NOT NULL,
	[IsTakedownAsset] [bit] NOT NULL,
	[IsSystemCreated] [bit] NOT NULL,
	[PreviousSequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SubStatus] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[DealerCost_Amount] [decimal](16, 2) NULL,
	[DealerCost_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[DMDPercentage] [decimal](5, 2) NULL,
	[CustomerAssetNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[VendorOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsManufacturerOverride] [bit] NOT NULL,
	[Description2] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Class1] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[Class3] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ManufacturerOverride] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsReversed] [bit] NOT NULL,
	[IsSerializedAsset] [bit] NOT NULL,
	[Residual_Amount] [decimal](16, 2) NOT NULL,
	[Residual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsVehicle] [bit] NOT NULL,
	[SpecifiedLeasingProperty] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[ExemptProperty] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[IsLeaseComponent] [bit] NOT NULL,
	[IsServiceOnly] [bit] NOT NULL,
	[IsSKU] [bit] NOT NULL,
	[IsTaxParameterChangedForLeasedAsset] [bit] NOT NULL,
	[DisposedDate] [date] NULL,
	[Salvage_Amount] [decimal](16, 2) NOT NULL,
	[Salvage_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ValueExclVAT_Amount] [decimal](16, 2) NOT NULL,
	[ValueExclVAT_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ValueInclVAT_Amount] [decimal](16, 2) NULL,
	[ValueInclVAT_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsVat] [bit] NULL,
	[IsImport] [bit] NULL,
	[IsPreLeased] [bit] NULL,
	[DateofProduction] [date] NOT NULL,
	[AgeofAsset] [decimal](16, 2) NULL,
	[Modification] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[TrimLevel] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[AcquiredDate] [date] NULL,
	[DeliveredDate] [date] NULL,
	[SalePurchaseAgreementNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[SalePurchaseAgreementDate] [date] NULL,
	[CreationStatus] [nvarchar](7) COLLATE Latin1_General_CI_AS NOT NULL,
	[RoadTaxType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[IsServiced] [bit] NULL,
	[IsFixedAsset] [bit] NULL,
	[IsFromCreditApp] [bit] NOT NULL,
	[ManufacturerId] [bigint] NULL,
	[MakeId] [bigint] NULL,
	[ModelId] [bigint] NULL,
	[TypeId] [bigint] NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[CustomerId] [bigint] NULL,
	[ParentAssetId] [bigint] NULL,
	[FeatureSetId] [bigint] NULL,
	[ClearAccumulatedGLTemplateId] [bigint] NULL,
	[TitleTransferCodeId] [bigint] NULL,
	[AssetUsageId] [bigint] NULL,
	[PropertyTaxReportCodeId] [bigint] NULL,
	[StateId] [bigint] NULL,
	[VendorAssetCategoryId] [bigint] NULL,
	[SaleLeasebackCodeId] [bigint] NULL,
	[RemarketingVendorId] [bigint] NULL,
	[MaintenanceVendorId] [bigint] NULL,
	[PlaceholderAssetId] [bigint] NULL,
	[SalesTaxExemptionLevelId] [bigint] NULL,
	[AssetCatalogId] [bigint] NULL,
	[ProductId] [bigint] NULL,
	[AssetClass2Id] [bigint] NULL,
	[AssetCategoryId] [bigint] NULL,
	[TaxExemptRuleId] [bigint] NOT NULL,
	[InventoryRemarketerId] [bigint] NULL,
	[PricingGroupId] [bigint] NULL,
	[VendorId] [bigint] NOT NULL,
	[CreditApplicationEquipmentDetailId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
