CREATE TYPE [dbo].[AssetMeasures] AS TABLE(
	[RemainingEconomicLife] [int] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[NBVImpairment] [decimal](16, 2) NULL,
	[AccumulatedNBVImpairmentAmountLeaseComponent] [decimal](16, 2) NULL,
	[AccumulatedNBVImpairmentAmountFinanceComponent] [decimal](16, 2) NULL,
	[ResidualImpairmentAmountLeaseComponent] [decimal](16, 2) NULL,
	[ResidualImpairmentAmountFinanceComponent] [decimal](16, 2) NULL,
	[AssetImpairmentLeaseComponent] [decimal](16, 2) NULL,
	[AssetImpairmentFinanceComponent] [decimal](16, 2) NULL,
	[AccumulatedAssetImpairmentAmountLeaseComponent] [decimal](16, 2) NULL,
	[AccumulatedAssetImpairmentAmountFinanceComponent] [decimal](16, 2) NULL,
	[AcquisitionCostLeaseComponent] [decimal](16, 2) NULL,
	[AcquisitionCostFinanceComponent] [decimal](16, 2) NULL,
	[AccumulatedInventoryDepreciationAmountLeaseComponent] [decimal](16, 2) NULL,
	[AccumulatedInventoryDepreciationAmountFinanceComponent] [decimal](16, 2) NULL,
	[AccumulatedFixedTermDepreciationAmountLeaseComponent] [decimal](16, 2) NULL,
	[AccumulatedOTPDepreciationAmountLeaseComponent] [decimal](16, 2) NULL,
	[AccumulatedOTPDepreciationAmountFinanceComponent] [decimal](16, 2) NULL,
	[CurrentNBVAmountLeaseComponent] [decimal](16, 2) NULL,
	[CurrentNBVAmountFinanceComponent] [decimal](16, 2) NULL,
	[AssetValue] [decimal](16, 2) NULL,
	[DatePlacedOffInventory] [date] NULL,
	[DatePlacedInInventory] [date] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
