CREATE TYPE [dbo].[AssetCatalog] AS TABLE(
	[CollateralCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Class3] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsInsuranceRequired] [bit] NOT NULL,
	[FMV_Amount] [decimal](16, 2) NULL,
	[FMV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsCollateralTrackingRequired] [bit] NOT NULL,
	[IsUpgradeEligible] [bit] NOT NULL,
	[Usefullife] [int] NULL,
	[IsActive] [bit] NOT NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ManufacturerId] [bigint] NOT NULL,
	[ProductId] [bigint] NULL,
	[AssetCategoryId] [bigint] NULL,
	[AssetTypeId] [bigint] NULL,
	[AssetClassADRId] [bigint] NULL,
	[Class2Id] [bigint] NULL,
	[ProductSubTypeId] [bigint] NULL,
	[MakeId] [bigint] NULL,
	[ModelId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
