CREATE TYPE [dbo].[AssetEnMasseUpdateDetail] AS TABLE(
	[Alias] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[AcquisitionDate] [date] NULL,
	[PartNumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[UsageCondition] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[Description] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Quantity] [int] NOT NULL,
	[InServiceDate] [date] NOT NULL,
	[IsEligibleForPropertyTax] [bit] NOT NULL,
	[PropertyTaxCost_Amount] [decimal](16, 2) NOT NULL,
	[PropertyTaxCost_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PropertyTaxDate] [date] NULL,
	[ProspectiveContract] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[OwnershipStatus] [nvarchar](19) COLLATE Latin1_General_CI_AS NULL,
	[PurchaseOrderDate] [date] NULL,
	[ModelYear] [decimal](4, 0) NULL,
	[VendorOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsSaleLeaseback] [bit] NOT NULL,
	[IsElectronicallyDelivered] [bit] NOT NULL,
	[AssetId] [bigint] NOT NULL,
	[ManufacturerId] [bigint] NULL,
	[MakeId] [bigint] NULL,
	[ModelId] [bigint] NULL,
	[TypeId] [bigint] NOT NULL,
	[CustomerId] [bigint] NULL,
	[PropertyTaxReportCodeId] [bigint] NULL,
	[VendorAssetCategoryId] [bigint] NULL,
	[StateId] [bigint] NULL,
	[SaleLeasebackCodeId] [bigint] NULL,
	[AssetCatalogId] [bigint] NULL,
	[AssetBookValueAdjustmentGLTemplateId] [bigint] NULL,
	[BookDepreciationGLTemplateId] [bigint] NULL,
	[InventoryRemarketerId] [bigint] NULL,
	[AssetEnMasseUpdateId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
