CREATE TYPE [dbo].[AssetEntryType] AS TABLE(
	[RowNumber] [bigint] NULL,
	[Alias] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionDate] [datetime] NULL,
	[AsOfDate] [datetime] NULL,
	[PartNumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[UsageCondition] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AssetDescription] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Quantity] [int] NULL,
	[IsEligibleForPropertyTax] [bit] NULL,
	[Status] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[FinancialType] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[MoveChildAssets] [bit] NULL,
	[AssetMode] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PropertyTaxCost_Amount] [decimal](19, 2) NULL,
	[PropertyTaxCost_Currency] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PropertyTaxDate] [datetime] NULL,
	[ProspectiveContract] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyCode] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ManufacturerId] [bigint] NULL,
	[TypeId] [bigint] NULL,
	[PricingGroupId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[AssetUsageId] [bigint] NULL,
	[ParentAssetAlias] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsTaxExempt] [bit] NULL,
	[LocationAlias] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[EffectiveFromDate] [datetime] NULL,
	[InServiceDate] [datetime] NULL,
	[CustomerPurchaseOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ModelYear] [decimal](4, 0) NULL,
	[PropertyTaxResponsibility] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[HistorySourceModule] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[GrossVehicleWeight] [int] NULL,
	[WeightMeasure] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[ElectronicallyDelivered] [bit] NULL,
	[PurchaseOrderDate] [datetime] NULL,
	[IsFLStampTaxExempt] [bit] NULL,
	[OwnershipStatus] [nvarchar](19) COLLATE Latin1_General_CI_AS NULL,
	[VendorAssetCategoryId] [bigint] NULL,
	[RegistrationStateId] [bigint] NULL,
	[SalesTaxExemptionLevelId] [bigint] NULL,
	[IsCollateralTracking] [bit] NULL,
	[CollateralTitleReleaseStatus] [nvarchar](29) COLLATE Latin1_General_CI_AS NULL,
	[CollateralStatus] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[SubStatus] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[IsManufacturerOverride] [bit] NULL,
	[Description2] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Class1] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Class3] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ManufacturerOverride] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetCatalogId] [bigint] NULL,
	[ProductId] [bigint] NULL,
	[AssetClass2Id] [bigint] NULL,
	[AssetCategoryId] [bigint] NULL,
	[VendorOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsSaleLeaseback] [bit] NULL,
	[AssetBookValueAdjustmentGLTemplateId] [bigint] NULL,
	[AssetBookDepreceiationGLTemplateId] [bigint] NULL,
	[MakeId] [bigint] NULL,
	[ModelId] [bigint] NULL,
	[MaintenanceVendorId] [bigint] NULL,
	[IsSerializedAsset] [bit] NULL,
	[Residual_Amount] [decimal](19, 2) NULL,
	[Residual_Currency] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[IsVehicle] [bit] NOT NULL,
	[AssetClassId] [bigint] NULL,
	[VehicleType] [nvarchar](18) COLLATE Latin1_General_CI_AS NULL,
	[TransmissionType] [nvarchar](18) COLLATE Latin1_General_CI_AS NULL,
	[TankCapacity] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[InteriorColor] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[NumberOfCylinders] [int] NULL,
	[PayloadCapacity] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[FuelTypeId] [bigint] NULL,
	[EngineSize] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[DriveTrainId] [bigint] NULL,
	[WeightClass] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[CO2] [decimal](16, 2) NULL,
	[ContractMileage] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[BodyDescription] [nvarchar](400) COLLATE Latin1_General_CI_AS NULL,
	[OriginalOdometerReading] [int] NULL,
	[OdometerReadingUnit] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[NumberOfDoors] [int] NULL,
	[BodyTypeId] [bigint] NULL,
	[NumberOfPassengers] [int] NULL,
	[NumberOfSeats] [int] NULL,
	[KeylessEntry] [bit] NOT NULL,
	[MPG] [int] NULL,
	[NumberOfKeys] [int] NULL,
	[DoorKeyCode] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[NumberOfRemotes] [int] NULL,
	[TireSize] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[EngineKeyCode] [int] NULL,
	[ExteriorColor] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[WeightUnit] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[GVW] [decimal](16, 2) NULL,
	[GrossCurbCombinedWeight] [decimal](16, 2) NULL,
	[VehicleRegisteredWeight] [decimal](16, 2) NULL,
	[VehicleCurbWeight] [decimal](16, 2) NULL,
	[Titled] [bit] NOT NULL,
	[TitleTrustOverride] [bit] NOT NULL,
	[TitleStateId] [bigint] NULL,
	[TitleBorrowedReason] [nvarchar](38) COLLATE Latin1_General_CI_AS NULL,
	[TitleBorrowedDate] [date] NULL,
	[TitleLienHolder] [nvarchar](32) COLLATE Latin1_General_CI_AS NULL,
	[TitleApplicationSubmissionDate] [date] NULL,
	[TitleReceivedDate] [date] NULL,
	[TitleCodeId] [bigint] NULL,
	[UpfrontTaxMode] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[TaxBasisType] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[InventoryRemarketerId] [bigint] NULL,
	[InvoiceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[VendorNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsLeaseComponent] [bit] NOT NULL,
	[ServiceOnly] [bit] NOT NULL,
	[IsSKU] [bit] NOT NULL
)
GO
