CREATE TYPE [dbo].[AssetType] AS TABLE(
	[Name] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsSoft] [bit] NOT NULL,
	[IsQualifiedTechnicalEquipment] [bit] NOT NULL,
	[EconomicLifeInMonths] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[ActivationDate] [date] NOT NULL,
	[DeactivationDate] [date] NULL,
	[ExcludeFrom90PercentTest] [bit] NOT NULL,
	[IsHighRisk] [bit] NOT NULL,
	[IsInsuranceRequired] [bit] NOT NULL,
	[EquipmentClass] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IRSClassCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsCollateralTracking] [bit] NOT NULL,
	[IsEligibleForFPI] [bit] NOT NULL,
	[IsElectronicallyDelivered] [bit] NOT NULL,
	[Serialized] [bit] NOT NULL,
	[ReviewFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[ExemptProperty] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[IsTrailer] [bit] NOT NULL,
	[IsRoadTaxApplicable] [bit] NOT NULL,
	[IsPermissibleMassRange] [bit] NOT NULL,
	[RoadTaxType] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[FlatFeeParameter] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[ProductId] [bigint] NULL,
	[CostTypeId] [bigint] NOT NULL,
	[AssetClassCodeId] [bigint] NULL,
	[TaxExemptRuleId] [bigint] NOT NULL,
	[BookDepreciationTemplateId] [bigint] NULL,
	[CapitalCostAllowanceClassId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[PricingGroupId] [bigint] NULL,
	[AssetCategoryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
