CREATE TYPE [dbo].[Assumption] AS TABLE(
	[OldSequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[NewSequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[AssumptionReason] [nvarchar](17) COLLATE Latin1_General_CI_AS NOT NULL,
	[PostDate] [date] NULL,
	[Status] [nvarchar](25) COLLATE Latin1_General_CI_AS NULL,
	[AssumptionDate] [date] NULL,
	[ReceivableAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ContractType] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsCloneAssetLocation] [bit] NOT NULL,
	[IsAccountingApproved] [bit] NOT NULL,
	[IsFundingApproved] [bit] NOT NULL,
	[IsAMReviewRequired] [bit] NOT NULL,
	[IsAMReviewCompleted] [bit] NOT NULL,
	[SortOrder] [int] NOT NULL,
	[IsSalesTaxExemption] [bit] NOT NULL,
	[IsSalesTaxReviewRequired] [bit] NOT NULL,
	[IsSalesTaxReviewCompleted] [bit] NOT NULL,
	[IsSalesLeaseBackReviewCompleted] [bit] NOT NULL,
	[IsBillInAlternateCurrency] [bit] NOT NULL,
	[IsVATAssessed] [bit] NOT NULL,
	[ContractId] [bigint] NOT NULL,
	[NewCustomerId] [bigint] NULL,
	[NewLocationId] [bigint] NULL,
	[NewBillToId] [bigint] NULL,
	[LineOfCreditId] [bigint] NULL,
	[OriginalCustomerId] [bigint] NOT NULL,
	[LeasePaymentId] [bigint] NULL,
	[LoanPaymentId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
