CREATE TYPE [dbo].[AVNotice] AS TABLE(
	[AVNoticeNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[AssessmentNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Type] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LienDate] [date] NULL,
	[TaxYear] [int] NULL,
	[TaxEntity] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivedDate] [date] NULL,
	[DueDate] [date] NULL,
	[FollowUpDate] [date] NULL,
	[ParcelNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AccountNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TotalAssessed_Amount] [decimal](16, 2) NULL,
	[TotalAssessed_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[RenderedValue_Amount] [decimal](16, 2) NULL,
	[RenderedValue_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[RenderedValueDifference] [decimal](10, 2) NULL,
	[ApprovalStatus] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[UserBatchID] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](2000) COLLATE Latin1_General_CI_AS NULL,
	[StateId] [bigint] NOT NULL,
	[AddressId] [bigint] NULL,
	[PPTAVVendorId] [bigint] NULL,
	[BusinessUnitId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
