CREATE TYPE [dbo].[BankAccount] AS TABLE(
	[AccountName] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[AccountNumber_CT] [varbinary](max) NULL,
	[LegalEntityAccountNumber] [nvarchar](22) COLLATE Latin1_General_CI_AS NULL,
	[LastFourDigitAccountNumber] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[IBAN] [nvarchar](34) COLLATE Latin1_General_CI_AS NULL,
	[IsOneTimeACHOnly] [bit] NOT NULL,
	[IsExpired] [bit] NOT NULL,
	[IsOwnersAuthorizationReceived] [bit] NOT NULL,
	[AuthorizationDate] [date] NULL,
	[IsPrimaryACH] [bit] NOT NULL,
	[ExternalPackageCheckBookID] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[DefaultToAP] [bit] NOT NULL,
	[AccountType] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[GLSegmentValue] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[RemittanceType] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[DefaultAccountFor] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[IsFromCustomerPortal] [bit] NOT NULL,
	[UniqueIdentifier] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[PaymentProfileId] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[AutomatedPaymentMethod] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[ACHFailureCount] [int] NULL,
	[OnHold] [bit] NOT NULL,
	[AccountOnHoldCount] [int] NULL,
	[BankBranchId] [bigint] NULL,
	[CurrencyId] [bigint] NULL,
	[ReceiptGLTemplateId] [bigint] NULL,
	[BankAccountCategoryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
