CREATE TYPE [dbo].[BankBranch] AS TABLE(
	[Name] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IsActive] [bit] NOT NULL,
	[ABARoutingNumber_CT] [varbinary](48) NULL,
	[ACHRoutingNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[SWIFTCode_CT] [varbinary](48) NULL,
	[TransitCode_CT] [varbinary](48) NULL,
	[BankName] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[BankCode] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[InternalBankNumber_CT] [varbinary](48) NULL,
	[IsPAP] [bit] NOT NULL,
	[ElectronicNetworkSupportedForFinancialTransactions] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsFromCustomerPortal] [bit] NOT NULL,
	[ShouldValidateTransitCodeLength] [bit] NOT NULL,
	[GenerateControlFile] [bit] NOT NULL,
	[GenerateBalancedACH] [bit] NOT NULL,
	[RecurringACHPAPLeadDays] [int] NULL,
	[OneTimeACHLeadDays] [int] NULL,
	[NACHAFilePaddingOption] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[BusinessCalendarId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[CountryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
