CREATE TYPE [dbo].[BCITransactionTableParameters] AS TABLE(
	[AmountBilledToDate] [decimal](18, 8) NULL,
	[AdminDestinationCity] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[BatchStatus] [int] NULL,
	[Status] [int] NULL,
	[LineItemNumber] [int] NULL,
	[CustomerCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Cost] [decimal](18, 8) NULL,
	[CompanyCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DocumentNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DocumentDate] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DestinationTaxAreaId] [bigint] NULL,
	[DestinationPostalCode] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[DestinationMainDivision] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[DestinationCountry] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ExtendedPrice] [decimal](18, 8) NULL,
	[FlexibleNumericField5] [decimal](18, 8) NULL,
	[FlexibleNumericField4] [decimal](18, 8) NULL,
	[FlexibleNumericField3] [decimal](18, 8) NULL,
	[FlexibleNumericField2] [decimal](18, 8) NULL,
	[FlexibleNumericField1] [decimal](18, 8) NULL,
	[FlexibleDateField1] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField20] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField19] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField18] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField17] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField16] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField15] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField14] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField13] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField12] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField11] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField10] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField9] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField8] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField7] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField6] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField5] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField4] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField3] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField2] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FlexibleCodeField1] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[FairMarketValue] [decimal](18, 8) NULL,
	[GeneralLedgerAccount] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LocationCode] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ProductCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TaxAreaId] [bigint] NULL,
	[TransactionType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[TransactionId] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL
)
GO
