CREATE TYPE [dbo].[BookDepreciation] AS TABLE(
	[CostBasis_Amount] [decimal](16, 2) NOT NULL,
	[CostBasis_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Salvage_Amount] [decimal](16, 2) NOT NULL,
	[Salvage_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BeginDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[RemainingLifeInMonths] [int] NOT NULL,
	[PerDayDepreciationFactor] [decimal](18, 8) NOT NULL,
	[TerminatedDate] [date] NULL,
	[IsActive] [bit] NOT NULL,
	[IsInOTP] [bit] NOT NULL,
	[LastAmortRunDate] [date] NULL,
	[ReversalPostDate] [date] NULL,
	[IsLessorOwned] [bit] NOT NULL,
	[IsLeaseComponent] [bit] NOT NULL,
	[AssetId] [bigint] NOT NULL,
	[ContractId] [bigint] NULL,
	[GLTemplateId] [bigint] NOT NULL,
	[ClearAccumulatedGLJournalId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NOT NULL,
	[LineofBusinessId] [bigint] NOT NULL,
	[CostCenterId] [bigint] NULL,
	[BookDepreciationTemplateId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
