CREATE TYPE [dbo].[ChargeOff] AS TABLE(
	[ChargeOffDate] [date] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ChargeOffAmount_Amount] [decimal](16, 2) NULL,
	[ChargeOffAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ChargeOffProcessingDate] [date] NULL,
	[PostDate] [date] NULL,
	[ContractType] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsActive] [bit] NOT NULL,
	[Status] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsRecovery] [bit] NOT NULL,
	[NetInvestmentWithBlended_Amount] [decimal](16, 2) NOT NULL,
	[NetInvestmentWithBlended_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[GrossWritedown_Amount] [decimal](16, 2) NOT NULL,
	[GrossWritedown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NetWritedown_Amount] [decimal](16, 2) NOT NULL,
	[NetWritedown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LeaseComponentAmount_Amount] [decimal](16, 2) NULL,
	[LeaseComponentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NonLeaseComponentAmount_Amount] [decimal](16, 2) NULL,
	[NonLeaseComponentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[LeaseComponentGain_Amount] [decimal](16, 2) NULL,
	[LeaseComponentGain_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NonLeaseComponentGain_Amount] [decimal](16, 2) NULL,
	[NonLeaseComponentGain_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[GLTemplateId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[ReceiptId] [bigint] NULL,
	[ChargeOffReasonCodeConfigId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
