CREATE TYPE [dbo].[ContractOrigination] AS TABLE(
	[OriginationFee_Amount] [decimal](16, 2) NOT NULL,
	[OriginationFee_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[OriginationScrapeFactor] [decimal](8, 4) NOT NULL,
	[IsOriginationGeneratePayable] [bit] NOT NULL,
	[ManagementSegment] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[DocFeeAmount_Amount] [decimal](16, 2) NULL,
	[DocFeeAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ScrapeWithholdingTaxRate] [decimal](5, 2) NULL,
	[CommissionType] [nvarchar](16) COLLATE Latin1_General_CI_AS NOT NULL,
	[CommissionValueExcludingVAT_Amount] [decimal](16, 2) NOT NULL,
	[CommissionValueExcludingVAT_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[OriginationSourceTypeId] [bigint] NULL,
	[OriginationSourceId] [bigint] NULL,
	[ProgramId] [bigint] NULL,
	[OriginationSourceUserId] [bigint] NULL,
	[AcquiredPortfolioId] [bigint] NULL,
	[OriginationFeeBlendedItemCodeId] [bigint] NULL,
	[OriginatorPayableRemitToId] [bigint] NULL,
	[ScrapePayableCodeId] [bigint] NULL,
	[OriginatingLineofBusinessId] [bigint] NULL,
	[ProgramVendorOriginationSourceId] [bigint] NULL,
	[DocFeeReceivableCodeId] [bigint] NULL,
	[OriginationChannelId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
