CREATE TYPE [dbo].[ContractLateFee] AS TABLE(
	[InvoiceGraceDays] [int] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[LateFeeFloorAmount_Amount] [decimal](16, 2) NOT NULL,
	[LateFeeFloorAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LateFeeCeilingAmount_Amount] [decimal](16, 2) NOT NULL,
	[LateFeeCeilingAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[WaiveIfLateFeeBelow_Amount] [decimal](16, 2) NULL,
	[WaiveIfLateFeeBelow_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[WaiveIfInvoiceAmountBelow_Amount] [decimal](16, 2) NULL,
	[WaiveIfInvoiceAmountBelow_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceGraceDaysAtInception] [int] NULL,
	[Spread] [decimal](5, 2) NULL,
	[InterestFloorPercentage] [decimal](5, 2) NULL,
	[InterestCeilingPercentage] [decimal](5, 2) NULL,
	[HolidayMethod] [nvarchar](22) COLLATE Latin1_General_CI_AS NULL,
	[IsMoveAcrossMonth] [bit] NOT NULL,
	[IsIndexPercentage] [bit] NOT NULL,
	[PercentageBasis] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[Percentage] [decimal](8, 4) NULL,
	[IsActive] [bit] NOT NULL,
	[LateFeeTemplateId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
