CREATE TYPE [dbo].[ContractDataType] AS TABLE(
	[LegalEntityName] [nvarchar](200) COLLATE Latin1_General_CI_AS NOT NULL,
	[Inventory_CT_GL] [decimal](16, 2) NOT NULL,
	[ETC_LAC_CT_GL] [decimal](16, 2) NOT NULL,
	[CapitalizedCost_LAC_CT_GL] [decimal](16, 2) NOT NULL,
	[SyndicationLARTI_CT_GL] [decimal](16, 2) NOT NULL,
	[PaidOffAssets_LAC_Table] [decimal](16, 2) NOT NULL,
	[PaidOffAssets_LAC_ETC_Table] [decimal](16, 2) NOT NULL,
	[LeasedAssetReturnedtoInventory_CT_GL] [decimal](16, 2) NOT NULL,
	[ETC_CT_GL] [decimal](16, 2) NOT NULL,
	[CapitalizedCost_CT_GL] [decimal](16, 2) NOT NULL,
	[ClearedDepreciation_CT_GL] [decimal](16, 2) NOT NULL,
	[ClearedImpairment_CT_GL] [decimal](16, 2) NOT NULL,
	[AccumulatedFixedTermDepreciation_CT_GL] [decimal](16, 2) NOT NULL,
	[AccumulatedOTPDepreciation_CT_GL] [decimal](16, 2) NOT NULL,
	[AccumulatedAssetDepreciation_CT_GL] [decimal](16, 2) NOT NULL,
	[AccumulatedNBVImpairment_CT_GL] [decimal](16, 2) NOT NULL,
	[AccumulatedAssetImpairment_CT_GL] [decimal](16, 2) NOT NULL,
	[CostofGoodsSold_CT_GL] [decimal](16, 2) NOT NULL,
	[ChargeOff_CT_GL] [decimal](16, 2) NOT NULL,
	[OperatingAmortCleared_CT_GL] [decimal](16, 2) NOT NULL,
	[CapitalAmortCleared_CT_GL] [decimal](16, 2) NOT NULL,
	[PaidOffAssets_Inventory_Table] [decimal](16, 2) NOT NULL,
	[LeasedAssets_Inventory_Table] [decimal](16, 2) NOT NULL,
	[PaidOffAssets_LARTI_GL] [decimal](16, 2) NOT NULL,
	[ActiveAssets_ETC_Table] [decimal](16, 2) NOT NULL,
	[PaidOffAssets_ETC_Table] [decimal](16, 2) NOT NULL,
	[FinanceChargeOffAmount_Table] [decimal](16, 2) NOT NULL
)
GO
