CREATE TYPE [dbo].[ContractCollectionDetail] AS TABLE(
	[OneToThirtyDaysLate] [int] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ThirtyPlusDaysLate] [int] NOT NULL,
	[SixtyPlusDaysLate] [int] NOT NULL,
	[NinetyPlusDaysLate] [int] NOT NULL,
	[OneHundredTwentyPlusDaysLate] [int] NOT NULL,
	[LegacyZeroPlusDaysLate] [int] NOT NULL,
	[LegacyThirtyPlusDaysLate] [int] NOT NULL,
	[LegacySixtyPlusDaysLate] [int] NOT NULL,
	[LegacyNinetyPlusDaysLate] [int] NOT NULL,
	[LegacyOneHundredTwentyPlusDaysLate] [int] NOT NULL,
	[TotalOneToThirtyDaysLate] [int] NOT NULL,
	[TotalThirtyPlusDaysLate] [int] NOT NULL,
	[TotalSixtyPlusDaysLate] [int] NOT NULL,
	[TotalNinetyPlusDaysLate] [int] NOT NULL,
	[TotalOneHundredTwentyPlusDaysLate] [int] NOT NULL,
	[InterestDPD] [int] NOT NULL,
	[RentOrPrincipalDPD] [int] NOT NULL,
	[MaturityDPD] [int] NOT NULL,
	[OverallDPD] [int] NOT NULL,
	[CalculateDeliquencyDetails] [bit] NOT NULL,
	[ContractId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
