CREATE TYPE [dbo].[Court] AS TABLE(
	[CourtName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ClerkOfCourtPhoneNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[CourtType] [nvarchar](7) COLLATE Latin1_General_CI_AS NULL,
	[AddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[City] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Region] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[PostalCode] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[ECMUserName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ECMPassword] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ECMWebPOCFilingLink] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ECMTrainingLink] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[DeactivationDate] [date] NULL,
	[ReactivationDate] [date] NULL,
	[Comments] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[AddressLine3] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Neighborhood] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[SubdivisionOrMunicipality] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[StateId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
