CREATE TYPE [dbo].[Covenant] AS TABLE(
	[Frequency] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Type] [nvarchar](22) COLLATE Latin1_General_CI_AS NOT NULL,
	[Status] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[StatementDate] [date] NOT NULL,
	[StatusDueDate] [date] NOT NULL,
	[TargetMinimumAmount] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[TargetMaximumAmount] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ReviewDays] [int] NULL,
	[ToEmail] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[CcEmail] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NOT NULL,
	[RemediationPlanNarrative] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsPrimaryCustomer] [bit] NOT NULL,
	[RelationshipType] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[LastStatus] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[LastStatementDate] [date] NULL,
	[LastStatusDate] [date] NULL,
	[LastReviewStatus] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[LastReviewStatementDate] [date] NULL,
	[LastReviewStatusDate] [date] NULL,
	[IsActive] [bit] NOT NULL,
	[IsOverDue] [bit] NOT NULL,
	[LastReviewById] [bigint] NULL,
	[ThirdPartyDealRelationshipId] [bigint] NULL,
	[CreditDecisionId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
