CREATE TYPE [dbo].[CPIContract] AS TABLE(
	[Number] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[EntityType] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[CommencementDate] [date] NOT NULL,
	[NextStartDate] [date] NULL,
	[BaseFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NOT NULL,
	[BasePaymentFrequencyDays] [int] NOT NULL,
	[OverageFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NOT NULL,
	[OveragePaymentFrequencyDays] [int] NOT NULL,
	[DueDay] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[TerminationDate] [date] NULL,
	[IsInventory] [bit] NOT NULL,
	[BasePassThroughPercentage] [int] NULL,
	[OveragePassThroughPercentage] [int] NULL,
	[OveragePayableWithholdingTaxRate] [decimal](5, 2) NULL,
	[CustomerId] [bigint] NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[ContractId] [bigint] NULL,
	[RemitToId] [bigint] NOT NULL,
	[BillToId] [bigint] NOT NULL,
	[BaseBillingReceivableCodeId] [bigint] NULL,
	[OverageReceivableCodeId] [bigint] NULL,
	[AdminFeeReceivableCodeId] [bigint] NULL,
	[CurrencyId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NOT NULL,
	[LineofBusinessId] [bigint] NOT NULL,
	[CostCenterId] [bigint] NOT NULL,
	[BasePayableCodeId] [bigint] NULL,
	[OveragePayableCodeId] [bigint] NULL,
	[PassThroughVendorId] [bigint] NULL,
	[PassThroughRemitToId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
