CREATE TYPE [dbo].[CPISchedule] AS TABLE(
	[Number] [int] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[BeginDate] [date] NOT NULL,
	[NextStartDate] [date] NULL,
	[ApplyByAsset] [bit] NOT NULL,
	[BaseRateCalculated] [bit] NOT NULL,
	[BaseRate] [decimal](8, 4) NOT NULL,
	[BaseAllowance] [int] NOT NULL,
	[BaseAmount_Amount] [decimal](16, 2) NOT NULL,
	[BaseAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AdminFee_Amount] [decimal](16, 2) NULL,
	[AdminFee_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[OverageTier] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[BaseChargeGeneratedTillDate] [date] NULL,
	[OverageChargeGeneratedTillDate] [date] NULL,
	[BaseStepPayments] [bit] NOT NULL,
	[OverageStepPayments] [bit] NOT NULL,
	[BaseStepPercentage] [decimal](5, 2) NULL,
	[OverageStepPercentage] [decimal](5, 2) NULL,
	[BaseStepPeriod] [int] NULL,
	[OverageStepPeriod] [int] NULL,
	[BaseStepPaymentEffectiveDate] [date] NULL,
	[OverageStepPaymentEffectiveDate] [date] NULL,
	[MeterTypeId] [bigint] NOT NULL,
	[TaxLocationId] [bigint] NULL,
	[CPIContractId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
