CREATE TYPE [dbo].[CreateReceivablesForAssetSaleParam] AS TABLE(
	[ReceivableTempId] [bigint] NULL,
	[EntityType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EntityId] [bigint] NULL,
	[DueDate] [datetime] NULL,
	[IsDummy] [bit] NULL,
	[IsActive] [bit] NULL,
	[TotalAmount] [decimal](16, 2) NULL,
	[InvoiceReceivableGroupingOption] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceComment] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableCodeId] [bigint] NULL,
	[TaxRemitToId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[IsCollected] [bit] NULL,
	[IsServiced] [bit] NULL,
	[SourceTable] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[SourceId] [bigint] NULL,
	[AlternateBillingCurrencyId] [bigint] NULL,
	[ExchangeRate] [decimal](20, 10) NULL,
	[AssetSaleReceivableId] [bigint] NULL,
	[FunderId] [bigint] NULL,
	[TotalBalance] [decimal](16, 2) NULL,
	[TotalEffectiveBalance] [decimal](16, 2) NULL,
	[TotalBookBalance] [decimal](16, 2) NULL
)
GO
