CREATE TYPE [dbo].[CreditApplication] AS TABLE(
	[CreditApplicationSourceType] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Comments] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Status] [nvarchar](19) COLLATE Latin1_General_CI_AS NULL,
	[IsSalesTaxExempt] [bit] NOT NULL,
	[IsHostedsolution] [bit] NOT NULL,
	[EquipmentDescription] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[CostDetails] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[IsFromVendorPortal] [bit] NOT NULL,
	[NoOfWorkItemsRemaining] [int] NULL,
	[AdditionalInformation] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ExternalApplicationId] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SubmittedToCreditDate] [date] NULL,
	[IsCreateCustomer] [bit] NOT NULL,
	[IsPreApproved] [bit] NOT NULL,
	[IsPaymentScheduleParameterChanged] [bit] NOT NULL,
	[IsPricingPerformed] [bit] NOT NULL,
	[IsVATAssessedForPayable] [bit] NOT NULL,
	[IsVATAssessedForReceivable] [bit] NOT NULL,
	[TaxRegistrationId] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[EffectiveDate] [date] NULL,
	[DealerEmail] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[DealerPhoneNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[PartyId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[EquipmentVendorId] [bigint] NULL,
	[BillingAddressId] [bigint] NULL,
	[TransactionTypeId] [bigint] NOT NULL,
	[DealTypeId] [bigint] NOT NULL,
	[VendorContactId] [bigint] NULL,
	[VendorUserId] [bigint] NULL,
	[PreApprovalLOCId] [bigint] NULL,
	[ProgramId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
