CREATE TYPE [dbo].[CreditProfile] AS TABLE(
	[Number] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[RequestedAmount_Amount] [decimal](16, 2) NOT NULL,
	[RequestedAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ApprovedAmount_Amount] [decimal](16, 2) NULL,
	[ApprovedAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ToleranceAmount_Amount] [decimal](16, 2) NOT NULL,
	[ToleranceAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[UsedAmount_Amount] [decimal](16, 2) NULL,
	[UsedAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsSyndicated] [bit] NOT NULL,
	[IsRevolving] [bit] NOT NULL,
	[IsCommitted] [bit] NOT NULL,
	[Comment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Status] [nvarchar](31) COLLATE Latin1_General_CI_AS NULL,
	[CreditCancelReasonCode] [nvarchar](26) COLLATE Latin1_General_CI_AS NULL,
	[RegBDeclinationCode] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[IsSNCCode] [bit] NOT NULL,
	[SNCRating] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[SNCRole] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[SNCAgent] [nvarchar](7) COLLATE Latin1_General_CI_AS NULL,
	[SNCRatingDate] [date] NULL,
	[IsCostConfigUsed] [bit] NOT NULL,
	[IsPreApproval] [bit] NOT NULL,
	[IsPreApproved] [bit] NOT NULL,
	[IsConfidential] [bit] NOT NULL,
	[IsConduit] [bit] NOT NULL,
	[IsFederalIncomeTaxExempt] [bit] NOT NULL,
	[BankQualified] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[HoldingStatus] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionId] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[IsHostedsolution] [bit] NOT NULL,
	[CapitalStreamProductType] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[ReplacementSchedule] [bit] NOT NULL,
	[PeakExposure_Amount] [decimal](16, 2) NULL,
	[PeakExposure_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ManagementSegment] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[IsCreditInLW] [bit] NOT NULL,
	[CreditAppVerified] [bit] NOT NULL,
	[IsPGChanged] [bit] NOT NULL,
	[CustomerLookUpStatus] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsCreditDataGatheringDone] [bit] NOT NULL,
	[IsOFACReviewDone] [bit] NOT NULL,
	[IsCustomerLookupComplete] [bit] NOT NULL,
	[IsAdditionalApprovalComplete] [bit] NOT NULL,
	[StatusDate] [date] NULL,
	[ReportStatus] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[CustomerCreditScore] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[DocumentMethod] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[SFDCUniqueId] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SingleSignOnIdentification] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsFutureFunding] [bit] NOT NULL,
	[IsCustomerCreationRequired] [bit] NOT NULL,
	[ServicingRole] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[CustomerId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[OpportunityId] [bigint] NULL,
	[OriginationSourceTypeId] [bigint] NOT NULL,
	[OriginationSourceId] [bigint] NULL,
	[ProgramId] [bigint] NULL,
	[ProgramVendorOriginationSourceId] [bigint] NULL,
	[OriginationSourceUserId] [bigint] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[AcquiredPortfolioId] [bigint] NULL,
	[ReferralBankerId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[LineOfCreditId] [bigint] NULL,
	[ShellCustomerDetailId] [bigint] NULL,
	[ShellCustomerContactId] [bigint] NULL,
	[ShellCustomerAddressId] [bigint] NULL,
	[CostCenterId] [bigint] NOT NULL,
	[EquipmentVendorId] [bigint] NULL,
	[ProductAndServiceTypeConfigId] [bigint] NULL,
	[PreApprovalLOCId] [bigint] NULL,
	[BusinessUnitId] [bigint] NOT NULL,
	[CountryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
