CREATE TYPE [dbo].[CreditProfileShellAsset] AS TABLE(
	[ModalityName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Quantity] [int] NOT NULL,
	[ManufacturerName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[EquipmentLocation] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[EquipmentDescription] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[ModelYear] [decimal](4, 0) NULL,
	[Model] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Alias] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[UsageCondition] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[Status] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[InServiceDate] [date] NULL,
	[IsRealAsset] [bit] NOT NULL,
	[SellingPrice_Amount] [decimal](16, 2) NULL,
	[SellingPrice_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[AssetId] [bigint] NULL,
	[ProposalShellAssetId] [bigint] NULL,
	[AssetCatalogId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[AssetTypeId] [bigint] NULL,
	[CreditProfileId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
