CREATE TYPE [dbo].[CreditProfileCustomer] AS TABLE(
	[IsCorporate] [bit] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IsSoleProprietor] [bit] NOT NULL,
	[FirstName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LastName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CompanyName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[CustomerName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[UniqueIdentificationNumber_CT] [varbinary](32) NULL,
	[LastFourDigitUniqueIdentificationNumber] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[CreationDate] [date] NOT NULL,
	[LegalNameValidationDate] [date] NOT NULL,
	[Status] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[CIPDocumentSourceForName] [nvarchar](61) COLLATE Latin1_General_CI_AS NULL,
	[PartyType] [nvarchar](42) COLLATE Latin1_General_CI_AS NOT NULL,
	[IncomeTaxStatus] [nvarchar](18) COLLATE Latin1_General_CI_AS NOT NULL,
	[DateOfBirth] [date] NULL,
	[PercentageOfGovernmentOwnership] [decimal](5, 2) NULL,
	[IsBillingAddressSameAsMain] [bit] NOT NULL,
	[AddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[City] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Division] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PostalCode] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[Description] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[HomeAddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[HomeAddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[HomeCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[HomeDivision] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[HomePostalCode] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[ConsentDate] [date] NULL,
	[LegalFormationTypeConfigId] [bigint] NOT NULL,
	[StateOfIncorporationId] [bigint] NOT NULL,
	[BusinessTypeId] [bigint] NOT NULL,
	[CustomerId] [bigint] NULL,
	[BusinessTypeNAICSCodeId] [bigint] NULL,
	[BusinessTypesSICsCodeId] [bigint] NULL,
	[ApprovedExchangeId] [bigint] NULL,
	[ApprovedRegulatorId] [bigint] NULL,
	[JurisdictionOfSovereignId] [bigint] NULL,
	[StateId] [bigint] NULL,
	[HomeStateId] [bigint] NULL,
	[CIPDocumentSourceNameId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
