CREATE TYPE [dbo].[CustomerThirdPartyRelationship] AS TABLE(
	[RelationshipType] [nvarchar](30) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[ActivationDate] [date] NOT NULL,
	[DeactivationDate] [date] NULL,
	[IsNewRelation] [bit] NOT NULL,
	[IsNewContact] [bit] NOT NULL,
	[IsNewAddress] [bit] NOT NULL,
	[IsFromAssumption] [bit] NOT NULL,
	[IsAssumptionApproved] [bit] NOT NULL,
	[Scope] [nvarchar](7) COLLATE Latin1_General_CI_AS NULL,
	[Coverage] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[LimitByDurationInMonths] [int] NULL,
	[LimitByPercentage] [decimal](5, 2) NULL,
	[LimitByAmount_Amount] [decimal](16, 2) NULL,
	[LimitByAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PersonalGuarantorCustomerOrContact] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[ThirdPartyId] [bigint] NULL,
	[ThirdPartyAddressId] [bigint] NULL,
	[ThirdPartyContactId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[CustomerId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
