CREATE TYPE [dbo].[CustomerLocationTaxBasisProcessingDetail_Extract] AS TABLE(
	[City] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Country] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[DueDate] [date] NOT NULL,
	[LeaseType] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[LeaseUniqueID] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[ContractId] [bigint] NOT NULL,
	[Company] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[LegalEntityName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Currency] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[ToState] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[AssetId] [bigint] NULL,
	[LineItemId] [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
	[LocationId] [bigint] NOT NULL,
	[ContractType] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerNumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxAreaId] [bigint] NOT NULL,
	[CustomerLocationId] [bigint] NOT NULL,
	[BatchId] [bigint] NOT NULL,
	[JobStepInstanceId] [bigint] NOT NULL,
	[LocationCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
