CREATE TYPE [dbo].[DealExposure] AS TABLE(
	[EntityType] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[EntityId] [bigint] NOT NULL,
	[ExposureDate] [date] NOT NULL,
	[ExposureType] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[RelationshipPercentage] [decimal](5, 2) NOT NULL,
	[CommencedDealRNI_Amount] [decimal](24, 2) NOT NULL,
	[CommencedDealRNI_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[CommencedDealExposure_Amount] [decimal](24, 2) NOT NULL,
	[CommencedDealExposure_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[OTPLeaseRNI_Amount] [decimal](24, 2) NOT NULL,
	[OTPLeaseRNI_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[OTPLeaseExposure_Amount] [decimal](24, 2) NOT NULL,
	[OTPLeaseExposure_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[UncommencedDealRNI_Amount] [decimal](24, 2) NOT NULL,
	[UncommencedDealRNI_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[UncommencedDealExposure_Amount] [decimal](24, 2) NOT NULL,
	[UncommencedDealExposure_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LOCBalanceRevolving_Amount] [decimal](24, 2) NOT NULL,
	[LOCBalanceRevolving_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LOCBalanceNonRevolving_Amount] [decimal](24, 2) NOT NULL,
	[LOCBalanceNonRevolving_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LOCBalanceExposure_Amount] [decimal](24, 2) NOT NULL,
	[LOCBalanceExposure_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TotalExposure_Amount] [decimal](24, 2) NOT NULL,
	[TotalExposure_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CustomerId] [bigint] NOT NULL,
	[ExposureCustomerId] [bigint] NOT NULL,
	[RNIId] [bigint] NULL,
	[OriginatingVendorId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
