CREATE TYPE [dbo].[DeferredTaxDetail] AS TABLE(
	[TaxableIncomeTax_Amount] [decimal](16, 2) NOT NULL,
	[TaxableIncomeTax_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TaxableIncomeBook_Amount] [decimal](16, 2) NOT NULL,
	[TaxableIncomeBook_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BookDepreciation_Amount] [decimal](16, 2) NOT NULL,
	[BookDepreciation_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxDepreciation_Amount] [decimal](16, 2) NOT NULL,
	[TaxDepreciation_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IncomeTaxExpense_Amount] [decimal](16, 2) NOT NULL,
	[IncomeTaxExpense_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IncomeTaxPayable_Amount] [decimal](16, 2) NOT NULL,
	[IncomeTaxPayable_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[YTDDeferredTax_Amount] [decimal](16, 2) NOT NULL,
	[YTDDeferredTax_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AccumDefTaxLiabBalance_Amount] [decimal](16, 2) NOT NULL,
	[AccumDefTaxLiabBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxIncome_Amount] [decimal](16, 2) NOT NULL,
	[TaxIncome_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BookIncome_Amount] [decimal](16, 2) NOT NULL,
	[BookIncome_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[DefTaxLiabBalance_Amount] [decimal](16, 2) NOT NULL,
	[DefTaxLiabBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[MTDDeferredTax_Amount] [decimal](16, 2) NOT NULL,
	[MTDDeferredTax_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AssetId] [bigint] NOT NULL,
	[DeferredTaxId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
