CREATE TYPE [dbo].[DisbursementRequest] AS TABLE(
	[PostDate] [date] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Status] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ImportInvoice] [bit] NOT NULL,
	[ApplyByPayable] [bit] NOT NULL,
	[PaymentDate] [date] NULL,
	[OriginationType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[ContractSequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsScheduledFunding] [bit] NOT NULL,
	[Type] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[IsFromPI] [bit] NOT NULL,
	[ClearingOption] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableDueDate] [date] NULL,
	[PayeeId] [bigint] NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[CurrencyId] [bigint] NULL,
	[ContractCurrencyId] [bigint] NULL,
	[RejectionReasonId] [bigint] NULL,
	[APGLTemplateId] [bigint] NULL,
	[ReceiptId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[SundryId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
