CREATE TYPE [dbo].[DiscountingFinance] AS TABLE(
	[SharedPercentage] [decimal](5, 2) NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TotalPaymentSold_Amount] [decimal](24, 2) NULL,
	[TotalPaymentSold_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[CalculateRate] [bit] NOT NULL,
	[DiscountRate] [decimal](14, 9) NULL,
	[DiscountingProceedsAmount_Amount] [decimal](16, 2) NULL,
	[DiscountingProceedsAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[SuggestedDiscountingProceedsAmount_Amount] [decimal](16, 2) NULL,
	[SuggestedDiscountingProceedsAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsCurrent] [bit] NOT NULL,
	[PostDate] [date] NULL,
	[Tied] [bit] NOT NULL,
	[EffectiveDate] [date] NULL,
	[Recourse] [bit] NOT NULL,
	[BookingStatus] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[BookedResidual_Amount] [decimal](16, 2) NULL,
	[BookedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ApprovalStatus] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[ModificationType] [nvarchar](11) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsPricingParametersChanged] [bit] NOT NULL,
	[IsPricingPerformed] [bit] NOT NULL,
	[PricingDayCountConvention] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[PricingCompoundingFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[CommencementDate] [date] NULL,
	[PaymentFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[CompoundingFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[DueDay] [int] NOT NULL,
	[DayCountConvention] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[PaymentNumberOfDays] [int] NOT NULL,
	[Term] [decimal](10, 6) NULL,
	[Advance] [bit] NOT NULL,
	[IsRegularPaymentStream] [bit] NOT NULL,
	[RegularPaymentAmount_Amount] [decimal](16, 2) NULL,
	[RegularPaymentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[MaturityDate] [date] NULL,
	[FrequencyStartDate] [date] NULL,
	[NumberOfPayments] [int] NULL,
	[Yield] [decimal](14, 9) NULL,
	[IsRepaymentScheduleGenerated] [bit] NOT NULL,
	[IsRepaymentScheduleParametersChanged] [bit] NOT NULL,
	[IsRepaymentPricingPerformed] [bit] NOT NULL,
	[IsRepaymentPricingParametersChanged] [bit] NOT NULL,
	[IsOnHold] [bit] NOT NULL,
	[AdditionalPaymentSold_Amount] [decimal](16, 2) NULL,
	[AdditionalPaymentSold_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[AdditionalBookedResidual_Amount] [decimal](16, 2) NULL,
	[AdditionalBookedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PaymentAllocation] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[InterestWithholdingTaxRate] [decimal](5, 2) NULL,
	[PrincipalWithholdingTaxRate] [decimal](5, 2) NULL,
	[DiscountingId] [bigint] NOT NULL,
	[DiscountingGLTemplateId] [bigint] NULL,
	[ExpenseRecognitionGLTemplateId] [bigint] NULL,
	[DiscountingProceedsReceivableCodeId] [bigint] NULL,
	[DiscountingProceedsBillToId] [bigint] NULL,
	[DiscountingProceedsRemitToId] [bigint] NULL,
	[DiscountingInterestPayableCodeId] [bigint] NULL,
	[DiscountingPrincipalPayableCodeId] [bigint] NULL,
	[DiscountingPayablesRemitToId] [bigint] NULL,
	[CostCenterId] [bigint] NOT NULL,
	[LineOfBusinessId] [bigint] NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[InstrumentTypeId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[FunderId] [bigint] NOT NULL,
	[APTemplateId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
