CREATE TYPE [dbo].[DiscountingWriteDown] AS TABLE(
	[WriteDownDate] [date] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[WriteDownAmount_Amount] [decimal](16, 2) NULL,
	[WriteDownAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsRecovery] [bit] NOT NULL,
	[PostDate] [date] NULL,
	[GrossWriteDown_Amount] [decimal](16, 2) NULL,
	[GrossWriteDown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NBVPostAdjustments_Amount] [decimal](16, 2) NULL,
	[NBVPostAdjustments_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NetWriteDown_Amount] [decimal](16, 2) NULL,
	[NetWriteDown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[Status] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[NetInvestmentWithReserve_Amount] [decimal](16, 2) NULL,
	[NetInvestmentWithReserve_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[SourceId] [bigint] NOT NULL,
	[SourceModule] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[DiscountingId] [bigint] NOT NULL,
	[RecoveryGLTemplateId] [bigint] NOT NULL,
	[WriteDownGLTemplateId] [bigint] NULL,
	[DiscountingFinanceId] [bigint] NULL,
	[DiscountingWriteDownGLJournalId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
