CREATE TYPE [dbo].[DiscountingAmendment] AS TABLE(
	[AccountingDate] [date] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[AmendmentAtInception] [bit] NOT NULL,
	[AmendmentDate] [date] NOT NULL,
	[AmendmentType] [nvarchar](31) COLLATE Latin1_General_CI_AS NOT NULL,
	[Comment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[PostDate] [date] NULL,
	[QuoteGoodThroughDate] [date] NULL,
	[Alias] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[QuoteStatus] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[SourceId] [bigint] NULL,
	[QuoteNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[AdditionalLoanAmount_Amount] [decimal](16, 2) NULL,
	[AdditionalLoanAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PreRestructureLoanAmount_Amount] [decimal](16, 2) NULL,
	[PreRestructureLoanAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PreRestructureYield] [decimal](14, 9) NULL,
	[RestructureAmortOption] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[DiscountingFinanceId] [bigint] NOT NULL,
	[DiscountingRepaymentScheduleId] [bigint] NULL,
	[OriginalDiscountingFinanceId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
