CREATE TYPE [dbo].[DiscountingContract] AS TABLE(
	[EarliestDueDate] [date] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[EndDueDate] [date] NOT NULL,
	[DiscountRate] [decimal](14, 9) NULL,
	[PVOfCashInflow_Amount] [decimal](16, 2) NULL,
	[PVOfCashInflow_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[BookedResidual_Amount] [decimal](16, 2) NULL,
	[BookedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IncludeResidual] [bit] NOT NULL,
	[TotalPaymentSold_Amount] [decimal](16, 2) NULL,
	[TotalPaymentSold_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[ResidualBalance_Amount] [decimal](16, 2) NULL,
	[ResidualBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ReleasedDate] [date] NULL,
	[PaidOffDate] [date] NULL,
	[PaidOffId] [bigint] NULL,
	[IsNewlyAdded] [bit] NOT NULL,
	[AdditionalPaymentSold_Amount] [decimal](16, 2) NULL,
	[AdditionalPaymentSold_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[AdditionalBookedResidual_Amount] [decimal](16, 2) NULL,
	[AdditionalBookedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PVOfAdditionalCashInflow_Amount] [decimal](16, 2) NULL,
	[PVOfAdditionalCashInflow_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[AmendmentDate] [date] NULL,
	[ResidualFactor] [decimal](18, 8) NULL,
	[ContractId] [bigint] NOT NULL,
	[DiscountingFinanceId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
