CREATE TYPE [dbo].[DocumentType] AS TABLE(
	[Name] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[DocumentDirection] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[Category] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[Classification] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[ViewableAtRelatedEntities] [bit] NOT NULL,
	[AllowDuplicate] [bit] NOT NULL,
	[DefaultPermission] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[CreationAllowed] [nvarchar](7) COLLATE Latin1_General_CI_AS NOT NULL,
	[ManualEntitySelectionNeeded] [bit] NOT NULL,
	[DocumentTitleRequired] [bit] NOT NULL,
	[DefaultTitle] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[IsReadyToUse] [bit] NOT NULL,
	[GenerationAllowedExpression] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[IsRetention] [bit] NOT NULL,
	[IsCoverLetter] [bit] NOT NULL,
	[EntityId] [bigint] NOT NULL,
	[BusinessEntityId] [bigint] NULL,
	[RelatedDocTypeId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
