CREATE TYPE [dbo].[DocumentPack] AS TABLE(
	[Name] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[StatusDate] [date] NOT NULL,
	[CreatedDate] [date] NOT NULL,
	[Comment] [nvarchar](4000) COLLATE Latin1_General_CI_AS NULL,
	[EmailRowNumber] [int] NULL,
	[EmailSentTime] [datetimeoffset](7) NULL,
	[IsActive] [bit] NOT NULL,
	[EnabledForESignature] [bit] NOT NULL,
	[PackedFromId] [bigint] NOT NULL,
	[StatusId] [bigint] NOT NULL,
	[PackedById] [bigint] NOT NULL,
	[StatusChangedById] [bigint] NOT NULL,
	[EmailSentById] [bigint] NULL,
	[AttachmentId] [bigint] NULL,
	[DocumentHeaderId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
