CREATE TYPE [dbo].[DocumentInstance] AS TABLE(
	[EntityId] [bigint] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[EntityNaturalId] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[Title] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EffectiveDate] [date] NULL,
	[ExpiryDate] [date] NULL,
	[IsModificationRequired] [bit] NOT NULL,
	[ModificationReason] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[ModificationComment] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[ExceptionComment] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[IsGenerationAllowed] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsReadOnly] [bit] NOT NULL,
	[DefaultPermission] [nvarchar](1) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsRetention] [bit] NOT NULL,
	[DocumentTypeId] [bigint] NOT NULL,
	[DocumentTemplateId] [bigint] NULL,
	[DocumentTemplateDetailId] [bigint] NULL,
	[StatusId] [bigint] NOT NULL,
	[RelatedInstanceId] [bigint] NULL,
	[AttachmentDetailId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
