CREATE TYPE [dbo].[Driver] AS TABLE(
	[DriverCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[DriverType] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[ExternalDriverId] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EmployeeID] [int] NULL,
	[LicenseNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LicenseExpiryDate] [date] NULL,
	[LicenseIssueDate] [date] NULL,
	[ClassCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AnnualInsuranceCost] [decimal](16, 2) NULL,
	[PIN] [bigint] NULL,
	[Active] [bit] NOT NULL,
	[ActivationDate] [date] NULL,
	[DeactivationDate] [date] NULL,
	[CreationDate] [date] NOT NULL,
	[MVRRequired] [bit] NOT NULL,
	[MVRStatus] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[MVRReviewedBy] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[MVRLastReviewedDate] [date] NULL,
	[MVRLastRunDate] [date] NULL,
	[Reason] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[CustomerId] [bigint] NOT NULL,
	[RelatedDriverId] [bigint] NULL,
	[LicenseStateId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
