CREATE TYPE [dbo].[EnmasseMeterReadingInstance] AS TABLE(
	[RowId] [bigint] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[CPINumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetId] [bigint] NULL,
	[Alias] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SerialNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MeterType] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[EndPeriodDate] [date] NULL,
	[AssetBeginDate] [date] NULL,
	[BeginPeriodDate] [date] NULL,
	[ReadDate] [date] NULL,
	[BeginReading] [bigint] NULL,
	[OriginalBeginReading] [bigint] NULL,
	[EndReading] [bigint] NULL,
	[ServiceCredits] [bigint] NOT NULL,
	[Source] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[OriginalSource] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsEstimated] [bit] NOT NULL,
	[IsCorrection] [bit] NOT NULL,
	[IsFirstReading] [bit] NOT NULL,
	[MeterResetType] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[InstanceId] [uniqueidentifier] NULL,
	[IsFaulted] [bit] NOT NULL,
	[PortfolioId] [bigint] NULL,
	[IsAggregate] [bit] NOT NULL,
	[MeterMaxReading] [bigint] NULL,
	[IsFirstReadingCorrected] [bit] NOT NULL,
	[ContractSequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ScheduleNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MatchedAssetId] [bigint] NULL,
	[CPUAssetMeterReadingHeaderId] [bigint] NULL,
	[CPUScheduleId] [bigint] NULL,
	[CPUAssetId] [bigint] NULL,
	[AssetMeterTypeId] [bigint] NULL,
	[CPUContractId] [bigint] NULL,
	[CPUOverageAssessmentId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
