CREATE TYPE [dbo].[FeeDetail] AS TABLE(
	[Number] [int] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Name] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[FeePercent] [decimal](5, 2) NOT NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[FloorAmount_Amount] [decimal](16, 2) NOT NULL,
	[FloorAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[CeilingAmount_Amount] [decimal](16, 2) NOT NULL,
	[CeilingAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsActive] [bit] NULL,
	[Description] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[AccountingTreatment] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[SundryOrBlendedItem] [nvarchar](11) COLLATE Latin1_General_CI_AS NOT NULL,
	[Occurrence] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[FeeType] [nvarchar](7) COLLATE Latin1_General_CI_AS NULL,
	[FeeBasis] [nvarchar](26) COLLATE Latin1_General_CI_AS NULL,
	[SundryType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[GracePeriodInMonths] [int] NULL,
	[FeeAssessmentLevel] [nvarchar](13) COLLATE Latin1_General_CI_AS NOT NULL,
	[UsageCondition] [nvarchar](6) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsImport] [bit] NOT NULL,
	[BlendedItemCodeId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[FeeCategoryId] [bigint] NOT NULL,
	[FeeTemplateId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
