CREATE TYPE [dbo].[FinancialStatementDocument] AS TABLE(
	[LatestStatementDate] [date] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[UploadStatus] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[TotalAssets_Amount] [decimal](16, 2) NULL,
	[TotalAssets_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TotalLiabilities_Amount] [decimal](16, 2) NULL,
	[TotalLiabilities_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[CurrentAssets_Amount] [decimal](16, 2) NULL,
	[CurrentAssets_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[CurrentLiabilities_Amount] [decimal](16, 2) NULL,
	[CurrentLiabilities_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TNW_Amount] [decimal](16, 2) NULL,
	[TNW_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[EBITDA_Amount] [decimal](16, 2) NULL,
	[EBITDA_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[CPLTD_Amount] [decimal](16, 2) NULL,
	[CPLTD_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[InterestExpense_Amount] [decimal](16, 2) NULL,
	[InterestExpense_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NetIncome_Amount] [decimal](16, 2) NULL,
	[NetIncome_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[DebtToTNW] [decimal](16, 2) NULL,
	[ExceptionComment] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[DocumentRequirementId] [bigint] NULL,
	[StatusId] [bigint] NULL,
	[FinancialStatementId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
