CREATE TYPE [dbo].[Funder] AS TABLE(
	[Type] [nvarchar](15) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Status] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[RejectionReasonCode] [nvarchar](25) COLLATE Latin1_General_CI_AS NULL,
	[ActivationDate] [date] NULL,
	[DeactivationDate] [date] NULL,
	[NextReviewDate] [date] NULL,
	[InactivationReason] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[W8IssueDate] [date] NULL,
	[W8ExpirationDate] [date] NULL,
	[FATCA] [decimal](5, 0) NULL,
	[Percentage1441] [decimal](5, 0) NULL,
	[ApprovalStatus] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[StatusPostApproval] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsForFunderLegalEntityAddition] [bit] NOT NULL,
	[IsForFunderEdit] [bit] NOT NULL,
	[IsForFunderRemitToAddition] [bit] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
