CREATE TYPE [dbo].[GLManualJournalEntry] AS TABLE(
	[EntityType] [nvarchar](11) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[PostDate] [date] NOT NULL,
	[ReversalPostDate] [date] NULL,
	[ManualGLTransactionType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NOT NULL,
	[Status] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsGLExportRequired] [bit] NOT NULL,
	[ContractId] [bigint] NULL,
	[AssetId] [bigint] NULL,
	[AssetSaleId] [bigint] NULL,
	[ReceivableForTransferId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[GLJournalId] [bigint] NULL,
	[ReversalGLJournalId] [bigint] NULL,
	[LineofBusinessId] [bigint] NOT NULL,
	[InstrumentTypeId] [bigint] NOT NULL,
	[ReferenceGLManualId] [bigint] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[CostCenterId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
