CREATE TYPE [dbo].[GLTransferDealDetail] AS TABLE(
	[HoldingStatusComment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IncomeBalance_Amount] [decimal](16, 2) NULL,
	[IncomeBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[GLSegmentChangeComment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[NewAcquisitionId] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[NewBQNBQ] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[NewSOP] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[ExistingFinanceId] [bigint] NOT NULL,
	[ContractId] [bigint] NOT NULL,
	[NewLegalEntityId] [bigint] NULL,
	[BlendedItemCodeId] [bigint] NULL,
	[NewLineofBusinessId] [bigint] NULL,
	[NewCostCenterId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[ValuationAllowanceBlendedItemId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[BookDepreciationTemplateId] [bigint] NULL,
	[NewBranchId] [bigint] NULL,
	[GLTransferId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
