CREATE TYPE [dbo].[InterestRateDetail] AS TABLE(
	[IsFloatRate] [bit] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IsHighPrimeInterest] [bit] NOT NULL,
	[EffectiveDate] [date] NOT NULL,
	[BaseRate] [decimal](12, 6) NOT NULL,
	[Spread] [decimal](12, 6) NOT NULL,
	[InterestRate] [decimal](12, 6) NOT NULL,
	[FloorPercent] [decimal](10, 6) NOT NULL,
	[CeilingPercent] [decimal](10, 6) NOT NULL,
	[FloatRateResetFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[FloatRateResetUnit] [int] NOT NULL,
	[FirstResetDate] [date] NULL,
	[CompoundingFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[HolidayMoveMethod] [nvarchar](22) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[IsIndexPercentage] [bit] NOT NULL,
	[PercentageBasis] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[Percentage] [decimal](9, 5) NOT NULL,
	[IsLeadUnitsinBusinessDays] [bit] NOT NULL,
	[LeadFrequency] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[LeadUnits] [int] NOT NULL,
	[EffectiveDayofMonth] [int] NOT NULL,
	[IsMoveAcrossMonth] [bit] NOT NULL,
	[ModificationType] [nvarchar](31) COLLATE Latin1_General_CI_AS NULL,
	[IsNewlyAdded] [bit] NOT NULL,
	[BankIndexDescription] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsManualInterestMargin] [bit] NOT NULL,
	[InterestConfiguration] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RateCardInterest] [decimal](10, 6) NULL,
	[FloatRateIndexId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
