CREATE TYPE [dbo].[InvoiceExtractReceivableDetail] AS TABLE(
	[EntityType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[SequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EntityId] [bigint] NULL,
	[MaturityDate] [date] NULL,
	[ContractPurchaseOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BlendNumber] [int] NULL,
	[ReceivableAmount_Amount] [decimal](16, 2) NULL,
	[ReceivableAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TaxAmount_Amount] [decimal](16, 2) NULL,
	[TaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[WithHoldingTax_Amount] [decimal](16, 2) NOT NULL,
	[WithHoldingTax_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PeriodStartDate] [date] NULL,
	[PeriodEndDate] [date] NULL,
	[AssetAddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AssetAddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AssetCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetState] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[AssetDivision] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetCountry] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[AssetPostalCode] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[AssetPurchaseOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetSerialNumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AssetDescription] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[u_CustomerReference1] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[u_CustomerReference2] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[u_CustomerReference3] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[u_CustomerReference4] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[u_CustomerReference5] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AdditionalComments] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[AdditionalInvoiceCommentBeginDate] [date] NULL,
	[AdditionalInvoiceCommentEndDate] [date] NULL,
	[ExchangeRate] [decimal](20, 10) NULL,
	[IsDownPaymentVATReceivable] [bit] NOT NULL,
	[InvoiceId] [bigint] NOT NULL,
	[ReceivableInvoiceDetailId] [bigint] NOT NULL,
	[ReceivableDetailId] [bigint] NOT NULL,
	[AssetId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[ReceivableCategoryId] [bigint] NULL,
	[AlternateBillingCurrencyCodeId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
