CREATE TYPE [dbo].[InvoiceReceivableDetails_Extract] AS TABLE(
	[JobStepInstanceId] [bigint] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ReceivableId] [bigint] NOT NULL,
	[EntityType] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[ContractId] [bigint] NULL,
	[DiscountingId] [bigint] NULL,
	[ReceivableDetailId] [bigint] NOT NULL,
	[BillToId] [bigint] NOT NULL,
	[CustomerId] [bigint] NOT NULL,
	[ReceivableDetailAmount] [decimal](16, 2) NOT NULL,
	[ReceivableDetailBalance] [decimal](16, 2) NOT NULL,
	[ReceivableDetailEffectiveBalance] [decimal](16, 2) NOT NULL,
	[OriginalTaxBalance] [decimal](16, 2) NOT NULL,
	[OriginalEffectiveTaxBalance] [decimal](16, 2) NOT NULL,
	[ContractType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableTypeId] [bigint] NOT NULL,
	[ReceivableTypeName] [nvarchar](21) COLLATE Latin1_General_CI_AS NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[IsSyndicated] [bit] NOT NULL,
	[ReceivableDueDate] [date] NOT NULL,
	[RemitToId] [bigint] NOT NULL,
	[TaxRemitToId] [bigint] NOT NULL,
	[IsPrivateLabel] [bit] NOT NULL,
	[IsDSL] [bit] NOT NULL,
	[ExchangeRate] [decimal](20, 10) NULL,
	[AlternateBillingCurrencyId] [bigint] NULL,
	[AssetId] [bigint] NULL,
	[AdjustmentBasisReceivableDetailId] [bigint] NULL,
	[CapSoftAssetId] [bigint] NULL,
	[AdjustmentReceivableInvoiceId] [bigint] NULL,
	[IsWithHoldingTaxAssessed] [bit] NOT NULL,
	[WithHoldingTaxBalance] [decimal](16, 2) NULL,
	[LocationId] [bigint] NULL,
	[ReceivableCategoryId] [bigint] NULL,
	[ReceivableCategoryName] [nvarchar](16) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceFormatId] [bigint] NOT NULL,
	[InvoiceOutputFormat] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[IsReceivableTypeRental] [bit] NOT NULL,
	[ReceivableCodeId] [bigint] NOT NULL,
	[DefaultInvoiceReceivableGroupingOption] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceDueDateCalculation] [nvarchar](19) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceDueDate] [date] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[CurrencyISO] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ACHScheduleId] [bigint] NULL,
	[IsACH] [bit] NOT NULL,
	[InvoiceComment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[CT_InvoiceTransitDays] [int] NULL,
	[CT_InvoiceLeadDays] [int] NULL,
	[CU_InvoiceTransitDays] [int] NOT NULL,
	[CU_InvoiceLeadDays] [int] NOT NULL,
	[InvoicePreference] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[GenerateSummaryInvoice] [bit] NOT NULL,
	[SplitRentalInvoiceByAsset] [bit] NOT NULL,
	[SplitCreditsByOriginalInvoice] [bit] NOT NULL,
	[SplitByReceivableAdjustments] [bit] NOT NULL,
	[SplitRentalInvoiceByContract] [bit] NOT NULL,
	[SplitLeaseRentalInvoiceByLocation] [bit] NOT NULL,
	[SplitReceivableDueDate] [bit] NOT NULL,
	[SplitCustomerPurchaseOrderNumber] [bit] NOT NULL,
	[GroupNumber] [int] NULL,
	[SplitNumber] [int] NULL,
	[BlendNumber] [int] NULL,
	[GenerateStatementInvoice] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsFunderOwnedReceivable] [bit] NOT NULL,
	[ReceivableAmount] [decimal](16, 2) NOT NULL,
	[TaxAmount] [decimal](16, 2) NOT NULL,
	[LegalEntityNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[SequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerName] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[RemitToName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[AlternateBillingCurrencyISO] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsDiscountingProceeds] [bit] NOT NULL,
	[AssetPurchaseOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableTaxType] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[DealCountryId] [bigint] NULL,
	[OriginalInvoiceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PaymentScheduleId] [bigint] NULL,
	[PaymentType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsDownPaymentVATReceivable] [bit] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
