CREATE TYPE [dbo].[Job] AS TABLE(
	[Name] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[EffectiveDate] [datetimeoffset](7) NOT NULL,
	[ExpiryDate] [datetimeoffset](7) NULL,
	[ScheduleType] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[ScheduleDate] [datetimeoffset](7) NULL,
	[CronExpression] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[ScheduledStatus] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[ApprovalStatus] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[SubmittedCulture] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsNotify] [bit] NOT NULL,
	[RunOnHolidayOption] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[RunDateOptions] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[IsCritical] [bit] NOT NULL,
	[IsSystemJob] [bit] NOT NULL,
	[Privacy] [nvarchar](7) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerId] [bigint] NULL,
	[OccurenceType] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[CutoffTime] [datetimeoffset](7) NULL,
	[IsServiceCall] [bit] NOT NULL,
	[SubmittedUserId] [bigint] NOT NULL,
	[BusinessUnitId] [bigint] NOT NULL,
	[SourceSiteId] [bigint] NOT NULL,
	[JobServiceId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
