CREATE TYPE [dbo].[LateFeeTemplate] AS TABLE(
	[Name] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[LateFeeType] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[LateFeeBasis] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[BasisPercentage] [decimal](5, 2) NULL,
	[Compounding] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[DayCountConvention] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[AccountingTreatment] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[FloorAmount_Amount] [decimal](16, 2) NOT NULL,
	[FloorAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[CeilingAmount_Amount] [decimal](16, 2) NOT NULL,
	[CeilingAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsAssessedOnlyOnce] [bit] NOT NULL,
	[IsAssessedOnTax] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsFloatRate] [bit] NOT NULL,
	[FloatRateResetFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[FloatRateResetUnit] [int] NULL,
	[IsLeadUnitsinBusinessDays] [bit] NOT NULL,
	[LeadFrequency] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[LeadUnits] [int] NULL,
	[EffectiveDayofMonth] [int] NULL,
	[ReceivableCodeId] [bigint] NOT NULL,
	[CurrencyId] [bigint] NOT NULL,
	[FloatRateIndexId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
