CREATE TYPE [dbo].[LeaseAmendment] AS TABLE(
	[Name] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[LeaseAmendmentStatus] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[AmendmentType] [nvarchar](31) COLLATE Latin1_General_CI_AS NULL,
	[AmendmentDate] [date] NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[AmendmentAtInception] [bit] NOT NULL,
	[IsTDR] [bit] NOT NULL,
	[TDRReason] [nvarchar](24) COLLATE Latin1_General_CI_AS NULL,
	[PreRestructureLessorYield] [decimal](12, 6) NOT NULL,
	[PreRestructureClassificationYield] [decimal](12, 6) NOT NULL,
	[FinalAcceptanceDate] [date] NULL,
	[IsLienFilingRequired] [bit] NOT NULL,
	[IsLienFilingException] [bit] NOT NULL,
	[LienExceptionComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PreRestructureLeaseNBV_Amount] [decimal](16, 2) NOT NULL,
	[PreRestructureLeaseNBV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PostRestructureLeaseNBV_Amount] [decimal](16, 2) NOT NULL,
	[PostRestructureLeaseNBV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreRestructureResidualBooked_Amount] [decimal](16, 2) NOT NULL,
	[PreRestructureResidualBooked_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PostRestructureResidualBooked_Amount] [decimal](16, 2) NOT NULL,
	[PostRestructureResidualBooked_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreRestructureFAS91Balance_Amount] [decimal](16, 2) NOT NULL,
	[PreRestructureFAS91Balance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PostRestructureFAS91Balance_Amount] [decimal](16, 2) NOT NULL,
	[PostRestructureFAS91Balance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NetWritedowns_Amount] [decimal](16, 2) NOT NULL,
	[NetWritedowns_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AccountingDate] [date] NULL,
	[PostDate] [date] NULL,
	[ImpairmentAmount_Amount] [decimal](16, 2) NULL,
	[ImpairmentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsLeaseLevelImpairment] [bit] NOT NULL,
	[AccumulatedImpairmentAmount_Amount] [decimal](16, 2) NULL,
	[AccumulatedImpairmentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PreRestructureUnguaranteedResidual_Amount] [decimal](16, 2) NOT NULL,
	[PreRestructureUnguaranteedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PostRestructureUnguaranteedResidual_Amount] [decimal](16, 2) NOT NULL,
	[PostRestructureUnguaranteedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceComment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[SalesTaxRemittanceMethod] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[LienExceptionReason] [nvarchar](24) COLLATE Latin1_General_CI_AS NULL,
	[LeaseSequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LeaseAlias] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PaymentDate] [date] NULL,
	[TaxPaidtoVendor_Amount] [decimal](16, 2) NOT NULL,
	[TaxPaidtoVendor_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[GSTTaxPaidtoVendor_Amount] [decimal](16, 2) NOT NULL,
	[GSTTaxPaidtoVendor_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[HSTTaxPaidtoVendor_Amount] [decimal](16, 2) NOT NULL,
	[HSTTaxPaidtoVendor_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[QSTorPSTTaxPaidtoVendor_Amount] [decimal](16, 2) NOT NULL,
	[QSTorPSTTaxPaidtoVendor_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreRestructureLessorYieldLeaseAsset] [decimal](12, 6) NOT NULL,
	[PreRestructureLessorYieldFinanceAsset] [decimal](12, 6) NOT NULL,
	[PreRestructureClassificationYield5A] [decimal](12, 6) NOT NULL,
	[PreRestructureClassificationYield5B] [decimal](12, 6) NOT NULL,
	[FloatRateRestructure] [bit] NOT NULL,
	[AmendmentReasonComment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[CreateCPURestructure] [bit] NOT NULL,
	[CurrentLeaseFinanceId] [bigint] NULL,
	[LeasePaymentScheduleId] [bigint] NULL,
	[DealProductTypeId] [bigint] NULL,
	[DealTypeId] [bigint] NULL,
	[GLTemplateId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[PayOffGLTemplateId] [bigint] NULL,
	[OriginalLeaseFinanceId] [bigint] NULL,
	[OriginalDealProductTypeId] [bigint] NULL,
	[AmendmentReasonId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
