CREATE TYPE [dbo].[LeaseFinanceAdditionalCharge] AS TABLE(
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IsAssetBased] [bit] NULL,
	[SundryType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[GracePeriodinMonths] [int] NULL,
	[DueDate] [date] NULL,
	[IsRentalBased] [bit] NULL,
	[IsIncludeinAPR] [bit] NULL,
	[IsVatable] [bit] NULL,
	[ReceivableAmountInclVAT_Amount] [decimal](16, 2) NULL,
	[ReceivableAmountInclVAT_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PayableAmount_Amount] [decimal](16, 2) NULL,
	[PayableAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[AdditionalChargeId] [bigint] NOT NULL,
	[SundryId] [bigint] NULL,
	[RecurringSundryId] [bigint] NULL,
	[LeaseAssetId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[AdditionalChargeLeaseAssetId] [bigint] NULL,
	[LeaseFinanceId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
