CREATE TYPE [dbo].[LeaseFinance] AS TABLE(
	[BookingStatus] [nvarchar](16) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ApprovalStatus] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsCurrent] [bit] NOT NULL,
	[IsSalesTaxExempt] [bit] NOT NULL,
	[PropertyTaxResponsibility] [nvarchar](16) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsFederalIncomeTaxExempt] [bit] NOT NULL,
	[IsPaymentScheduleGenerated] [bit] NOT NULL,
	[PaymentScheduleParametersChanged] [bit] NOT NULL,
	[IsPricedPerformed] [bit] NOT NULL,
	[PricingParametersChanged] [bit] NOT NULL,
	[ManagementYieldParametersChanged] [bit] NOT NULL,
	[SendToGAIC] [bit] NOT NULL,
	[GAICStatus] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[GAICRejectionReason] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[HoldingStatus] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[HoldingStatusComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PurchaseOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionId] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[InterimRentAdjustmentEffectiveDate] [date] NULL,
	[InterimRentUpdateHasBeenRun] [bit] NOT NULL,
	[InterimInterestAdjustmentEffectiveDate] [date] NULL,
	[InterimInterestUpdateHasBeenRun] [bit] NOT NULL,
	[LeaseStipLossDetailDocument_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[LeaseStipLossDetailDocument_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[LeaseStipLossDetailDocument_Content] [varbinary](82) NULL,
	[ClassificationTestParametersChanged] [bit] NOT NULL,
	[IsAMReviewCompleted] [bit] NOT NULL,
	[IsAMReviewRequired] [bit] NOT NULL,
	[IsFundingApproved] [bit] NOT NULL,
	[IsAccountingApproved] [bit] NOT NULL,
	[FloatRateUpdateRunDate] [date] NULL,
	[BankQualified] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[IsHostedSolution] [bit] NOT NULL,
	[IsRetrievedFromSalesTaxParametersChanged] [bit] NOT NULL,
	[IsRePricingParametersChanged] [bit] NOT NULL,
	[IsRetrievedFromSalesTax] [bit] NOT NULL,
	[CustomerClass] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsRepricedForSalesTax] [bit] NOT NULL,
	[IsFutureFunding] [bit] NOT NULL,
	[IsSalesTaxReviewRequired] [bit] NOT NULL,
	[IsSalesTaxReviewCompleted] [bit] NOT NULL,
	[IsSalesLeaseBackReviewCompleted] [bit] NOT NULL,
	[IsSalesTaxExemption] [bit] NOT NULL,
	[IsConduit] [bit] NOT NULL,
	[IsRecoveryContract] [bit] NOT NULL,
	[IsTaxReserve] [bit] NOT NULL,
	[Is467Lease] [bit] NOT NULL,
	[TimbreNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsNewMasterAgreement] [bit] NOT NULL,
	[SFDCUniqueId] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsNotQuotable] [bit] NOT NULL,
	[IsBillInAlternateCurrency] [bit] NOT NULL,
	[RestructureOnFloatRateRunTillDate] [date] NULL,
	[VendorWithholdingTaxRate] [decimal](5, 2) NULL,
	[IsOTPDepreciationParameterChanged] [bit] NOT NULL,
	[PreparedBy] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsSubleasing] [bit] NOT NULL,
	[IsFinancialRiskInsurance] [bit] NOT NULL,
	[IsVat] [bit] NOT NULL,
	[IsLetterOfConsentForPledge] [bit] NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[CustomerId] [bigint] NOT NULL,
	[ContractId] [bigint] NOT NULL,
	[ContractOriginationId] [bigint] NOT NULL,
	[TaxProductTypeId] [bigint] NULL,
	[ThirdPartyResidualGuarantorId] [bigint] NULL,
	[ThirdPartyResidualGuarantorBillToId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[ReferralBankerId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[AgreementTypeDetailId] [bigint] NULL,
	[MasterAgreementId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[TaxExemptRuleId] [bigint] NOT NULL,
	[BranchId] [bigint] NULL,
	[VendorPayableCodeId] [bigint] NULL,
	[PayOffTemplateId] [bigint] NULL,
	[QuoteLeaseTypeId] [bigint] NOT NULL,
	[CreditAppId] [bigint] NULL,
	[InitialCostInvoiceJobId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
