CREATE TYPE [dbo].[LeaseContractOption] AS TABLE(
	[ContractOption] [nvarchar](16) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ContractOptionTerms] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[IsEarly] [bit] NOT NULL,
	[IsAnyDay] [bit] NOT NULL,
	[OptionDate] [date] NULL,
	[OptionMonth] [int] NULL,
	[PurchaseFactor] [decimal](8, 4) NULL,
	[RenewalFactor] [decimal](8, 4) NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Penalty] [decimal](5, 2) NULL,
	[IsPartialPermitted] [bit] NOT NULL,
	[IsExcluded] [bit] NOT NULL,
	[IsRenewalOfferApproved] [bit] NOT NULL,
	[LesseeNoticeDays] [int] NULL,
	[RestockingFee] [decimal](5, 2) NULL,
	[IsActive] [bit] NOT NULL,
	[IsOptionControlledByLessor] [bit] NOT NULL,
	[IsLesseeReasonablyCertainToExerciseOption] [bit] NOT NULL,
	[LeaseFinanceId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
