CREATE TYPE [dbo].[LegalEntity] AS TABLE(
	[Name] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Status] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[LegalEntityNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[GLSegmentValue] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[FiscalYearBeginMonthNo] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxFiscalYearBeginMonthNo] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[ActivationDate] [date] NULL,
	[DeactivationDate] [date] NULL,
	[IncorporationDate] [date] NULL,
	[TaxID_CT] [varbinary](48) NULL,
	[TaxPayer] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[OrganizationID] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyCode] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TaxRemittancePreference] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[GSTId] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[LessorWebAddress] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CostCenter] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[GLAccountNumber] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[NonUSDeferredTaxAccountNumber] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[LateFeeApproach] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[ThresholdDays] [int] NULL,
	[PSTQSTId] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[TaxAssessmentLevel] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[AccountingStandard] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceDueDateCalculation] [nvarchar](19) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsAssessSalesTaxAtSKULevel] [bit] NOT NULL,
	[SupportsVAT] [bit] NOT NULL,
	[ACHFailureLimit] [int] NULL,
	[BusinessUnitId] [bigint] NOT NULL,
	[ParentId] [bigint] NULL,
	[TaxDepBasisCurrencyId] [bigint] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[GLConfigurationId] [bigint] NOT NULL,
	[IncorporationStateId] [bigint] NOT NULL,
	[BusinessTypeId] [bigint] NOT NULL,
	[ReceiptHierarchyTemplateId] [bigint] NULL,
	[NonAccrualRuleTemplateId] [bigint] NULL,
	[ReAccrualRuleTemplateId] [bigint] NULL,
	[BusinessCalendarId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
