CREATE TYPE [dbo].[LeveragedLeaseAmendment] AS TABLE(
	[Name] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[RestructureDate] [date] NOT NULL,
	[AmortDocument_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[AmortDocument_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[AmortDocument_Content] [varbinary](82) NOT NULL,
	[PostDate] [date] NOT NULL,
	[LeveragedLeaseAmendmentStatus] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[MaturityDate] [date] NULL,
	[Term] [decimal](10, 6) NOT NULL,
	[EquipmentCost_Amount] [decimal](24, 2) NULL,
	[EquipmentCost_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ResidualValue_Amount] [decimal](24, 2) NULL,
	[ResidualValue_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[LongTermDebt_Amount] [decimal](24, 2) NULL,
	[LongTermDebt_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[EquityInvestment_Amount] [decimal](24, 2) NULL,
	[EquityInvestment_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IDC_Amount] [decimal](24, 2) NULL,
	[IDC_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[RentalsReceivable_Amount] [decimal](24, 2) NULL,
	[RentalsReceivable_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Debt_Amount] [decimal](24, 2) NULL,
	[Debt_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsFromStandalone] [bit] NOT NULL,
	[IsRestructureAtInception] [bit] NOT NULL,
	[CurrentLeveragedLeaseId] [bigint] NULL,
	[LeveragedLeaseRestructureReasonConfigId] [bigint] NOT NULL,
	[ContractId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
