CREATE TYPE [dbo].[LoanPaydown] AS TABLE(
	[QuoteNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[QuoteName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PaydownDate] [date] NULL,
	[PaydownReason] [nvarchar](30) COLLATE Latin1_General_CI_AS NOT NULL,
	[PaydownAmortOption] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[GoodThroughDate] [date] NULL,
	[AmortProcessThroughDate] [date] NULL,
	[ReceivableAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[Status] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[AccountingDate] [date] NULL,
	[PostDate] [date] NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceDate] [date] NULL,
	[DueDate] [date] NULL,
	[PrincipalPaydown_Amount] [decimal](16, 2) NULL,
	[PrincipalPaydown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[InterestPaydown_Amount] [decimal](16, 2) NULL,
	[InterestPaydown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NumberOfPayments] [int] NULL,
	[IsPaymentScheduleGenerated] [bit] NOT NULL,
	[IsPaymentModified] [bit] NOT NULL,
	[IsPaymentScheduleCleared] [bit] NOT NULL,
	[InvoiceFile_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceFile_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceFile_Content] [varbinary](82) NULL,
	[PrincipalOutstanding_Amount] [decimal](16, 2) NULL,
	[PrincipalOutstanding_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[InterestOutstanding_Amount] [decimal](16, 2) NULL,
	[InterestOutstanding_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PrincipalBalance_Amount] [decimal](16, 2) NULL,
	[PrincipalBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[AccruedInterest_Amount] [decimal](16, 2) NULL,
	[AccruedInterest_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[RecoveryAtPaydown_Amount] [decimal](16, 2) NOT NULL,
	[RecoveryAtPaydown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[WritedownAtPaydown_Amount] [decimal](16, 2) NOT NULL,
	[WritedownAtPaydown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[UnrecoveredWritedownAtPaydown_Amount] [decimal](16, 2) NOT NULL,
	[UnrecoveredWritedownAtPaydown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NetWritedown_Amount] [decimal](16, 2) NOT NULL,
	[NetWritedown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsPaydownFromLoan] [bit] NOT NULL,
	[Settlement] [bit] NOT NULL,
	[Report1099C] [bit] NOT NULL,
	[PaydownAtInception] [bit] NOT NULL,
	[PrepaymentPenalty_Amount] [decimal](16, 2) NULL,
	[PrepaymentPenalty_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[InterestRate] [decimal](10, 6) NOT NULL,
	[GainLoss_Amount] [decimal](16, 2) NOT NULL,
	[GainLoss_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PaydownRequestPhoneNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[PaydownRequestEMail] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[IsSystemGenerated] [bit] NOT NULL,
	[DailyFinanceAsOfDate] [date] NULL,
	[SuggestedPaydownAmount_Amount] [decimal](16, 2) NOT NULL,
	[SuggestedPaydownAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsPaydownTemplateParametersChanged] [bit] NOT NULL,
	[IsPaydownPricingOptionsPopulated] [bit] NOT NULL,
	[ExcessPaydownAmount] [decimal](16, 2) NOT NULL,
	[CloseRevolvingLoan] [bit] NOT NULL,
	[InvoicePreference] [nvarchar](18) COLLATE Latin1_General_CI_AS NOT NULL,
	[IncludeOutstandingCharges] [bit] NOT NULL,
	[LoanFinanceId] [bigint] NOT NULL,
	[LoanPaymentId] [bigint] NULL,
	[LoanAmendmentId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[PaydownGLTemplateId] [bigint] NULL,
	[PrincipalPaydownReceivableCodeId] [bigint] NULL,
	[InterestPaydownReceivableCodeId] [bigint] NULL,
	[WritedownGLTemplateId] [bigint] NULL,
	[RecoveryGLTemplateId] [bigint] NULL,
	[RecoveryReceivableCodeId] [bigint] NULL,
	[CasualtyReceivableCodeId] [bigint] NULL,
	[InvoiceId] [bigint] NULL,
	[ReceiptId] [bigint] NULL,
	[PrepaymentPenaltyReceivableCodeId] [bigint] NULL,
	[SundryReceivableCodeId] [bigint] NULL,
	[AssetHoldingStatusChangeId] [bigint] NULL,
	[DisbursementId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[PaydownTemplateId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
