CREATE TYPE [dbo].[LoanPaydownSecurityDeposit] AS TABLE(
	[AmountAppliedToPayDown_Amount] [decimal](16, 2) NOT NULL,
	[AmountAppliedToPayDown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TransferToIncome_Amount] [decimal](16, 2) NOT NULL,
	[TransferToIncome_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TransferToReceipt_Amount] [decimal](16, 2) NOT NULL,
	[TransferToReceipt_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsRefund] [bit] NOT NULL,
	[PayableDate] [date] NULL,
	[AvailableAmount_Amount] [decimal](16, 2) NOT NULL,
	[AvailableAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[WithholdingTaxRate] [decimal](5, 2) NULL,
	[SecurityDepositId] [bigint] NOT NULL,
	[PartyId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[SecurityDepositAllocationId] [bigint] NOT NULL,
	[SecurityDepositApplicationId] [bigint] NULL,
	[LoanPaydownId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
