CREATE TYPE [dbo].[LoanIncomeSchedulesForManipulation] AS TABLE(
	[Id] [bigint] NULL,
	[IncomeDate] [date] NULL,
	[Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Payment] [decimal](16, 2) NULL,
	[BeginNetBookValue] [decimal](16, 2) NULL,
	[EndNetBookValue] [decimal](16, 2) NULL,
	[PrincipalRepayment] [decimal](16, 2) NULL,
	[PrincipalAdded] [decimal](16, 2) NULL,
	[InterestPayment] [decimal](16, 2) NULL,
	[InterestAccrued] [decimal](16, 2) NULL,
	[InterestAccrualBalance] [decimal](16, 2) NULL,
	[CapitalizedInterest] [decimal](16, 2) NULL,
	[CumulativeInterestBalance] [decimal](16, 2) NULL,
	[CompoundDate] [date] NULL,
	[IsSchedule] [bit] NULL,
	[IsAccounting] [bit] NULL,
	[IsSyndicated] [bit] NULL,
	[IsGLPosted] [bit] NULL,
	[IsNonAccrual] [bit] NULL,
	[DisbursementId] [bigint] NULL,
	[FloatRateIndexDetailId] [bigint] NULL,
	[IsLessorOwned] [bit] NULL,
	[CumulativeInterestAppliedToPrincipal] [decimal](16, 2) NULL,
	[AdjustmentEntry] [bit] NULL,
	[InterestRate] [decimal](10, 8) NULL,
	[TV5InterestAccrualBalance] [decimal](16, 2) NULL,
	[LoanFinanceId] [bigint] NULL,
	[IsNew] [bit] NULL,
	[UnroundedInterestAccrued] [decimal](18, 8) NULL
)
GO
