CREATE TYPE [dbo].[LoanBlendedItemSundryTypeForLoan] AS TABLE(
	[BlendedItemId] [bigint] NULL,
	[Identifier] [bigint] NULL,
	[SundryType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[EntityType] [nvarchar](2) COLLATE Latin1_General_CI_AS NULL,
	[DueDate] [date] NULL,
	[InvoiceComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[Memo] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsAssetBased] [bit] NULL,
	[Amount] [decimal](16, 2) NULL,
	[IsTaxExempt] [bit] NULL,
	[IsServiced] [bit] NULL,
	[IsCollected] [bit] NULL,
	[IsPrivateLabel] [bit] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[ReceivableRemitToId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[IsOwned] [bit] NULL,
	[IsAssignAtAssetLevel] [bit] NULL,
	[IsSystemGenerated] [bit] NULL,
	[InvoiceAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[Type] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[PayableEntityType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[PayableStatus] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[PayableSourceTable] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableSourceTable] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceReceivableGroupingOption] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableBilledStatus] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsReceivableTaxAssessed] [bit] NULL,
	[TreasuryPayableStatus] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptType] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[CostCenterId] [bigint] NULL,
	[AlternateBillingCurrencyId] [bigint] NULL,
	[ExchangeRate] [decimal](20, 10) NULL,
	[ContractSequenceNumber] [nvarchar](80) COLLATE Latin1_General_CI_AS NULL,
	[Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyId] [bigint] NULL,
	[PayableWithholdingTaxRate] [decimal](5, 2) NULL
)
GO
