CREATE TYPE [dbo].[LoanIncomesToCreate] AS TABLE(
	[IncomeDate] [date] NOT NULL,
	[PaymentAmount] [decimal](16, 2) NOT NULL,
	[BeginNetBookValueAmount] [decimal](16, 2) NOT NULL,
	[EndNetBookValueAmount] [decimal](16, 2) NOT NULL,
	[PrincipalRepaymentAmount] [decimal](16, 2) NOT NULL,
	[PrincipalAddedAmount] [decimal](16, 2) NOT NULL,
	[InterestPaymentAmount] [decimal](16, 2) NOT NULL,
	[UnroundedInterestAccrued] [decimal](18, 8) NOT NULL,
	[InterestAccruedAmount] [decimal](16, 2) NOT NULL,
	[InterestAccrualBalanceAmount] [decimal](16, 2) NOT NULL,
	[CapitalizedInterestAmount] [decimal](16, 2) NOT NULL,
	[CumulativeInterestBalanceAmount] [decimal](16, 2) NOT NULL,
	[CompoundDate] [date] NULL,
	[IsSchedule] [bit] NOT NULL,
	[IsAccounting] [bit] NOT NULL,
	[IsSyndicated] [bit] NOT NULL,
	[IsGLPosted] [bit] NOT NULL,
	[IsNonAccrual] [bit] NOT NULL,
	[IsLessorOwned] [bit] NOT NULL,
	[CumulativeInterestAppliedToPrincipalAmount] [decimal](16, 2) NOT NULL,
	[AdjustmentEntry] [bit] NOT NULL,
	[InterestRate] [decimal](10, 8) NOT NULL,
	[TV5InterestAccrualBalanceAmount] [decimal](16, 2) NOT NULL,
	[DisbursementId] [bigint] NULL,
	[FloatRateIndexDetailId] [bigint] NULL,
	[LoanFinanceId] [bigint] NOT NULL,
	[UniqueId] [bigint] NOT NULL,
	[MakeGLEntry] [bit] NOT NULL,
	[NonAccrualPostDate] [date] NULL
)
GO
