CREATE TYPE [dbo].[LoanPaydownSundry] AS TABLE(
	[SundryType] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IncludeInPaydownInvoice] [bit] NOT NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[DueDate] [date] NOT NULL,
	[IsSystemGenerated] [bit] NOT NULL,
	[IsPenalty] [bit] NOT NULL,
	[IsForSuggestedPaydownAmount] [bit] NOT NULL,
	[PayableWithholdingTaxRate] [decimal](5, 2) NULL,
	[LocationId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[RemitToId] [bigint] NOT NULL,
	[BillToId] [bigint] NULL,
	[SundryPayableCodeId] [bigint] NULL,
	[SundryReceivableCodeId] [bigint] NULL,
	[SundryId] [bigint] NULL,
	[LoanPaydownId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
