CREATE TYPE [dbo].[Location] AS TABLE(
	[Code] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Name] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Division] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[City] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PostalCode] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[TaxAreaVerifiedTillDate] [date] NULL,
	[IsActive] [bit] NOT NULL,
	[TaxAreaId] [bigint] NULL,
	[ApprovalStatus] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[IncludedPostalCodeInLocationLookup] [bit] NOT NULL,
	[TaxBasisType] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[UpfrontTaxMode] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[CountryTaxExemptionRate] [decimal](10, 6) NULL,
	[StateTaxExemptionRate] [decimal](10, 6) NULL,
	[DivisionTaxExemptionRate] [decimal](10, 6) NULL,
	[CityTaxExemptionRate] [decimal](10, 6) NULL,
	[AddressLine3] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Neighborhood] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[SubdivisionOrMunicipality] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Longitude] [decimal](11, 8) NULL,
	[Latitude] [decimal](11, 8) NULL,
	[CustomerId] [bigint] NULL,
	[StateId] [bigint] NOT NULL,
	[JurisdictionId] [bigint] NULL,
	[JurisdictionDetailId] [bigint] NULL,
	[ContactPersonId] [bigint] NULL,
	[TaxExemptRuleId] [bigint] NOT NULL,
	[PortfolioId] [bigint] NOT NULL,
	[VendorId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
