CREATE TYPE [dbo].[NonAccrualContract] AS TABLE(
	[NonAccrualDate] [date] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IsActive] [bit] NOT NULL,
	[NBV_Amount] [decimal](16, 2) NOT NULL,
	[NBV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NBVWithBlended_Amount] [decimal](16, 2) NOT NULL,
	[NBVWithBlended_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TotalOutstandingAR_Amount] [decimal](16, 2) NOT NULL,
	[TotalOutstandingAR_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AccountingDate] [date] NULL,
	[LastReceiptDate] [date] NULL,
	[IncomeRecognizedAfterNonAccrual_Amount] [decimal](16, 2) NOT NULL,
	[IncomeRecognizedAfterNonAccrual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BillingSuppressed] [bit] NOT NULL,
	[DeferredRentalIncomeReclass_Amount] [decimal](16, 2) NOT NULL,
	[DeferredRentalIncomeReclass_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LastIncomeUpdateDate] [date] NULL,
	[DoubtfulCollectability] [bit] NOT NULL,
	[IsNonAccrualApproved] [bit] NOT NULL,
	[PostDate] [date] NULL,
	[ContractId] [bigint] NOT NULL,
	[NonAccrualId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
