CREATE TYPE [dbo].[OneSourceExportDetailExtract] AS TABLE(
	[AssetNumber] [bigint] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[LeaseNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PreviousLeaseNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ItemType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetDescription] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[AcquisitionDate] [date] NULL,
	[AssetCost] [decimal](16, 2) NULL,
	[AssetAddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AssetAddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AssetAddressLine3] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AssetCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetCountyName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[AssetZipCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EquipmentCode] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SalesTaxRate] [decimal](16, 2) NULL,
	[LeaseType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[AssetSerialNumber] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Quantity] [int] NOT NULL,
	[FederalTaxDep] [decimal](16, 2) NULL,
	[Manufacturer] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ModelYear] [decimal](4, 0) NULL,
	[AgreementCustomerName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[CustomerAddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[CustomerAddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[CustomerAddressLine3] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[CustomerCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerState] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CustomerZipCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TaxExempt] [bit] NULL,
	[LegalEntityId] [bigint] NULL,
	[IsIncluded] [bit] NOT NULL,
	[FileName] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[AsOfDate] [date] NULL,
	[RejectReason] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[JobStepInstanceId] [bigint] NOT NULL,
	[IsDisposedAssetReported] [bit] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
