CREATE TYPE [dbo].[OneTimeACH] AS TABLE(
	[SettlementDate] [date] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[AppliedAmount_Amount] [decimal](16, 2) NOT NULL,
	[AppliedAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ACHAmount_Amount] [decimal](16, 2) NOT NULL,
	[ACHAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[UnAllocatedAmount_Amount] [decimal](16, 2) NOT NULL,
	[UnAllocatedAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsCreateBankAccount] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[Status] [nvarchar](18) COLLATE Latin1_General_CI_AS NOT NULL,
	[AmountDistributionType] [nvarchar](13) COLLATE Latin1_General_CI_AS NOT NULL,
	[CheckNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ApplyByReceivable] [bit] NOT NULL,
	[FileGenerationDate] [date] NULL,
	[IsAutoAllocate] [bit] NOT NULL,
	[BankAccountId] [bigint] NOT NULL,
	[LineofBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[CustomerId] [bigint] NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[LegalEntityBankAccountId] [bigint] NOT NULL,
	[CurrencyId] [bigint] NOT NULL,
	[CashTypeId] [bigint] NULL,
	[ReceiptGLTemplateId] [bigint] NOT NULL,
	[CostCenterId] [bigint] NULL,
	[OneTimeACHRequestId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
