CREATE TYPE [dbo].[OrganizationConfig] AS TABLE(
	[Name] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[FavIcon_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[FavIcon_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[FavIcon_Content] [varbinary](82) NOT NULL,
	[BrowserTitle] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[LoginBackground_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[LoginBackground_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[LoginBackground_Content] [varbinary](82) NOT NULL,
	[LoginLogo_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[LoginLogo_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[LoginLogo_Content] [varbinary](82) NOT NULL,
	[LoginTitle] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[TermsAndConditions] [nvarchar](max) COLLATE Latin1_General_CI_AS NOT NULL,
	[EmailContact] [nvarchar](70) COLLATE Latin1_General_CI_AS NOT NULL,
	[ContactMessage] [nvarchar](max) COLLATE Latin1_General_CI_AS NOT NULL,
	[MenuLogo_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[MenuLogo_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[MenuLogo_Content] [varbinary](82) NOT NULL,
	[FooterLogo_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[FooterLogo_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[FooterLogo_Content] [varbinary](82) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
