CREATE TYPE [dbo].[Party] AS TABLE(
	[PartyNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IsCorporate] [bit] NOT NULL,
	[FirstName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MiddleName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LastName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Suffix] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CompanyName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[PartyName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[Alias] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[UniqueIdentificationNumber_CT] [varbinary](48) NULL,
	[LastFourDigitUniqueIdentificationNumber] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[DateOfBirth] [date] NULL,
	[DoingBusinessAs] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[CreationDate] [date] NOT NULL,
	[IncorporationDate] [date] NULL,
	[CurrentRole] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[IsSoleProprietor] [bit] NOT NULL,
	[PartyEntityType] [nvarchar](39) COLLATE Latin1_General_CI_AS NULL,
	[IsIntercompany] [bit] NOT NULL,
	[VATRegistrationNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ExternalPartyNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsVATRegistration] [bit] NULL,
	[EIKNumber_CT] [varbinary](64) NULL,
	[WayOfRepresentation] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Representative1] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Representative2] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Representative3] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[VATRegistration] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[NationalIdCardNumber_CT] [varbinary](64) NULL,
	[DateofIssueID] [date] NULL,
	[IssuedIn] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Gender] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[IsForeigner] [bit] NULL,
	[Ln4] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[PassportNo] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[DateofIssue] [date] NULL,
	[PassportCountry] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[PassportAddress] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsSpecialClient] [bit] NOT NULL,
	[EquityOwnerEGN1] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[EquityOwnerEGN2] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[EquityOwnerEGN3] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Email] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[ParentPartyId] [bigint] NULL,
	[StateOfIncorporationId] [bigint] NULL,
	[LanguageId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[CustomerLegalStatusId] [bigint] NULL,
	[SectorId] [bigint] NULL,
	[ProfessionsId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
