CREATE TYPE [dbo].[PartyDAMVReportDetail] AS TABLE(
	[FirstName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[LastName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DateOfBirth] [date] NULL,
	[IdentityDocumentNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IssueDate] [date] NULL,
	[IssuerPlace] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IssuerPlaceLatin] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IssuerName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IssuerNameLatin] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ValidDate] [date] NULL,
	[MiddleName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DocumentType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DocumentTypeLatin] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BirthPlaceCountryCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BirthPlaceCountryName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BirthPlaceCountryNameLatin] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BirthPlaceTerritorialUnitName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BirthPlaceDistrictName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BirthPlaceMunicipalityName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DAIntegrationResponseId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
