CREATE TYPE [dbo].[PartyContact] AS TABLE(
	[UniqueIdentifier] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Prefix] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[FirstName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[MiddleName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LastName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[FullName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[PhoneNumber1] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ExtensionNumber1] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[PhoneNumber2] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ExtensionNumber2] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[MobilePhoneNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[FaxNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[EMailId] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[Description] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[SocialSecurityNumber_CT] [varbinary](48) NULL,
	[LastFourDigitSocialSecurityNumber] [nvarchar](4) COLLATE Latin1_General_CI_AS NULL,
	[DateOfBirth] [date] NULL,
	[OwnershipPercentage] [decimal](5, 2) NULL,
	[CIPDocumentSourceForName] [nvarchar](61) COLLATE Latin1_General_CI_AS NULL,
	[CIPDocumentSourceForAddress] [nvarchar](61) COLLATE Latin1_General_CI_AS NULL,
	[CIPDocumentSourceForTaxIdOrSSN] [nvarchar](61) COLLATE Latin1_General_CI_AS NULL,
	[MortgageHighCredit_Amount] [decimal](16, 2) NULL,
	[MortgageHighCredit_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsSCRA] [bit] NOT NULL,
	[SCRAStartDate] [date] NULL,
	[SCRAEndDate] [date] NULL,
	[BenefitsAndProtection] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[IsFromAssumption] [bit] NOT NULL,
	[IsAssumptionApproved] [bit] NOT NULL,
	[ParalegalName] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[SecretaryName] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[Webpage] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[LastName2] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SFDCContactId] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[IsBookingNotificationAllowed] [bit] NOT NULL,
	[IsCreditNotificationAllowed] [bit] NOT NULL,
	[BusinessStartTimeInHours] [int] NOT NULL,
	[BusinessEndTimeInHours] [int] NOT NULL,
	[BusinessStartTimeInMinutes] [int] NOT NULL,
	[BusinessEndTimeInMinutes] [int] NOT NULL,
	[EGNNumber_CT] [varbinary](64) NULL,
	[DrivingLicense] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IssuedOn] [date] NULL,
	[IssuedIn] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Validity] [date] NULL,
	[Foreigner] [bit] NOT NULL,
	[IDCardNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IDCardIssuedOn] [date] NULL,
	[IDCardIssuedIn] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Gender] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[LN4] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PassportNo] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PassportIssuedOn] [date] NULL,
	[PassportCountry] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PassportAddress] [nvarchar](2000) COLLATE Latin1_General_CI_AS NULL,
	[EMail2] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[PowerOfAttorneyNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PowerOfAttorneyValidity] [date] NULL,
	[Notary] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistarationNoOfNotary] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[NationalIdCardNumber_CT] [varbinary](64) NULL,
	[MailingAddressId] [bigint] NULL,
	[ParentPartyContactId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[CIPDocumentSourceNameId] [bigint] NULL,
	[TimeZoneId] [bigint] NULL,
	[PartyId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
