CREATE TYPE [dbo].[Payable] AS TABLE(
	[EntityType] [nvarchar](4) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[EntityId] [bigint] NOT NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Balance_Amount] [decimal](16, 2) NOT NULL,
	[Balance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxPortion_Amount] [decimal](16, 2) NOT NULL,
	[TaxPortion_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[DueDate] [date] NOT NULL,
	[Status] [nvarchar](17) COLLATE Latin1_General_CI_AS NOT NULL,
	[SourceTable] [nvarchar](24) COLLATE Latin1_General_CI_AS NOT NULL,
	[SourceId] [bigint] NOT NULL,
	[InternalComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsGLPosted] [bit] NOT NULL,
	[CreationSourceTable] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[CreationSourceId] [bigint] NULL,
	[WithholdingTaxRate] [decimal](5, 2) NULL,
	[CurrencyId] [bigint] NOT NULL,
	[PayableCodeId] [bigint] NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[PayeeId] [bigint] NOT NULL,
	[RemitToId] [bigint] NULL,
	[AdjustmentBasisPayableId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
