CREATE TYPE [dbo].[PaymentVoucher] AS TABLE(
	[VoucherNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[PaymentDate] [date] NOT NULL,
	[PostDate] [date] NOT NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AmountInContractCurrency_Amount] [decimal](16, 2) NOT NULL,
	[AmountInContractCurrency_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Status] [nvarchar](10) COLLATE Latin1_General_CI_AS NOT NULL,
	[CheckNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CheckDate] [date] NULL,
	[FederalReferenceNumber] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[WireDate] [date] NULL,
	[Memo] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[Urgency] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptType] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[OverNightRequired] [bit] NOT NULL,
	[OFACReviewRequired] [bit] NOT NULL,
	[IsManual] [bit] NOT NULL,
	[OriginalVoucherId] [bigint] NULL,
	[BatchId] [bigint] NULL,
	[IsIntercompany] [bit] NOT NULL,
	[MailingInstruction] [nvarchar](2) COLLATE Latin1_General_CI_AS NULL,
	[WithholdingTaxAmount_Amount] [decimal](16, 2) NOT NULL,
	[WithholdingTaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AssessmentDate] [date] NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[RemitToId] [bigint] NOT NULL,
	[ReceiptId] [bigint] NULL,
	[PayFromAccountId] [bigint] NULL,
	[PaymentVoucherInfoId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
