CREATE TYPE [dbo].[PayoffBlendedItem] AS TABLE(
	[Earned_Amount] [decimal](16, 2) NOT NULL,
	[Earned_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Unearned_Amount] [decimal](16, 2) NOT NULL,
	[Unearned_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayoffAdjustment_Amount] [decimal](16, 2) NOT NULL,
	[PayoffAdjustment_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AccumulatedAdjustment_Amount] [decimal](16, 2) NOT NULL,
	[AccumulatedAdjustment_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BilledAmount_Amount] [decimal](16, 2) NOT NULL,
	[BilledAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[UnbilledAmount_Amount] [decimal](16, 2) NOT NULL,
	[UnbilledAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsActive] [bit] NOT NULL,
	[InactivatedInLease] [bit] NOT NULL,
	[OriginalEndDate] [date] NULL,
	[BlendedItemId] [bigint] NOT NULL,
	[GLJournalId] [bigint] NULL,
	[PayoffId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
