CREATE TYPE [dbo].[Payoff] AS TABLE(
	[QuoteNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[QuoteName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[FullPayoff] [bit] NOT NULL,
	[PayoffAtInception] [bit] NOT NULL,
	[Status] [nvarchar](25) COLLATE Latin1_General_CI_AS NOT NULL,
	[GoodThroughDate] [date] NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PayoffEffectiveDate] [date] NULL,
	[Settlement] [bit] NOT NULL,
	[Report1099C] [bit] NOT NULL,
	[ApplyAtAssetLevel] [bit] NOT NULL,
	[PayoffDiscountRate] [decimal](8, 4) NULL,
	[SuggestedPayoffAmount_Amount] [decimal](16, 2) NOT NULL,
	[SuggestedPayoffAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayoffAmount_Amount] [decimal](16, 2) NOT NULL,
	[PayoffAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayoffWeightageAttribute] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[BuyoutDiscountRate] [decimal](8, 4) NULL,
	[BuyoutWeightageAttribute] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[SuggestedBuyoutAmount_Amount] [decimal](16, 2) NOT NULL,
	[SuggestedBuyoutAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BuyoutAmount_Amount] [decimal](16, 2) NOT NULL,
	[BuyoutAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayoffAssetStatus] [nvarchar](21) COLLATE Latin1_General_CI_AS NULL,
	[PayoffAssetSubStatus] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[AssetValuation_Amount] [decimal](16, 2) NOT NULL,
	[AssetValuation_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[OLV_Amount] [decimal](16, 2) NOT NULL,
	[OLV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AssetValuationWeightageAttribute] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[OLVWeightageAttribute] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[DueDate] [date] NULL,
	[StopInvoicingFutureRentals] [bit] NOT NULL,
	[IncludeOutstandingCharges] [bit] NOT NULL,
	[PayoffInvoicePreference] [nvarchar](18) COLLATE Latin1_General_CI_AS NULL,
	[BuyoutInvoicePreference] [nvarchar](18) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[EstimatedPropertyTaxAmount_Amount] [decimal](16, 2) NOT NULL,
	[EstimatedPropertyTaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[EstimatedPropertyTaxVATAmount_Amount] [decimal](16, 2) NOT NULL,
	[EstimatedPropertyTaxVATAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayoffInvoiceComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PostDate] [date] NULL,
	[ReversalPostDate] [date] NULL,
	[AccountingDate] [date] NULL,
	[OriginalChargeoffAmount_Amount] [decimal](16, 2) NOT NULL,
	[OriginalChargeoffAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ChargeoffBalance_Amount] [decimal](16, 2) NOT NULL,
	[ChargeoffBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsSystemGenerated] [bit] NOT NULL,
	[SummaryComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsParametersChanged] [bit] NOT NULL,
	[IsPaymentScheduleGenerated] [bit] NOT NULL,
	[PrePayoffPricingInterestRate] [decimal](12, 6) NULL,
	[PostPayoffPricingInterestRate] [decimal](12, 6) NULL,
	[AssetFinancialValuesComputed] [bit] NOT NULL,
	[IsAssetFinancialValueParametersChanged] [bit] NOT NULL,
	[BlendedFinancialValuesComputed] [bit] NOT NULL,
	[NetInvestmentWithBlended_Amount] [decimal](16, 2) NOT NULL,
	[NetInvestmentWithBlended_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[GrossWriteDown_Amount] [decimal](16, 2) NOT NULL,
	[GrossWriteDown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NetWriteDown_Amount] [decimal](16, 2) NOT NULL,
	[NetWriteDown_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsPaidOffInInstallPhase] [bit] NOT NULL,
	[AddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[City] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Zip] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[FullName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[PhoneNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[MobilePhoneNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[EMail] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[PickupDate] [date] NULL,
	[PayoffRequestPhoneNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[PayoffRequestEMail] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[ApplySecurityDeposit] [bit] NOT NULL,
	[FMV_Amount] [decimal](16, 2) NOT NULL,
	[FMV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[OTPRent_Amount] [decimal](16, 2) NOT NULL,
	[OTPRent_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[QuoteType] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[MultiplePricingOption] [bit] NOT NULL,
	[IsPayoffTemplateParametersChanged] [bit] NOT NULL,
	[DailyFinanceAsOfDate] [date] NULL,
	[IsPayoffPricingOptionsPopulated] [bit] NOT NULL,
	[TradeupFeeAmount] [decimal](16, 2) NOT NULL,
	[TradeupFeeVATAmount_Amount] [decimal](16, 2) NOT NULL,
	[TradeupFeeVATAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsCreatedFromVendorPortal] [bit] NOT NULL,
	[IsCreatedFromCustomerPortal] [bit] NOT NULL,
	[ExternalReferenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PurchaseOption] [nvarchar](32) COLLATE Latin1_General_CI_AS NULL,
	[TotalEconomicLifeInMonths] [int] NOT NULL,
	[RemainingEconomicLifeInMonths] [int] NOT NULL,
	[IsBargainPurchaseOption] [bit] NOT NULL,
	[IsTransferOfOwnership] [bit] NOT NULL,
	[IsSpecializedUseAssets] [bit] NOT NULL,
	[TotalEconomicLifeTestResult] [decimal](10, 6) NOT NULL,
	[NinetyPercentTestPresentValue_Amount] [decimal](16, 2) NOT NULL,
	[NinetyPercentTestPresentValue_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NinetyPercentTestResult] [decimal](10, 6) NOT NULL,
	[NinetyPercentTestResultPassed] [bit] NOT NULL,
	[NinetyPercentTestPresentValue5A_Amount] [decimal](16, 2) NOT NULL,
	[NinetyPercentTestPresentValue5A_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NinetyPercentTestPresentValue5B_Amount] [decimal](16, 2) NOT NULL,
	[NinetyPercentTestPresentValue5B_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NinetyPercent5ATestResultPassed] [bit] NOT NULL,
	[NinetyPercent5BTestResultPassed] [bit] NOT NULL,
	[NinetyPercent5ATestResult] [decimal](10, 6) NOT NULL,
	[NinetyPercent5BTestResult] [decimal](10, 6) NOT NULL,
	[ClassificationContractType] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[IsClassificationTestDone] [bit] NOT NULL,
	[ClassificationTestParametersChanged] [bit] NOT NULL,
	[LessorYield] [decimal](28, 18) NOT NULL,
	[LessorYieldLeaseAsset] [decimal](28, 18) NOT NULL,
	[LessorYieldFinanceAsset] [decimal](28, 18) NOT NULL,
	[ClassificationYield] [decimal](28, 18) NOT NULL,
	[ClassificationYield5A] [decimal](28, 18) NOT NULL,
	[ClassificationYield5B] [decimal](28, 18) NOT NULL,
	[IsYieldComputed] [bit] NOT NULL,
	[YieldCalculationParametersChanged] [bit] NOT NULL,
	[IsLessorYieldLeaseAssetExtreme] [bit] NOT NULL,
	[IsLessorYieldFinanceAssetExtreme] [bit] NOT NULL,
	[IsLessorYieldExtreme] [bit] NOT NULL,
	[IsClassificationYieldExtreme] [bit] NOT NULL,
	[IsClassificationYield5AExtreme] [bit] NOT NULL,
	[IsClassificationYield5BExtreme] [bit] NOT NULL,
	[IsAssetBasedEstimatedPropertyTax] [bit] NOT NULL,
	[PayoffVATAmount_Amount] [decimal](16, 2) NOT NULL,
	[PayoffVATAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BuyoutVATAmount_Amount] [decimal](16, 2) NOT NULL,
	[BuyoutVATAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsVATAssessed] [bit] NOT NULL,
	[IsGLConsolidated] [bit] NOT NULL,
	[LeaseFinanceId] [bigint] NOT NULL,
	[LeasePaymentScheduleId] [bigint] NULL,
	[BillToCustomerId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[PayoffReceivableCodeId] [bigint] NULL,
	[BuyoutReceivableCodeId] [bigint] NULL,
	[PropertyTaxEscrowReceivableCodeId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[PayoffGLTemplateId] [bigint] NULL,
	[AssetBookValueAdjustmentGLTemplateId] [bigint] NULL,
	[NBVImpairmentGLTemplateId] [bigint] NULL,
	[WritedownReceivableCodeId] [bigint] NULL,
	[WritedownGLTemplateId] [bigint] NULL,
	[TerminationOptionId] [bigint] NULL,
	[InventoryBookDepGLTemplateId] [bigint] NULL,
	[GLJournalId] [bigint] NULL,
	[ReversalGLJournalId] [bigint] NULL,
	[ShipFromId] [bigint] NULL,
	[FrieghtBillToId] [bigint] NULL,
	[StateId] [bigint] NULL,
	[TaxDepDisposalTemplateId] [bigint] NULL,
	[AssetHoldingStatusChangeId] [bigint] NULL,
	[ReceiptHierarchyTemplateId] [bigint] NULL,
	[PayOffTemplateId] [bigint] NULL,
	[PayOffTemplateTerminationTypeId] [bigint] NULL,
	[TradeUpFeeReceivableCodeId] [bigint] NULL,
	[AutoPayoffTemplateId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
