CREATE TYPE [dbo].[Plate] AS TABLE(
	[PlateUniqueNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IssuedDate] [date] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[ActivationDate] [date] NULL,
	[AssignmentDate] [date] NULL,
	[PlateNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[ResponsibleEntity] [nvarchar](6) COLLATE Latin1_General_CI_AS NULL,
	[DoNotRenewRegistration] [bit] NOT NULL,
	[ExpiryDate] [date] NOT NULL,
	[DeactivationDate] [date] NULL,
	[DeactivationReason] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[RegistrationAddressType] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[RegistrationName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistantAttentionTo] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistrantAddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[RegistrantAddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[RegistrantAddressLine3] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[RegistrantCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistrantDivision] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistrantPostalCode] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[RegistrantNeighborhood] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistrantSubdivisionOrMunicipality] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DMVAddressType] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[DMVAttentionTo] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DMVAddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[DMVAddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[DMVAddressLine3] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[DMVCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DMVDivision] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DMVPostalCode] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[DMVNeighborhood] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DMVSubdivisionOrMunicipality] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistrationCountryId] [bigint] NOT NULL,
	[RegistrantCountryId] [bigint] NULL,
	[DMVCountryId] [bigint] NULL,
	[RegistrationStateId] [bigint] NOT NULL,
	[RegistantStateId] [bigint] NULL,
	[DMVStateId] [bigint] NULL,
	[AssetId] [bigint] NULL,
	[PlateTypeId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
