CREATE TYPE [dbo].[PPTEscrowAssessment] AS TABLE(
	[DisposistionAmount_Amount] [decimal](16, 2) NULL,
	[DisposistionAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[PostDate] [date] NULL,
	[EscrowDisposistion] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[Status] [nvarchar](19) COLLATE Latin1_General_CI_AS NOT NULL,
	[TotalEscrowAmount_Amount] [decimal](16, 2) NULL,
	[TotalEscrowAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[EscrowProcessAmount_Amount] [decimal](16, 2) NULL,
	[EscrowProcessAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableDueDate] [date] NULL,
	[PayableDueDate] [date] NULL,
	[PayableWithholdingTaxRate] [decimal](5, 2) NULL,
	[ContractId] [bigint] NOT NULL,
	[ReceivableCodeId] [bigint] NULL,
	[ReceivableRemitToId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[ReceiptNonCashGLTemplateId] [bigint] NULL,
	[ReceiptId] [bigint] NULL,
	[SundryId] [bigint] NULL,
	[GlJournalId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
