CREATE TYPE [dbo].[PreQuoteRenewal] AS TABLE(
	[IsRenewalAccepted] [bit] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Term] [int] NULL,
	[RenewalType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[SuggestedPrice_Amount] [decimal](16, 2) NULL,
	[SuggestedPrice_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Price_Amount] [decimal](16, 2) NULL,
	[Price_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PaymentAmount_Amount] [decimal](16, 2) NULL,
	[PaymentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ServiceAmount_Amount] [decimal](16, 2) NULL,
	[ServiceAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PaymentFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[InterestRate] [decimal](10, 6) NULL,
	[ResidualValue_Amount] [decimal](16, 2) NULL,
	[ResidualValue_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ExistingNBV_Amount] [decimal](16, 2) NULL,
	[ExistingNBV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[UpgradeRenewalPrice_Amount] [decimal](16, 2) NULL,
	[UpgradeRenewalPrice_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[UpgradeRenewalDollar_Amount] [decimal](16, 2) NULL,
	[UpgradeRenewalDollar_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[UpgradeRenewalPMT_Amount] [decimal](16, 2) NULL,
	[UpgradeRenewalPMT_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[UpgradeRenewalService_Amount] [decimal](16, 2) NULL,
	[UpgradeRenewalService_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[UpgradeRenewalRV_Amount] [decimal](16, 2) NULL,
	[UpgradeRenewalRV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TotalPrice_Amount] [decimal](16, 2) NULL,
	[TotalPrice_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TotalPayment_Amount] [decimal](16, 2) NULL,
	[TotalPayment_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TotalService_Amount] [decimal](16, 2) NULL,
	[TotalService_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[ContractId] [bigint] NULL,
	[AssetCatalogId] [bigint] NULL,
	[PreQuoteId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
