CREATE TYPE [dbo].[PreQuoteSecurityDeposit] AS TABLE(
	[EntityType] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[AllocationType] [nvarchar](11) COLLATE Latin1_General_CI_AS NOT NULL,
	[TransferToReceipt_Amount] [decimal](16, 2) NOT NULL,
	[TransferToReceipt_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Refund] [bit] NOT NULL,
	[AppliedToPayoff_Amount] [decimal](16, 2) NOT NULL,
	[AppliedToPayoff_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Balance_Amount] [decimal](16, 2) NOT NULL,
	[Balance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsActive] [bit] NOT NULL,
	[AvailableAmount_Amount] [decimal](16, 2) NOT NULL,
	[AvailableAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayableDate] [date] NULL,
	[WithholdingTaxRate] [decimal](5, 2) NULL,
	[PartyId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[SecurityDepositAllocationId] [bigint] NOT NULL,
	[SecurityDepositApplicationId] [bigint] NULL,
	[PreQuoteId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
