CREATE TYPE [dbo].[PreQuoteLease] AS TABLE(
	[IsActive] [bit] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ManagementYield] [decimal](28, 18) NOT NULL,
	[Payment_Amount] [decimal](16, 2) NOT NULL,
	[Payment_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[RemainingRentalReceivable_Amount] [decimal](16, 2) NOT NULL,
	[RemainingRentalReceivable_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[RemainingIncomeBalance_Amount] [decimal](16, 2) NOT NULL,
	[RemainingIncomeBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BookedResidual_Amount] [decimal](16, 2) NOT NULL,
	[BookedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[OTPStartDate] [date] NULL,
	[OTPIncome_Amount] [decimal](16, 2) NOT NULL,
	[OTPIncome_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[OTPDepreciation_Amount] [decimal](16, 2) NOT NULL,
	[OTPDepreciation_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreQuoteContractId] [bigint] NOT NULL,
	[LeaseFinanceId] [bigint] NOT NULL,
	[PayoffId] [bigint] NULL,
	[PreQuoteId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
