CREATE TYPE [dbo].[PreQuote] AS TABLE(
	[QuoteNumber] [bigint] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Status] [nvarchar](23) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsFutureQuote] [bit] NOT NULL,
	[QuoteType] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[EffectiveDate] [date] NOT NULL,
	[GoodThroughDate] [date] NULL,
	[PaydownReason] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[PayoffAssetStatus] [nvarchar](21) COLLATE Latin1_General_CI_AS NULL,
	[IsMultiQuote] [bit] NOT NULL,
	[IsRenewalQuote] [bit] NOT NULL,
	[Comment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[DueDate] [date] NULL,
	[BillingComment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[CustomerId] [bigint] NOT NULL,
	[TerminationOptionId] [bigint] NULL,
	[CurrencyId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[BusinessUnitId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
