CREATE TYPE [dbo].[PropertyTax] AS TABLE(
	[ReportingYear] [decimal](4, 0) NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[LienDate] [date] NULL,
	[BillNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxDistrict] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[CollectorTitle] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PropertyTaxRate] [decimal](8, 4) NOT NULL,
	[PropertyTaxAmount_Amount] [decimal](16, 2) NOT NULL,
	[PropertyTaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[DueDate] [date] NOT NULL,
	[PostDate] [date] NOT NULL,
	[DisbursementBatchID] [int] NULL,
	[ReversalPostDate] [date] NULL,
	[InvoiceAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[NumberofInstallments] [int] NULL,
	[InstallmentNumber] [int] NULL,
	[IsActive] [bit] NOT NULL,
	[IsManuallyAssessed] [bit] NOT NULL,
	[ContractId] [bigint] NOT NULL,
	[StateId] [bigint] NULL,
	[RemitToId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NOT NULL,
	[ReceivableCodeForAdminFeeId] [bigint] NULL,
	[PropTaxReceivableId] [bigint] NULL,
	[ReceivableForAdminFeeId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
