CREATE TYPE [dbo].[ProposalExhibit] AS TABLE(
	[Number] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Term] [decimal](10, 6) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsProgressFunding] [bit] NOT NULL,
	[IsIndexBasedProgressFunding] [bit] NOT NULL,
	[ProgressFundingIndexAsofDate] [date] NULL,
	[ProgressFundingBaseRate] [decimal](10, 6) NULL,
	[ProgressFundingSpread] [decimal](10, 6) NULL,
	[ProgressFundingFloorRate] [decimal](10, 6) NULL,
	[ProgressFundingCeilingRate] [decimal](10, 6) NULL,
	[ProgressFundingTotalRate] [decimal](10, 6) NULL,
	[ProgressFundingDescription] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[IsIndexBased] [bit] NOT NULL,
	[IndexAsofDate] [date] NULL,
	[BaseRate] [decimal](10, 6) NOT NULL,
	[Spread] [decimal](10, 6) NOT NULL,
	[TotalRate] [decimal](10, 6) NOT NULL,
	[IsAdvance] [bit] NOT NULL,
	[PaymentFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NOT NULL,
	[NumberofPayments] [int] NOT NULL,
	[ExpectedCommencementDate] [date] NULL,
	[PricingCommencementDate] [date] NULL,
	[VendorSubsidy_Amount] [decimal](16, 2) NOT NULL,
	[VendorSubsidy_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[EstimatedBalloonAmount_Amount] [decimal](16, 2) NOT NULL,
	[EstimatedBalloonAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Revolving] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsRegularPaymentStream] [bit] NOT NULL,
	[IrregularFrequencyDescription] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsSaleLeaseback] [bit] NOT NULL,
	[BankIndexDescription] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[CustomerTerm] [int] NULL,
	[CompoundingFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NOT NULL,
	[NumberOfInceptionPayments] [int] NOT NULL,
	[RentFactor] [decimal](18, 8) NOT NULL,
	[Rent_Amount] [decimal](16, 2) NOT NULL,
	[Rent_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ProposedResidualFactor] [decimal](18, 8) NOT NULL,
	[ProposedResidual_Amount] [decimal](16, 2) NOT NULL,
	[ProposedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[GuaranteedResidualFactor] [decimal](18, 8) NOT NULL,
	[GuaranteedResidual_Amount] [decimal](16, 2) NOT NULL,
	[GuaranteedResidual_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[InceptionPayment_Amount] [decimal](16, 2) NOT NULL,
	[InceptionPayment_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[InceptionRentFactor] [decimal](18, 8) NOT NULL,
	[FrequencyStartDate] [date] NULL,
	[DayCountConvention] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[DueDay] [int] NOT NULL,
	[ResidualatRisk_Amount] [decimal](16, 2) NOT NULL,
	[ResidualatRisk_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsResidualSharing] [bit] NOT NULL,
	[DownPayment_Amount] [decimal](16, 2) NOT NULL,
	[DownPayment_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PricingOption] [nvarchar](12) COLLATE Latin1_General_CI_AS NOT NULL,
	[DealProductTypeId] [bigint] NULL,
	[DealTypeId] [bigint] NULL,
	[PricingBaseIndexId] [bigint] NULL,
	[ProgressFundingBaseIndexId] [bigint] NULL,
	[ProposalExhibitTemplateId] [bigint] NULL,
	[ProgramIndicatorConfigId] [bigint] NULL,
	[CreditProfileId] [bigint] NULL,
	[ProposalId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
