CREATE TYPE [dbo].[Quote] AS TABLE(
	[Number] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[EstimatedFinancialAmount_Amount] [decimal](16, 2) NULL,
	[EstimatedFinancialAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ResidualPercentage] [decimal](5, 2) NULL,
	[ResidualAmount_Amount] [decimal](16, 2) NULL,
	[ResidualAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[QuotePaymentAmount_Amount] [decimal](16, 2) NULL,
	[QuotePaymentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[EstimatedBalloonAmount_Amount] [decimal](16, 2) NULL,
	[EstimatedBalloonAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[IsAdvance] [bit] NOT NULL,
	[QuoteExpirationDate] [date] NULL,
	[IsQuoteRequested] [bit] NOT NULL,
	[CalculatedPaymentAmount_Amount] [decimal](16, 2) NULL,
	[CalculatedPaymentAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ProgramRateCardRate] [decimal](10, 6) NULL,
	[ProgramRateCardYield] [decimal](10, 6) NULL,
	[StepPercentage] [decimal](10, 6) NULL,
	[StepPeriod] [int] NULL,
	[StepPaymentStartDate] [date] NULL,
	[StubAdjustment] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[IsStepPayment] [bit] NOT NULL,
	[CanUsePricingEngine] [bit] NOT NULL,
	[DayCountConvention] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyId] [bigint] NOT NULL,
	[ProgramAssetTypeId] [bigint] NOT NULL,
	[ProgramAssetTypeTermId] [bigint] NOT NULL,
	[ProgramAssetTypeEOTOptionId] [bigint] NOT NULL,
	[ProgramAssetTypeFrequencyId] [bigint] NOT NULL,
	[RequestedPromotionId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[QuoteRequestId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
