CREATE TYPE [dbo].[ReceivableInvoice] AS TABLE(
	[Number] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[DueDate] [date] NOT NULL,
	[IsDummy] [bit] NOT NULL,
	[IsNumberSystemCreated] [bit] NOT NULL,
	[CancellationDate] [date] NULL,
	[InvoiceAmount_Amount] [decimal](16, 2) NOT NULL,
	[InvoiceAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceTaxAmount_Amount] [decimal](16, 2) NOT NULL,
	[InvoiceTaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Balance_Amount] [decimal](16, 2) NOT NULL,
	[Balance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxBalance_Amount] [decimal](16, 2) NOT NULL,
	[TaxBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[EffectiveBalance_Amount] [decimal](16, 2) NOT NULL,
	[EffectiveBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[EffectiveTaxBalance_Amount] [decimal](16, 2) NOT NULL,
	[EffectiveTaxBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[WithHoldingTaxAmount_Amount] [decimal](16, 2) NOT NULL,
	[WithHoldingTaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[WithHoldingTaxBalance_Amount] [decimal](16, 2) NOT NULL,
	[WithHoldingTaxBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceRunDate] [date] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsInvoiceCleared] [bit] NOT NULL,
	[SplitByContract] [bit] NOT NULL,
	[SplitByLocation] [bit] NOT NULL,
	[SplitByAsset] [bit] NOT NULL,
	[SplitCreditsByOriginalInvoice] [bit] NOT NULL,
	[SplitByReceivableAdj] [bit] NOT NULL,
	[SplitReceivableDueDate] [bit] NOT NULL,
	[SplitCustomerPurchaseOrderNumber] [bit] NOT NULL,
	[GenerateSummaryInvoice] [bit] NOT NULL,
	[InvoiceFile_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceFile_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceFile_Content] [varbinary](82) NULL,
	[IsEmailSent] [bit] NOT NULL,
	[IsPrivateLabel] [bit] NOT NULL,
	[IsACH] [bit] NOT NULL,
	[InvoiceFileName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoicePreference] [nvarchar](18) COLLATE Latin1_General_CI_AS NOT NULL,
	[RunTimeComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[OriginationSource] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[OriginationSourceId] [bigint] NULL,
	[LastReceivedDate] [date] NULL,
	[IsPdfGenerated] [bit] NOT NULL,
	[DeliveryDate] [date] NULL,
	[DeliveryMethod] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[DaysLateCount] [int] NULL,
	[IsStatementInvoice] [bit] NOT NULL,
	[LastStatementGeneratedDueDate] [date] NULL,
	[StatementInvoicePreference] [nvarchar](18) COLLATE Latin1_General_CI_AS NOT NULL,
	[CurrencyISO] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivableAmount_Amount] [decimal](16, 2) NOT NULL,
	[ReceivableAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxAmount_Amount] [decimal](16, 2) NOT NULL,
	[TaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LegalEntityNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerName] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[RemitToName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[AlternateBillingCurrencyISO] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableTaxType] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[DealCountryId] [bigint] NULL,
	[OriginalInvoiceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CustomerId] [bigint] NOT NULL,
	[BillToId] [bigint] NOT NULL,
	[RemitToId] [bigint] NOT NULL,
	[CancelledById] [bigint] NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[ReceivableCategoryId] [bigint] NOT NULL,
	[ReportFormatId] [bigint] NULL,
	[JobStepInstanceId] [bigint] NULL,
	[DeliveryJobStepInstanceId] [bigint] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[EmailNotificationId] [bigint] NULL,
	[AlternateBillingCurrencyId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
