CREATE TYPE [dbo].[ReceiptPostByLockBox_Extract] AS TABLE(
	[LegalEntityNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[CustomerNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ContractNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ReceivedAmount] [decimal](16, 2) NULL,
	[ReceivedDate] [date] NULL,
	[CheckNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BankName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[BankAccountNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BankAccountNumberEncrypted] [varbinary](max) NULL,
	[RowNumber] [bigint] NULL,
	[IsValid] [bit] NOT NULL,
	[ErrorCode] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[ErrorMessage] [nvarchar](4000) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[EntityType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[LegalEntityId] [bigint] NULL,
	[LineOfBusinessId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[CurrencyId] [bigint] NULL,
	[CashTypeId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[GLTemplateId] [bigint] NULL,
	[BankAccountId] [bigint] NULL,
	[JobStepInstanceId] [bigint] NULL,
	[MigratedUniqueIdentifier] [uniqueidentifier] NULL,
	[FileName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[LockBoxString] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptClassification] [nvarchar](23) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptTypeId] [bigint] NULL,
	[IsValidLegalEntity] [bit] NOT NULL,
	[IsValidInvoice] [bit] NOT NULL,
	[IsValidContract] [bit] NOT NULL,
	[IsValidCustomer] [bit] NOT NULL,
	[IsValidBankName] [bit] NOT NULL,
	[IsValidBankAccountNumber] [bit] NOT NULL,
	[IsContractCustomerAssociated] [bit] NOT NULL,
	[IsContractLegalEntityAssociated] [bit] NOT NULL,
	[CustomerId] [bigint] NULL,
	[IsInvoiceCustomerAssociated] [bit] NOT NULL,
	[IsInvoiceLegalEntityAssociated] [bit] NOT NULL,
	[IsInvoiceContractAssociated] [bit] NOT NULL,
	[ReceiptBatchId] [bigint] NULL,
	[HasMandatoryFields] [bit] NOT NULL,
	[IsFullPosting] [bit] NOT NULL,
	[HasMoreInvoice] [bit] NOT NULL,
	[ContractId] [bigint] NULL,
	[DiscountingId] [bigint] NULL,
	[ReceivableInvoiceId] [bigint] NULL,
	[IsNonAccrualLoan] [bit] NOT NULL,
	[LockBoxReceiptId] [bigint] NULL,
	[IsStatementInvoice] [bit] NULL,
	[CreateUnallocatedReceipt] [bit] NOT NULL,
	[PayOffId] [bigint] NULL,
	[PayDownId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
