CREATE TYPE [dbo].[ReceiptMigration_Extract] AS TABLE(
	[ReceiptMigrationId] [bigint] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ContractSequenceNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LegalEntityNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[CheckNumber] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptAmount_Amount] [decimal](16, 2) NOT NULL,
	[ReceiptAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PostDate] [date] NULL,
	[IsPureUnallocatedCash] [bit] NOT NULL,
	[TotalAmountToApply_Amount] [decimal](16, 2) NULL,
	[TotalAmountToApply_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TotalTaxAmountToApply_Amount] [decimal](16, 2) NULL,
	[TotalTaxAmountToApply_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[CashTypeName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyCode] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BankAccountNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[BankAccountBranchName] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[BankAccountBankName] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[BankName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptGLTemplateName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptTypeName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[UniqueIdentifier] [uniqueidentifier] NOT NULL,
	[ReceivedDate] [date] NULL,
	[IsValid] [bit] NOT NULL,
	[ErrorMessage] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsProcessed] [bit] NOT NULL,
	[JobStepInstanceId] [bigint] NULL,
	[Comment] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
