CREATE TYPE [dbo].[ReceiptParam] AS TABLE(
	[Number] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptAmount] [decimal](16, 2) NULL,
	[Balance] [decimal](16, 2) NULL,
	[EntityType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[PostDate] [date] NULL,
	[ReceivedDate] [date] NULL,
	[Status] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ApplyByReceivable] [bit] NULL,
	[NonCashReason] [nvarchar](28) COLLATE Latin1_General_CI_AS NULL,
	[SecurityDepositLiabilityAmount] [decimal](16, 2) NULL,
	[SecurityDepositLiabilityContractAmount] [decimal](16, 2) NULL,
	[ReceiptClassification] [nvarchar](24) COLLATE Latin1_General_CI_AS NULL,
	[IsFromReceiptBatch] [bit] NULL,
	[CheckNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CheckDate] [date] NULL,
	[NameOnCheck] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[BankName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ReversalDate] [date] NULL,
	[ReversalPostDate] [date] NULL,
	[CreateRefund] [bit] NULL,
	[PayableDate] [date] NULL,
	[DueDate] [date] NULL,
	[LegalEntityId] [bigint] NULL,
	[CurrencyId] [bigint] NULL,
	[BankAccountId] [bigint] NULL,
	[CashTypeId] [bigint] NULL,
	[TypeId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[ReceiptGLTemplateId] [bigint] NULL,
	[ReceiptBatchId] [bigint] NULL,
	[ReversalReasonId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[ReceivableRemitToId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[SundryId] [bigint] NULL,
	[EscrowGLTemplateId] [bigint] NULL,
	[CostCenterId] [bigint] NULL
)
GO
