CREATE TYPE [dbo].[Receipt] AS TABLE(
	[Number] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ReceiptAmount_Amount] [decimal](16, 2) NOT NULL,
	[ReceiptAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Balance_Amount] [decimal](16, 2) NOT NULL,
	[Balance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[EntityType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[PostDate] [date] NULL,
	[ReceivedDate] [date] NULL,
	[Status] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ApplyByReceivable] [bit] NOT NULL,
	[NonCashReason] [nvarchar](28) COLLATE Latin1_General_CI_AS NULL,
	[SecurityDepositLiabilityAmount_Amount] [decimal](16, 2) NULL,
	[SecurityDepositLiabilityAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[SecurityDepositLiabilityContractAmount_Amount] [decimal](16, 2) NULL,
	[SecurityDepositLiabilityContractAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptClassification] [nvarchar](23) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsFromReceiptBatch] [bit] NOT NULL,
	[ReversalDate] [date] NULL,
	[ReversalAsOfDate] [datetimeoffset](7) NULL,
	[ReversalPostDate] [date] NULL,
	[CreateRefund] [bit] NOT NULL,
	[PayableDate] [date] NULL,
	[DueDate] [date] NULL,
	[CheckNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CheckDate] [date] NULL,
	[NameOnCheck] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[BankName] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](1000) COLLATE Latin1_General_CI_AS NULL,
	[JobId] [bigint] NULL,
	[IsReceiptCreatedFromLockBox] [bit] NOT NULL,
	[JobStepInstanceId] [bigint] NULL,
	[PayableWithholdingTaxRate] [decimal](5, 2) NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[CurrencyId] [bigint] NOT NULL,
	[BankAccountId] [bigint] NULL,
	[CashTypeId] [bigint] NULL,
	[TypeId] [bigint] NOT NULL,
	[CustomerId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[ReceiptGLTemplateId] [bigint] NOT NULL,
	[ReceiptBatchId] [bigint] NULL,
	[ReversalReasonId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[ReceivableRemitToId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[SundryId] [bigint] NULL,
	[EscrowGLTemplateId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[DiscountingId] [bigint] NULL,
	[OriginalReceiptId] [bigint] NULL,
	[ReceivableInvoiceId] [bigint] NULL,
	[DealCountryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
