CREATE TYPE [dbo].[ReceiptDiscountingContracts_Extract] AS TABLE(
	[ContractId] [bigint] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[DiscountingId] [bigint] NOT NULL,
	[DiscountingFinanceId] [bigint] NOT NULL,
	[SharedPercentage] [decimal](16, 2) NULL,
	[BookedResidual] [decimal](16, 2) NULL,
	[ResidualBalance] [decimal](16, 2) NULL,
	[IncludeResidual] [bit] NOT NULL,
	[DiscountingContractId] [bigint] NULL,
	[PaymentAllocation] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[MaturityDate] [date] NULL,
	[FunderId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[LineOfBusinessId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[CurrencyId] [bigint] NULL,
	[Currency] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[InterestPayableCodeId] [bigint] NULL,
	[PrincipalPayableCodeId] [bigint] NULL,
	[ResidualRepaymentId] [bigint] NULL,
	[ResidualAmountUtilized] [decimal](16, 2) NULL,
	[JobStepInstanceId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
