CREATE TYPE [dbo].[ReceiptContractRecoveryDetails_Extract] AS TABLE(
	[ContractId] [bigint] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ContractType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[ChargeOffId] [bigint] NULL,
	[TotalChargeOffAmount] [decimal](16, 2) NULL,
	[TotalRecoveryAmount] [decimal](16, 2) NULL,
	[ChargeOffReasonCodeConfigId] [bigint] NULL,
	[NetInvestmentWithBlended] [decimal](16, 2) NULL,
	[WriteDownId] [bigint] NULL,
	[TotalWriteDownAmount] [decimal](16, 2) NULL,
	[TotalRecoveryAmountForWriteDown] [decimal](16, 2) NULL,
	[NetWriteDown] [decimal](16, 2) NULL,
	[ChargeOffGLTemplateId] [bigint] NULL,
	[WriteDownGLTemplateId] [bigint] NULL,
	[RecoveryGLTemplateId] [bigint] NULL,
	[RecoveryReceivableCodeId] [bigint] NULL,
	[WriteDownDate] [date] NULL,
	[WriteDownReason] [nvarchar](18) COLLATE Latin1_General_CI_AS NULL,
	[LeaseFinanceId] [bigint] NULL,
	[LoanFinanceId] [bigint] NULL,
	[JobStepInstanceId] [bigint] NULL,
	[TotalLeaseComponentChargeOffAmount] [decimal](16, 2) NULL,
	[TotalNonLeaseComponentChargeOffAmount] [decimal](16, 2) NULL,
	[TotalLeaseComponentRecoveryAmount] [decimal](16, 2) NULL,
	[TotalNonLeaseComponentRecoveryAmount] [decimal](16, 2) NULL,
	[TotalLeaseComponentGainAmount] [decimal](16, 2) NULL,
	[TotalNonLeaseComponentGainAmount] [decimal](16, 2) NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
