CREATE TYPE [dbo].[ReceiptApplicationReceivableGroup] AS TABLE(
	[AmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[AmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TaxApplied_Amount] [decimal](16, 2) NOT NULL,
	[TaxApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BookAmountApplied_Amount] [decimal](16, 2) NULL,
	[BookAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PreviousAmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[PreviousAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreviousTaxApplied_Amount] [decimal](16, 2) NOT NULL,
	[PreviousTaxApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreviousBookAmountApplied_Amount] [decimal](16, 2) NULL,
	[PreviousBookAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[IsReApplication] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[ReceivedAmount_Amount] [decimal](16, 2) NOT NULL,
	[ReceivedAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AdjustedWithHoldingTax_Amount] [decimal](16, 2) NOT NULL,
	[AdjustedWithHoldingTax_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreviousAdjustedWithHoldingTax_Amount] [decimal](16, 2) NOT NULL,
	[PreviousAdjustedWithHoldingTax_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivableId] [bigint] NOT NULL,
	[ReceiptApplicationId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
