CREATE TYPE [dbo].[ReceiptApplicationReceivableDetail] AS TABLE(
	[AmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[AmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TaxApplied_Amount] [decimal](16, 2) NOT NULL,
	[TaxApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[BookAmountApplied_Amount] [decimal](16, 2) NULL,
	[BookAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PreviousAmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[PreviousAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreviousBookAmountApplied_Amount] [decimal](16, 2) NULL,
	[PreviousBookAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PreviousTaxApplied_Amount] [decimal](16, 2) NOT NULL,
	[PreviousTaxApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsGLPosted] [bit] NOT NULL,
	[IsTaxGLPosted] [bit] NOT NULL,
	[RecoveryAmount_Amount] [decimal](16, 2) NOT NULL,
	[RecoveryAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[GainAmount_Amount] [decimal](16, 2) NOT NULL,
	[GainAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsReApplication] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[PrepaidAmount_Amount] [decimal](16, 2) NOT NULL,
	[PrepaidAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PrepaidTaxAmount_Amount] [decimal](16, 2) NOT NULL,
	[PrepaidTaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivedAmount_Amount] [decimal](16, 2) NOT NULL,
	[ReceivedAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivedTowardsInterest_Amount] [decimal](16, 2) NOT NULL,
	[ReceivedTowardsInterest_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AdjustedWithHoldingTax_Amount] [decimal](16, 2) NOT NULL,
	[AdjustedWithHoldingTax_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PreviousAdjustedWithHoldingTax_Amount] [decimal](16, 2) NOT NULL,
	[PreviousAdjustedWithHoldingTax_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LeaseComponentAmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[LeaseComponentAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NonLeaseComponentAmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[NonLeaseComponentAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PrevLeaseComponentAmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[PrevLeaseComponentAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PrevNonLeaseComponentAmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[PrevNonLeaseComponentAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LeaseComponentPrepaidAmount_Amount] [decimal](16, 2) NOT NULL,
	[LeaseComponentPrepaidAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NonLeaseComponentPrepaidAmount_Amount] [decimal](16, 2) NOT NULL,
	[NonLeaseComponentPrepaidAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[WithHoldingTaxBookAmountApplied_Amount] [decimal](16, 2) NOT NULL,
	[WithHoldingTaxBookAmountApplied_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivableDetailId] [bigint] NOT NULL,
	[ReceiptApplicationInvoiceId] [bigint] NULL,
	[ReceiptApplicationReceivableGroupId] [bigint] NULL,
	[ReceivableInvoiceId] [bigint] NULL,
	[PayableId] [bigint] NULL,
	[SundryPayableId] [bigint] NULL,
	[SundryReceivableId] [bigint] NULL,
	[UpfrontTaxSundryId] [bigint] NULL,
	[ReceiptApplicationId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
