CREATE TYPE [dbo].[ReceiptApplicationReceivableDetails_Extract] AS TABLE(
	[ReceiptId] [bigint] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[AmountApplied] [decimal](16, 2) NULL,
	[BookAmountApplied] [decimal](16, 2) NOT NULL,
	[TaxApplied] [decimal](16, 2) NULL,
	[ReceivableDetailId] [bigint] NULL,
	[ReceivableDetailIsActive] [bit] NOT NULL,
	[ContractId] [bigint] NULL,
	[DiscountingId] [bigint] NULL,
	[InvoiceId] [bigint] NULL,
	[ReceiptApplicationReceivableDetailId] [bigint] NOT NULL,
	[ReceivableId] [bigint] NULL,
	[JobStepInstanceId] [bigint] NULL,
	[DumpId] [bigint] NULL,
	[PrevAmountAppliedForReApplication] [decimal](16, 2) NULL,
	[PrevBookAmountAppliedForReApplication] [decimal](16, 2) NULL,
	[PrevTaxAppliedForReApplication] [decimal](16, 2) NULL,
	[PrevAdjustedWithHoldingTaxForReApplication] [decimal](16, 2) NULL,
	[PrevPrePaidForReApplication] [decimal](16, 2) NULL,
	[PrevPrePaidTaxForReApplication] [decimal](16, 2) NULL,
	[ReceiptApplicationId] [bigint] NULL,
	[IsReApplication] [bit] NOT NULL,
	[ReceivedTowardsInterest] [decimal](16, 2) NULL,
	[AdjustedWithHoldingTax] [decimal](16, 2) NULL,
	[LeaseComponentAmountApplied] [decimal](16, 2) NULL,
	[PrevLeaseComponentAmountAppliedForReApplication] [decimal](16, 2) NULL,
	[NonLeaseComponentAmountApplied] [decimal](16, 2) NULL,
	[PrevNonLeaseComponentAmountAppliedForReApplication] [decimal](16, 2) NULL,
	[PrevPrePaidLeaseComponentForReApplication] [decimal](16, 2) NULL,
	[PrevPrePaidNonLeaseComponentForReApplication] [decimal](16, 2) NULL,
	[WithHoldingTaxBookAmountApplied] [decimal](16, 2) NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
