CREATE TYPE [dbo].[Receivable] AS TABLE(
	[EntityType] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[EntityId] [bigint] NOT NULL,
	[DueDate] [date] NOT NULL,
	[IsDSL] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[InvoiceComment] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceReceivableGroupingOption] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsGLPosted] [bit] NOT NULL,
	[IncomeType] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[PaymentScheduleId] [bigint] NULL,
	[IsCollected] [bit] NOT NULL,
	[IsServiced] [bit] NOT NULL,
	[IsDummy] [bit] NOT NULL,
	[IsPrivateLabel] [bit] NOT NULL,
	[SourceTable] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[SourceId] [bigint] NULL,
	[TotalAmount_Amount] [decimal](16, 2) NOT NULL,
	[TotalAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TotalBalance_Amount] [decimal](16, 2) NOT NULL,
	[TotalBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TotalEffectiveBalance_Amount] [decimal](16, 2) NOT NULL,
	[TotalEffectiveBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TotalBookBalance_Amount] [decimal](16, 2) NULL,
	[TotalBookBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ExchangeRate] [decimal](20, 10) NULL,
	[CalculatedDueDate] [date] NULL,
	[CreationSourceTable] [nvarchar](21) COLLATE Latin1_General_CI_AS NULL,
	[CreationSourceId] [bigint] NULL,
	[ReceivableTaxType] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[DealCountryId] [bigint] NULL,
	[UniqueIdentifier] [nvarchar](30) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableCodeId] [bigint] NOT NULL,
	[CustomerId] [bigint] NULL,
	[FunderId] [bigint] NULL,
	[RemitToId] [bigint] NOT NULL,
	[TaxRemitToId] [bigint] NOT NULL,
	[LocationId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[AlternateBillingCurrencyId] [bigint] NULL,
	[TaxSourceDetailId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
