CREATE TYPE [dbo].[RemitTo] AS TABLE(
	[Name] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Code] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[UniqueIdentifier] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[ReceiptType] [nvarchar](5) COLLATE Latin1_General_CI_AS NOT NULL,
	[WireType] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[ActivationDate] [date] NOT NULL,
	[DeactivationDate] [date] NULL,
	[Description] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsSecuredParty] [bit] NOT NULL,
	[IsPrivateLabel] [bit] NOT NULL,
	[DefaultFromEmail] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[InvoiceFooterText] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LegalEntityContactId] [bigint] NULL,
	[LegalEntityAddressId] [bigint] NULL,
	[PartyContactId] [bigint] NULL,
	[PartyAddressId] [bigint] NULL,
	[UserGroupId] [bigint] NULL,
	[LogoId] [bigint] NULL,
	[PortfolioId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
