CREATE TYPE [dbo].[RMAProfile] AS TABLE(
	[TransactionNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[RMAStatus] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[NotifiedCustomer] [bit] NOT NULL,
	[NotifiedShippingCompany] [bit] NOT NULL,
	[NotifiedRefurbishmentCenter] [bit] NOT NULL,
	[Canadian] [bit] NOT NULL,
	[LastDateToBill] [date] NULL,
	[ShippingOption] [nvarchar](17) COLLATE Latin1_General_CI_AS NOT NULL,
	[ActualPickupDate] [date] NULL,
	[EstimatedPickupDate] [date] NULL,
	[DeliveryDate] [date] NULL,
	[ExpectedDeliveryDate] [date] NULL,
	[AuditReceivedDate] [date] NULL,
	[TrackingNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InsuranceAmount_Amount] [decimal](16, 2) NOT NULL,
	[InsuranceAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ShipToInside] [bit] NOT NULL,
	[ShipToLiftgate] [bit] NOT NULL,
	[ShipFromAddressLine1] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromAddressLine2] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromCity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromZip] [nvarchar](12) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromPrimaryContact] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromPhoneNumber1] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromMobilePhoneNumber1] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromEMailId1] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromAdditionalContact] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromPhoneNumber2] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromMobilePhoneNumber2] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ShipFromEMailId2] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[DockHours] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CallFirst] [bit] NOT NULL,
	[ShipFromInside] [bit] NOT NULL,
	[ShipFromLiftgate] [bit] NOT NULL,
	[CityTruckRequired] [bit] NOT NULL,
	[ClimateControl] [bit] NOT NULL,
	[FloorCoveringNeeded] [bit] NOT NULL,
	[CertificateofInsuranceRequired] [bit] NOT NULL,
	[PackingNeeded] [bit] NOT NULL,
	[Wheels] [bit] NOT NULL,
	[Palletized] [bit] NOT NULL,
	[EstimatedWeight] [int] NULL,
	[EstimatedDimensions] [int] NULL,
	[DockHeight] [int] NULL,
	[FreightComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[InsuredValue_Amount] [decimal](16, 2) NOT NULL,
	[InsuredValue_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[DeInstallationRequired] [bit] NOT NULL,
	[Bandling] [bit] NOT NULL,
	[Licenses] [bit] NOT NULL,
	[WipeHardDrives] [bit] NOT NULL,
	[RestoreSoftware] [bit] NOT NULL,
	[PasswordsRequired] [bit] NOT NULL,
	[AuditRequired] [bit] NOT NULL,
	[EquipmentDispositionComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[ShipToPhoneNumber1] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ShipToMobilePhoneNumber1] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ShipToEMailId1] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[ShipToPhoneNumber2] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ShipToMobilePhoneNumber2] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[ShipToEMailId2] [nvarchar](70) COLLATE Latin1_General_CI_AS NULL,
	[CustomerId] [bigint] NOT NULL,
	[CurrencyId] [bigint] NOT NULL,
	[SalesRepId] [bigint] NULL,
	[ProductManagerId] [bigint] NULL,
	[AuthorizedById] [bigint] NULL,
	[ShippingCompanyId] [bigint] NULL,
	[ShipToId] [bigint] NULL,
	[ShipToLocationId] [bigint] NULL,
	[ShipFromLocationId] [bigint] NULL,
	[ShipFromStateId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
