CREATE TYPE [dbo].[SecurityDepositApplication] AS TABLE(
	[EntityType] [nvarchar](11) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TransferToIncome_Amount] [decimal](16, 2) NOT NULL,
	[TransferToIncome_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TransferToReceipt_Amount] [decimal](16, 2) NOT NULL,
	[TransferToReceipt_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[AssumedAmount_Amount] [decimal](16, 2) NOT NULL,
	[AssumedAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsActive] [bit] NOT NULL,
	[PostDate] [date] NULL,
	[IsRefund] [bit] NOT NULL,
	[PayableDate] [date] NULL,
	[WithholdingTaxRate] [decimal](5, 2) NULL,
	[ReceiptId] [bigint] NULL,
	[GlJournalId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[PartyId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[SecurityDepositId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
