CREATE TYPE [dbo].[ShellCustomerDetail] AS TABLE(
	[SFDCId] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Status] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsCorporate] [bit] NOT NULL,
	[FirstName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[MiddleName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LastName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CompanyName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[IsSoleProprietor] [bit] NOT NULL,
	[DateOfBirth] [date] NULL,
	[CIPDocumentSourceForName] [nvarchar](61) COLLATE Latin1_General_CI_AS NULL,
	[LegalNameValidationDate] [date] NULL,
	[PartyType] [nvarchar](42) COLLATE Latin1_General_CI_AS NULL,
	[IncomeTaxStatus] [nvarchar](18) COLLATE Latin1_General_CI_AS NULL,
	[PercentageOfGovernmentOwnership] [decimal](5, 2) NULL,
	[IsShellCustomerCreated] [bit] NOT NULL,
	[UniqueIdentificationNumber] [nvarchar](18) COLLATE Latin1_General_CI_AS NULL,
	[BusinessTypeId] [bigint] NULL,
	[StateOfIncorporationId] [bigint] NULL,
	[ApprovedRegulatorId] [bigint] NULL,
	[BusinessTypeNAICSCodeId] [bigint] NULL,
	[ApprovedExchangeId] [bigint] NULL,
	[JurisdictionOfSovereignId] [bigint] NULL,
	[CIPDocumentSourceNameId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
