CREATE TYPE [dbo].[StatementInvoiceReceivableDetails_Extract] AS TABLE(
	[ReceivableInvoiceId] [bigint] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ReceivableDetailId] [bigint] NOT NULL,
	[ReceivableId] [bigint] NOT NULL,
	[JobStepInstanceId] [bigint] NOT NULL,
	[JobProcessThroughDate] [date] NULL,
	[IsInvoiceSensitive] [bit] NOT NULL,
	[EntityType] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[EntityId] [bigint] NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[ContractType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[ContractId] [bigint] NULL,
	[DiscountingId] [bigint] NULL,
	[BillToId] [bigint] NOT NULL,
	[RemitToId] [bigint] NOT NULL,
	[CustomerId] [bigint] NOT NULL,
	[InvoiceDueDate] [date] NULL,
	[ReceivableDueDate] [date] NOT NULL,
	[LastStatementGeneratedDueDate] [date] NULL,
	[IsPrivateLabel] [bit] NOT NULL,
	[IsDSL] [bit] NOT NULL,
	[IsACH] [bit] NOT NULL,
	[CT_InvoiceTransitDays] [int] NULL,
	[CT_InvoiceLeadDays] [int] NULL,
	[CU_InvoiceTransitDays] [int] NOT NULL,
	[CU_InvoiceLeadDays] [int] NOT NULL,
	[AssetId] [bigint] NULL,
	[RI_StatementInvoicePreference] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[SplitRentalInvoiceByAsset] [bit] NOT NULL,
	[SplitCreditsByOriginalInvoice] [bit] NOT NULL,
	[SplitByReceivableAdjustments] [bit] NOT NULL,
	[SplitRentalInvoiceByContract] [bit] NOT NULL,
	[SplitLeaseRentalInvoiceByLocation] [bit] NOT NULL,
	[SplitReceivableDueDate] [bit] NOT NULL,
	[SplitCustomerPurchaseOrderNumber] [bit] NOT NULL,
	[GenerateSummaryInvoice] [bit] NOT NULL,
	[StatementInvoiceFormatId] [bigint] NULL,
	[ReceivableCategoryId] [bigint] NULL,
	[ReceivableCategoryName] [nvarchar](16) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceAmount] [decimal](16, 2) NOT NULL,
	[InvoiceBalance] [decimal](16, 2) NOT NULL,
	[InvoiceEffectiveBalance] [decimal](16, 2) NOT NULL,
	[InvoiceTaxAmount] [decimal](16, 2) NOT NULL,
	[InvoiceTaxBalance] [decimal](16, 2) NOT NULL,
	[InvoiceTaxEffectiveBalance] [decimal](16, 2) NOT NULL,
	[InvoiceCurrency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[CurrencyId] [bigint] NOT NULL,
	[ExchangeRate] [decimal](16, 2) NULL,
	[AlternateBillingCurrencyId] [bigint] NULL,
	[ReceivableDetailAmount] [decimal](16, 2) NOT NULL,
	[ReceivableDetailBalance] [decimal](16, 2) NOT NULL,
	[ReceivableDetailEffectiveBalance] [decimal](16, 2) NOT NULL,
	[OriginalTaxBalance] [decimal](16, 2) NOT NULL,
	[OriginalTaxEffectiveBalance] [decimal](16, 2) NOT NULL,
	[LocationId] [bigint] NULL,
	[IsReceivableTypeRental] [bit] NOT NULL,
	[WithHoldingTaxAmount] [decimal](16, 2) NULL,
	[WithHoldingTaxBalance] [decimal](16, 2) NULL,
	[ReceivableTypeId] [bigint] NOT NULL,
	[ReceivableTypeName] [nvarchar](21) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivableCodeId] [bigint] NOT NULL,
	[DefaultInvoiceReceivableGroupingOption] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[IsReceivableAdjustment] [bit] NOT NULL,
	[AdjustmentBasisReceivableDetailId] [bigint] NULL,
	[ReportFormatId] [bigint] NULL,
	[IsCurrentInstance] [bit] NOT NULL,
	[IsOffPeriod] [bit] NOT NULL,
	[GroupNumber] [bigint] NULL,
	[ComputedSIDueDate] [date] NULL,
	[StatementDueDay] [int] NULL,
	[IsActive] [bit] NOT NULL,
	[AssetPurchaseOrderNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[LegalEntityNumber] [nvarchar](20) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[CustomerName] [nvarchar](250) COLLATE Latin1_General_CI_AS NOT NULL,
	[RemitToName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[AlternateBillingCurrencyISO] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyISO] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivableTaxType] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[DealCountryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
