CREATE TYPE [dbo].[SundryRecurring] AS TABLE(
	[FirstDueDate] [date] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[NextPaymentDate] [date] NULL,
	[SundryType] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[Status] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[EntityType] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[InvoiceComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[Memo] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[IsAssetBased] [bit] NOT NULL,
	[PaymentDateOffset] [int] NOT NULL,
	[IsRentalBased] [bit] NOT NULL,
	[BillPastEndDate] [bit] NOT NULL,
	[NumberOfPayments] [int] NOT NULL,
	[Frequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NOT NULL,
	[NumberOfDays] [int] NOT NULL,
	[DueDay] [int] NOT NULL,
	[TerminationDate] [date] NULL,
	[ProcessThroughDate] [date] NULL,
	[InvoiceAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[IsTaxExempt] [bit] NOT NULL,
	[IsFinancialParametersChanged] [bit] NOT NULL,
	[IsPayableAdjusted] [bit] NOT NULL,
	[IsServiced] [bit] NOT NULL,
	[IsCollected] [bit] NOT NULL,
	[IsPrivateLabel] [bit] NOT NULL,
	[IsOwned] [bit] NOT NULL,
	[IsRegular] [bit] NOT NULL,
	[IsApplyAtAssetLevel] [bit] NOT NULL,
	[RegularAmount_Amount] [decimal](16, 2) NULL,
	[RegularAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[PayableAmount_Amount] [decimal](16, 2) NOT NULL,
	[PayableAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsSystemGenerated] [bit] NOT NULL,
	[IsExternalTermination] [bit] NOT NULL,
	[Type] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayableWithholdingTaxRate] [decimal](5, 2) NULL,
	[IsVATAssessed] [bit] NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[ContractId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[ReceivableRemitToId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[LineofBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[CostCenterId] [bigint] NOT NULL,
	[BranchId] [bigint] NULL,
	[CountryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
