CREATE TYPE [dbo].[SundriesToPersist] AS TABLE(
	[Identifier] [bigint] NULL,
	[SundryType] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[PayableDueDate] [date] NULL,
	[ReceivableDueDate] [date] NULL,
	[InvoiceComment] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Memo] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Amount] [decimal](16, 2) NULL,
	[ContractId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[CurrencyId] [bigint] NULL,
	[LineOfBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[ReceivableRemitToId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[IsOwned] [bit] NULL,
	[ContractSequenceNumber] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[Type] [nvarchar](max) COLLATE Latin1_General_CI_AS NULL,
	[CostCenterId] [bigint] NULL,
	[PayableWithholdingTaxRate] [decimal](5, 2) NULL
)
GO
