CREATE TYPE [dbo].[SundryParam] AS TABLE(
	[SundryType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[EntityType] [nvarchar](2) COLLATE Latin1_General_CI_AS NULL,
	[ReceivableDueDate] [date] NULL,
	[InvoiceComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PayableDueDate] [date] NULL,
	[Memo] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[Amount] [decimal](16, 2) NULL,
	[IsServiced] [bit] NULL,
	[IsCollected] [bit] NULL,
	[IsPrivateLabel] [bit] NULL,
	[ReceivableCodeId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[ReceivableRemitToId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[CurrencyId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[IsOwned] [bit] NULL,
	[IsAssignAtAssetLevel] [bit] NULL,
	[IsSystemGenerated] [bit] NULL,
	[InvoiceAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[Type] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[TaxPortionOfPayable] [decimal](16, 2) NULL,
	[ReceivableDetailId] [bigint] NULL,
	[PaymentReceivableId] [bigint] NULL,
	[SourceTable] [varchar](19) COLLATE Latin1_General_CI_AS NULL,
	[SourceTableId] [bigint] NULL
)
GO
