CREATE TYPE [dbo].[Sundry] AS TABLE(
	[EntityType] [nvarchar](2) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[SundryType] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[Amount_Amount] [decimal](16, 2) NOT NULL,
	[Amount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayableAmount_Amount] [decimal](16, 2) NOT NULL,
	[PayableAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[ReceivableDueDate] [date] NULL,
	[IsAssetBased] [bit] NOT NULL,
	[InvoiceComment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[Memo] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PayableDueDate] [date] NULL,
	[IsServiced] [bit] NOT NULL,
	[IsCollected] [bit] NOT NULL,
	[IsPrivateLabel] [bit] NOT NULL,
	[IsOwned] [bit] NOT NULL,
	[IsAssignAtAssetLevel] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsTaxExempt] [bit] NOT NULL,
	[IsSystemGenerated] [bit] NOT NULL,
	[InvoiceAmendmentType] [nvarchar](20) COLLATE Latin1_General_CI_AS NULL,
	[Type] [nvarchar](9) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxPortionOfPayable_Amount] [decimal](16, 2) NOT NULL,
	[TaxPortionOfPayable_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[Status] [nvarchar](8) COLLATE Latin1_General_CI_AS NULL,
	[PayableWithholdingTaxRate] [decimal](5, 2) NULL,
	[IsVATAssessed] [bit] NOT NULL,
	[ProjectedVATAmount_Amount] [decimal](16, 2) NOT NULL,
	[ProjectedVATAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[ContractId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[ReceivableId] [bigint] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[ReceivableCodeId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[ReceivableRemitToId] [bigint] NULL,
	[LocationId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[PayableId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[CountryId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
