CREATE TYPE [dbo].[TaxDepEntity] AS TABLE(
	[EntityType] [nvarchar](14) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TaxBasisAmount_Amount] [decimal](16, 2) NOT NULL,
	[TaxBasisAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[FXTaxBasisAmount_Amount] [decimal](16, 2) NOT NULL,
	[FXTaxBasisAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[TaxProceedsAmount_Amount] [decimal](16, 2) NOT NULL,
	[TaxProceedsAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[DepreciationBeginDate] [date] NOT NULL,
	[DepreciationEndDate] [date] NULL,
	[IsConditionalSale] [bit] NOT NULL,
	[IsStraightLineMethodUsed] [bit] NOT NULL,
	[IsTaxDepreciationTerminated] [bit] NOT NULL,
	[TerminationDate] [date] NULL,
	[IsActive] [bit] NOT NULL,
	[IsComputationPending] [bit] NOT NULL,
	[TerminatedByLeaseId] [bigint] NULL,
	[IsGLPosted] [bit] NOT NULL,
	[PostDate] [date] NULL,
	[TaxDepTemplateId] [bigint] NOT NULL,
	[TaxDepDisposalTemplateId] [bigint] NULL,
	[AssetId] [bigint] NULL,
	[BlendedItemId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
