CREATE TYPE [dbo].[TerminationTypeParameterConfig] AS TABLE(
	[Entity] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Property] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[Parameter] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[Label] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[DiscountRateApplicable] [bit] NOT NULL,
	[FactorApplicable] [bit] NOT NULL,
	[BlendedItemCodeApplicable] [bit] NOT NULL,
	[SundryCodeApplicable] [bit] NOT NULL,
	[NumberofTermsApplicable] [bit] NOT NULL,
	[OperatorSign] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[IsLease] [bit] NOT NULL,
	[ApplicableForFixedTerm] [bit] NOT NULL,
	[ApplicableForOTP] [bit] NOT NULL,
	[IsApplicableForFeeParameter] [bit] NOT NULL,
	[IsApplicableForPayoffAtMaturity] [bit] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
