CREATE TYPE [dbo].[UnallocatedRefund] AS TABLE(
	[EntityType] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[Type] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[PayableDate] [date] NULL,
	[Memo] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[PostDate] [date] NULL,
	[ReversalPostDate] [date] NULL,
	[Status] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[AmountToClear_Amount] [decimal](16, 2) NULL,
	[AmountToClear_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[WithholdingTaxRate] [decimal](5, 2) NULL,
	[ReceiptId] [bigint] NULL,
	[CurrencyId] [bigint] NOT NULL,
	[LegalEntityId] [bigint] NOT NULL,
	[CustomerId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[DiscountingId] [bigint] NULL,
	[LineofBusinessId] [bigint] NULL,
	[InstrumentTypeId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[PayableCodeId] [bigint] NULL,
	[PayableRemitToId] [bigint] NULL,
	[CostCenterId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
