CREATE TYPE [dbo].[User] AS TABLE(
	[FirstName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[LastName] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[FullName] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[LoginName] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsWindowsAuthenticated] [bit] NOT NULL,
	[Password] [nvarchar](65) COLLATE Latin1_General_CI_AS NULL,
	[PhoneNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[FaxNumber] [nvarchar](15) COLLATE Latin1_General_CI_AS NULL,
	[PhoneExtensionNumber] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[Email] [nvarchar](70) COLLATE Latin1_General_CI_AS NOT NULL,
	[IsEmailNotificationAllowed] [bit] NOT NULL,
	[LoginEffectiveDate] [date] NULL,
	[LoginExpiryDate] [date] NULL,
	[IsLoginBlocked] [bit] NOT NULL,
	[IsAdminBlocked] [bit] NOT NULL,
	[LoginBlockedTime] [datetimeoffset](7) NULL,
	[ForcePasswordReset] [bit] NOT NULL,
	[CreationDate] [date] NOT NULL,
	[ActivationDate] [date] NULL,
	[DeactivationDate] [date] NULL,
	[ProfilePicture_Source] [nvarchar](250) COLLATE Latin1_General_CI_AS NULL,
	[ProfilePicture_Type] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[ProfilePicture_Content] [varbinary](82) NULL,
	[IsFactorAuthenticationEnabled] [bit] NOT NULL,
	[IsFactorAuthorizationEnabled] [bit] NOT NULL,
	[CanLogin] [bit] NOT NULL,
	[LoginFailureCounter] [int] NOT NULL,
	[ApprovalStatus] [nvarchar](8) COLLATE Latin1_General_CI_AS NOT NULL,
	[Title] [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
	[ESignJWTUserId] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[DiligenzAccountID] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DiligenzContactNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IsFullAccess] [bit] NOT NULL,
	[ExternalUserId] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[EGN_CT] [varbinary](64) NULL,
	[MiddleName] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IdCardNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IssuedBy] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[IssuedIn] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[PermanentAddressCity] [nvarchar](2000) COLLATE Latin1_General_CI_AS NULL,
	[Role] [nvarchar](14) COLLATE Latin1_General_CI_AS NULL,
	[IsAttorney] [bit] NOT NULL,
	[PowerOfAttorneyNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Validity] [date] NULL,
	[Notary] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[NotaryRegistrationNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[SignatureNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[DefaultBusinessUnitId] [bigint] NULL,
	[MultiFactorAuthenticationId] [bigint] NULL,
	[AdminUserId] [bigint] NULL,
	[DomainId] [bigint] NULL,
	[OrganizationConfigId] [bigint] NULL,
	[ContractId] [bigint] NULL,
	[BillToId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
