CREATE TYPE [dbo].[ValuationAllowance] AS TABLE(
	[PostDate] [date] NOT NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[IsActive] [bit] NOT NULL,
	[Comment] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[OriginalBookValue_Amount] [decimal](16, 2) NULL,
	[OriginalBookValue_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Allowance_Amount] [decimal](16, 2) NULL,
	[Allowance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[ValuationReserveBalance_Amount] [decimal](16, 2) NULL,
	[ValuationReserveBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[NetInvestmentWithBlended_Amount] [decimal](16, 2) NOT NULL,
	[NetInvestmentWithBlended_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NetInvestmentWithReserve_Amount] [decimal](16, 2) NOT NULL,
	[NetInvestmentWithReserve_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[NBV_Amount] [decimal](16, 2) NOT NULL,
	[NBV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[WrittenDownNBV_Amount] [decimal](16, 2) NOT NULL,
	[WrittenDownNBV_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NOT NULL,
	[HFIStatusHistoriesId] [bigint] NULL,
	[GLTemplateId] [bigint] NOT NULL,
	[ContractId] [bigint] NOT NULL,
	[ContractHoldingStatusHistoryId] [bigint] NOT NULL,
	[JobStepInstanceId] [bigint] NULL,
	[BusinessUnitId] [bigint] NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
