CREATE TYPE [dbo].[VATReceivableLocationDetail_Extract] AS TABLE(
	[ReceivableId] [bigint] NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[ReceivableDueDate] [date] NULL,
	[CustomerId] [bigint] NULL,
	[LegalEntityId] [bigint] NULL,
	[ReceivableDetailId] [bigint] NOT NULL,
	[AssetId] [bigint] NULL,
	[JobStepInstanceId] [bigint] NOT NULL,
	[ReceivableTypeId] [bigint] NOT NULL,
	[TaxLevel] [nvarchar](7) COLLATE Latin1_General_CI_AS NOT NULL,
	[BuyerLocationId] [bigint] NOT NULL,
	[SellerLocationId] [bigint] NOT NULL,
	[TaxReceivableTypeId] [bigint] NULL,
	[PayableTypeId] [bigint] NULL,
	[TaxAssetTypeId] [bigint] NULL,
	[TaxRemittanceType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BuyerLocation] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[SellerLocation] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[TaxAssetType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[TaxReceivableType] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BuyerTaxRegistrationId] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[SellerTaxRegistrationId] [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
	[IsCapitalizedUpfront] [bit] NOT NULL,
	[IsReceivableCodeTaxExempt] [bit] NOT NULL,
	[BasisAmount] [decimal](16, 2) NOT NULL,
	[BasisAmountCurrency] [nvarchar](40) COLLATE Latin1_General_CI_AS NOT NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
