CREATE TYPE [dbo].[VehicleDetail] AS TABLE(
	[VehicleType] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[TransmissionType] [nvarchar](9) COLLATE Latin1_General_CI_AS NULL,
	[TankCapacity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[InteriorColor] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[NumberOfCylinders] [int] NULL,
	[PayloadCapacity] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EngineSize] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[WeightClass] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[CO2] [decimal](16, 2) NULL,
	[ContractMileage] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[BodyDescription] [nvarchar](200) COLLATE Latin1_General_CI_AS NULL,
	[OriginalOdometerReading] [int] NULL,
	[OdometerReadingUnit] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[NumberOfDoors] [int] NULL,
	[NumberOfPassengers] [int] NULL,
	[NumberOfSeats] [int] NULL,
	[KeylessEntry] [bit] NOT NULL,
	[MPG] [int] NULL,
	[NumberOfKeys] [int] NULL,
	[DoorKeyCode] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[NumberOfRemotes] [int] NULL,
	[TireSize] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EngineKeyCode] [int] NULL,
	[ExteriorColor] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[WeightUnit] [nvarchar](10) COLLATE Latin1_General_CI_AS NULL,
	[GVW] [decimal](16, 2) NULL,
	[GrossCurbCombinedWeight] [decimal](16, 2) NULL,
	[VehicleRegisteredWeight] [decimal](16, 2) NULL,
	[VehicleCurbWeight] [decimal](16, 2) NULL,
	[Titled] [bit] NOT NULL,
	[TitleTrustOverride] [bit] NOT NULL,
	[TitleBorrowedReason] [nvarchar](19) COLLATE Latin1_General_CI_AS NULL,
	[TitleBorrowedDate] [date] NULL,
	[TitleLienHolder] [nvarchar](16) COLLATE Latin1_General_CI_AS NULL,
	[TitleApplicationSubmissionDate] [date] NULL,
	[TitleReceivedDate] [date] NULL,
	[VehiclePlateNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistrationCertificateNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[RegistrationDate] [date] NULL,
	[UserInRegistrationCertificate] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[EngineNumber] [nvarchar](40) COLLATE Latin1_General_CI_AS NULL,
	[Horsepower] [decimal](16, 2) NULL,
	[BeginningMileage] [decimal](16, 2) NULL,
	[TerminationMileage] [decimal](16, 2) NULL,
	[ExcessMileage] [decimal](16, 2) NULL,
	[EngineCapacity] [decimal](16, 2) NULL,
	[KW] [decimal](16, 2) NULL,
	[VehicleContractMileage] [decimal](16, 2) NULL,
	[Axles] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[VehicleNumberOfKeys] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[VehicleNumberOfDoors] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[LoadCapacity] [decimal](16, 2) NULL,
	[IsGPS] [bit] NULL,
	[IsGPSTracker] [bit] NULL,
	[IsImmobiliser] [bit] NULL,
	[LastDateOfExecution] [date] NULL,
	[NextDateOfExecution] [date] NULL,
	[AssetClassConfigId] [bigint] NULL,
	[FuelTypeConfigId] [bigint] NULL,
	[DriveTrainConfigId] [bigint] NULL,
	[BodyTypeConfigId] [bigint] NULL,
	[TitleStateId] [bigint] NULL,
	[TitleCodeConfigId] [bigint] NULL,
	[ColourId] [bigint] NULL,
	[ColourTypeId] [bigint] NULL,
	[SuspensionId] [bigint] NULL,
	[FrontTyreSizeId] [bigint] NULL,
	[RearTyreSizeId] [bigint] NULL,
	[WheelId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
