CREATE TYPE [dbo].[VendorAccountHistoryReportTemplate] AS TABLE(
	[Name] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[Id] [bigint] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[CreatedTime] [datetimeoffset](7) NOT NULL,
	[UpdatedById] [bigint] NULL,
	[UpdatedTime] [datetimeoffset](7) NULL,
	[SequenceNumber] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[ContractFilterOption] [nvarchar](5) COLLATE Latin1_General_CI_AS NULL,
	[CommencementDate] [date] NULL,
	[CommencementDateOptions] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[FromCommencementDate] [date] NULL,
	[ToCommencementDate] [date] NULL,
	[CommencementUpThrough] [date] NULL,
	[CommencementRunDate] [int] NULL,
	[MaturityDateOptions] [nvarchar](17) COLLATE Latin1_General_CI_AS NULL,
	[MaturityTillXDaysFromRunDate] [int] NULL,
	[MaturityDate] [date] NULL,
	[FromMaturityDate] [date] NULL,
	[ToMaturityDate] [date] NULL,
	[MaturityTillDate] [date] NULL,
	[OrderBy] [nvarchar](21) COLLATE Latin1_General_CI_AS NOT NULL,
	[PaymentFrequency] [nvarchar](13) COLLATE Latin1_General_CI_AS NULL,
	[Term] [decimal](10, 6) NULL,
	[ContractCurrency] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[PaymentDate] [date] NULL,
	[DueDate] [date] NULL,
	[InvoiceNumber] [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
	[AmountDue_Amount] [decimal](16, 2) NULL,
	[AmountDue_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TaxAmount_Amount] [decimal](16, 2) NULL,
	[TaxAmount_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TaxAssessed_Amount] [decimal](16, 2) NULL,
	[TaxAssessed_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[AmountPaid_Amount] [decimal](16, 2) NULL,
	[AmountPaid_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TaxPaid_Amount] [decimal](16, 2) NULL,
	[TaxPaid_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[Balance_Amount] [decimal](16, 2) NULL,
	[Balance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[TaxBalance_Amount] [decimal](16, 2) NULL,
	[TaxBalance_Currency] [nvarchar](3) COLLATE Latin1_General_CI_AS NULL,
	[UserId] [bigint] NULL,
	[VendorId] [bigint] NULL,
	[CustomerId] [bigint] NULL,
	[FromSequenceNumberId] [bigint] NULL,
	[ToSequenceNumberId] [bigint] NULL,
	[ProgramVendorId] [bigint] NULL,
	[DealerOrDistributerId] [bigint] NULL,
	[Token] [int] NOT NULL,
	[RowVersion] [bigint] NULL
)
GO
