SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[AlterColumnStructure]
AS
BEGIN
SET ANSI_PADDING ON
DECLARE commands CURSOR FOR
SELECT 'ALTER TABLE [' + TABLES.TABLE_SCHEMA+'].['+TABLES.TABLE_NAME
+'] ALTER COLUMN ['+COLUMN_NAME+'] '+ DATA_TYPE +'('
+ CASE WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN 'MAX' ELSE CONVERT(nvarchar(5),CHARACTER_MAXIMUM_LENGTH) END +')'
+ CHAR(10)
+ CASE WHEN mc.is_masked = 1 THEN ' MASKED WITH (FUNCTION = ''' + mc.masking_function collate database_default +''')' ELSE '' END
+ CHAR(10)
+ CASE WHEN COLUMNS.IS_NULLABLE = 'NO' THEN 'NOT NULL'
ELSE 'NULL' END
+'; '
FROM
INFORMATION_SCHEMA.COLUMNS
INNER JOIN
INFORMATION_SCHEMA.TABLES
ON
COLUMNS.TABLE_NAME = TABLES.TABLE_NAME
LEFT JOIN sys.masked_columns mc ON  mc.name=COLUMNS.COLUMN_NAME and mc.object_id=OBJECT_ID(TABLES.TABLE_NAME)
WHERE
TABLE_TYPE ='BASE TABLE'
AND
DATA_TYPE IN ('CHAR','VARCHAR','VARBINARY','NVARCHAR')
DECLARE @cmd varchar(max)
OPEN commands
FETCH NEXT FROM commands INTO @cmd
WHILE @@FETCH_STATUS=0
BEGIN
EXEC(@cmd)
FETCH NEXT FROM commands INTO @cmd
END
CLOSE commands
DEALLOCATE commands
END

GO
