SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[CreateCopyForClosedPeriodLeaseIncomes]
(
@IncomeSchedules LeaseIncomesToClone READONLY,
@ModificationType NVARCHAR(50),
@ModificationId BIGINT,
@UserId BIGINT,
@ModificationTime DATETIMEOFFSET,
@IsNonAccrual BIT
)
AS
BEGIN
SET NOCOUNT ON
       DECLARE @OldIncomeScheduleId BIGINT;
       DECLARE @NewIncomeScheduleId BIGINT;

       DECLARE IncomeSchedulesCursor CURSOR LOCAL FOR (SELECT Id FROM @IncomeSchedules);

       OPEN IncomeSchedulesCursor;
       FETCH NEXT FROM IncomeSchedulesCursor INTO @OldIncomeScheduleId;
       WHILE @@FETCH_STATUS = 0
       BEGIN
              INSERT INTO LeaseIncomeSchedules
              (
                      IncomeDate,
                      IncomeType,
                      IsGLPosted,
                      AccountingTreatment,
                      IsAccounting,
                      IsSchedule,
                      LeaseModificationType,
                      LeaseModificationID,
                      IsLessorOwned,
                      IsNonAccrual,
                      BeginNetBookValue_Amount,
                      BeginNetBookValue_Currency,
                      EndNetBookValue_Amount,
                      EndNetBookValue_Currency,
                      OperatingBeginNetBookValue_Amount,
                      OperatingBeginNetBookValue_Currency,
                      OperatingEndNetBookValue_Amount,
                      OperatingEndNetBookValue_Currency,
                      Depreciation_Amount,
                      Depreciation_Currency,
                      Income_Amount,
                      Income_Currency,
                      IncomeAccrued_Amount,
                      IncomeAccrued_Currency,
                      IncomeBalance_Amount,
                      IncomeBalance_Currency,
                      RentalIncome_Amount,
                      RentalIncome_Currency,
                      DeferredRentalIncome_Amount,
                      DeferredRentalIncome_Currency,
                      ResidualIncome_Amount,
                      ResidualIncome_Currency,
                      ResidualIncomeBalance_Amount,
                      ResidualIncomeBalance_Currency,
                      Payment_Amount,
                      Payment_Currency,
                      FinanceIncome_Amount,
                      FinanceIncome_Currency,
                      FinanceResidualIncome_Amount,
                      FinanceResidualIncome_Currency,
                      FinanceBeginNetBookValue_Amount,
                      FinanceBeginNetBookValue_Currency,
                      FinanceEndNetBookValue_Amount,
                      FinanceEndNetBookValue_Currency,
                      FinanceIncomeAccrued_Amount,
                      FinanceIncomeAccrued_Currency,
                      FinanceIncomeBalance_Amount,
                      FinanceIncomeBalance_Currency,
                      FinanceRentalIncome_Amount,
                      FinanceRentalIncome_Currency,
                      FinanceDeferredRentalIncome_Amount,
                      FinanceDeferredRentalIncome_Currency,
                      FinanceResidualIncomeBalance_Amount,
                      FinanceResidualIncomeBalance_Currency,
                      FinancePayment_Amount,
                      FinancePayment_Currency,                  
                      DeferredSellingProfitIncome_Amount,
                      DeferredSellingProfitIncome_Currency,
                      DeferredSellingProfitIncomeBalance_Amount,
                      DeferredSellingProfitIncomeBalance_Currency,
                      AdjustmentEntry,
                      CreatedById,
                      CreatedTime,
                      LeaseFinanceId,
                      IsReclassOTP
              )
              SELECT 
              IncomeDate, 
              IncomeType, 
              0, 
              AccountingTreatment,
              0, 
              1,
              @ModificationType,
              @ModificationId,
              IsLessorOwned,
              @IsNonAccrual,
              BeginNetBookValue_Amount,
              BeginNetBookValue_Currency,
              EndNetBookValue_Amount,
              EndNetBookValue_Currency,
              OperatingBeginNetBookValue_Amount,
              OperatingBeginNetBookValue_Currency,
              OperatingEndNetBookValue_Amount,
              OperatingEndNetBookValue_Currency,
              Depreciation_Amount, 
              Depreciation_Currency,
              Income_Amount,
              Income_Currency,
              IncomeAccrued_Amount,
              IncomeAccrued_Currency,
              IncomeBalance_Amount,
              IncomeBalance_Currency,
              RentalIncome_Amount, 
              RentalIncome_Currency, 
              DeferredRentalIncome_Amount, 
              DeferredRentalIncome_Currency, 
              ResidualIncome_Amount, 
              ResidualIncome_Currency, 
              ResidualIncomeBalance_Amount,
              ResidualIncomeBalance_Currency,
              Payment_Amount,
              Payment_Currency,
              FinanceIncome_Amount,              
              FinanceIncome_Currency,
              FinanceResidualIncome_Amount,
              FinanceResidualIncome_Currency,
              FinanceBeginNetBookValue_Amount,
              FinanceBeginNetBookValue_Currency,
              FinanceEndNetBookValue_Amount,
              FinanceEndNetBookValue_Currency,
              FinanceIncomeAccrued_Amount,
              FinanceIncomeAccrued_Currency,
              FinanceIncomeBalance_Amount,
              FinanceIncomeBalance_Currency,
              FinanceRentalIncome_Amount,
              FinanceRentalIncome_Currency,
              FinanceDeferredRentalIncome_Amount,
              FinanceDeferredRentalIncome_Currency,
              FinanceResidualIncomeBalance_Amount,
              FinanceResidualIncomeBalance_Currency,
              FinancePayment_Amount,
              FinancePayment_Currency,                  
              DeferredSellingProfitIncome_Amount,
              DeferredSellingProfitIncome_Currency,
              DeferredSellingProfitIncomeBalance_Amount,
              DeferredSellingProfitIncomeBalance_Currency,
              0,
              @UserId,
              @ModificationTime,
              LeaseFinanceId,
              IsReclassOTP
              FROM LeaseIncomeSchedules WHERE Id = @OldIncomeScheduleId;

              SET @NewIncomeScheduleId = SCOPE_IDENTITY();

              INSERT INTO AssetIncomeSchedules
              (
                      BeginNetBookValue_Amount,      
                      BeginNetBookValue_Currency,
                      LeaseBeginNetBookValue_Amount,
                      LeaseBeginNetBookValue_Currency,
                      FinanceBeginNetBookValue_Amount,
                      FinanceBeginNetBookValue_Currency,
                      EndNetBookValue_Amount, 
                      EndNetBookValue_Currency,
                      LeaseEndNetBookValue_Amount,
                      LeaseEndNetBookValue_Currency,
                      FinanceEndNetBookValue_Amount,
                      FinanceEndNetBookValue_Currency,
                      Income_Amount, 
                      Income_Currency, 
                      LeaseIncome_Amount,
                      LeaseIncome_Currency,
                      FinanceIncome_Amount,
                      FinanceIncome_Currency,
                      IncomeAccrued_Amount, 
                      IncomeAccrued_Currency, 
                      LeaseIncomeAccrued_Amount,
                      LeaseIncomeAccrued_Currency,
                      FinanceIncomeAccrued_Amount,
                      FinanceIncomeAccrued_Currency,
                      IncomeBalance_Amount, 
                      IncomeBalance_Currency, 
                      LeaseIncomeBalance_Amount,
                      LeaseIncomeBalance_Currency,
                      FinanceIncomeBalance_Amount,
                      FinanceIncomeBalance_Currency,
                      ResidualIncome_Amount,
                      ResidualIncome_Currency,
                      LeaseResidualIncome_Amount,
                      LeaseResidualIncome_Currency,
                      FinanceResidualIncome_Amount,
                      FinanceResidualIncome_Currency,
                      ResidualIncomeBalance_Amount, 
                      ResidualIncomeBalance_Currency, 
                      LeaseResidualIncomeBalance_Amount,
                      LeaseResidualIncomeBalance_Currency,
                      FinanceResidualIncomeBalance_Amount,
                      FinanceResidualIncomeBalance_Currency,
                      OperatingBeginNetBookValue_Amount,
                      OperatingBeginNetBookValue_Currency,
                      OperatingEndNetBookValue_Amount,
                      OperatingEndNetBookValue_Currency,
                      RentalIncome_Amount,
                      RentalIncome_Currency,
                      LeaseRentalIncome_Amount,
                      LeaseRentalIncome_Currency,
                      FinanceRentalIncome_Amount,
                      FinanceRentalIncome_Currency,
                      DeferredRentalIncome_Amount,
                      DeferredRentalIncome_Currency,
                      LeaseDeferredRentalIncome_Amount,
                      LeaseDeferredRentalIncome_Currency,
                      FinanceDeferredRentalIncome_Amount,
                      FinanceDeferredRentalIncome_Currency,
                      Depreciation_Amount,
                      Depreciation_Currency,
                      Payment_Amount,
                      Payment_Currency,
                      LeasePayment_Amount,
                      LeasePayment_Currency,
                      FinancePayment_Amount,
                      FinancePayment_Currency,
                      DeferredSellingProfitIncome_Amount,
                      DeferredSellingProfitIncome_Currency,
                      DeferredSellingProfitIncomeBalance_Amount,
                      DeferredSellingProfitIncomeBalance_Currency,
                      IsActive,
                      CreatedById,
                      CreatedTime,
                      AssetId,
                      LeaseIncomeScheduleId
              )
              SELECT 
              BeginNetBookValue_Amount,      
              BeginNetBookValue_Currency,
              LeaseBeginNetBookValue_Amount,
              LeaseBeginNetBookValue_Currency,
              FinanceBeginNetBookValue_Amount,
              FinanceBeginNetBookValue_Currency,
              EndNetBookValue_Amount, 
              EndNetBookValue_Currency,
              LeaseEndNetBookValue_Amount,
              LeaseEndNetBookValue_Currency,
              FinanceEndNetBookValue_Amount,
              FinanceEndNetBookValue_Currency,
              Income_Amount, 
              Income_Currency, 
              LeaseIncome_Amount,
              LeaseIncome_Currency,
              FinanceIncome_Amount,
              FinanceIncome_Currency,
              IncomeAccrued_Amount, 
              IncomeAccrued_Currency, 
              LeaseIncomeAccrued_Amount,
              LeaseIncomeAccrued_Currency,
              FinanceIncomeAccrued_Amount,
              FinanceIncomeAccrued_Currency,
              IncomeBalance_Amount, 
              IncomeBalance_Currency, 
              LeaseIncomeBalance_Amount,
              LeaseIncomeBalance_Currency,
              FinanceIncomeBalance_Amount,
              FinanceIncomeBalance_Currency,
              ResidualIncome_Amount,
              ResidualIncome_Currency,
              LeaseResidualIncome_Amount,
              LeaseResidualIncome_Currency,
              FinanceResidualIncome_Amount,
              FinanceResidualIncome_Currency,
              ResidualIncomeBalance_Amount, 
              ResidualIncomeBalance_Currency, 
              LeaseResidualIncomeBalance_Amount,
              LeaseResidualIncomeBalance_Currency,
              FinanceResidualIncomeBalance_Amount,
              FinanceResidualIncomeBalance_Currency,
              OperatingBeginNetBookValue_Amount,
              OperatingBeginNetBookValue_Currency,
              OperatingEndNetBookValue_Amount,
              OperatingEndNetBookValue_Currency,
              RentalIncome_Amount,
              RentalIncome_Currency,
              LeaseRentalIncome_Amount,
              LeaseRentalIncome_Currency,
              FinanceRentalIncome_Amount,
              FinanceRentalIncome_Currency,
              DeferredRentalIncome_Amount,
              DeferredRentalIncome_Currency,
              LeaseDeferredRentalIncome_Amount,
              LeaseDeferredRentalIncome_Currency,
              FinanceDeferredRentalIncome_Amount,
              FinanceDeferredRentalIncome_Currency,
              Depreciation_Amount,
              Depreciation_Currency,
              Payment_Amount,
              Payment_Currency,
              LeasePayment_Amount,
              LeasePayment_Currency,
              FinancePayment_Amount,
              FinancePayment_Currency,
              DeferredSellingProfitIncome_Amount,
              DeferredSellingProfitIncome_Currency,
              DeferredSellingProfitIncomeBalance_Amount,
              DeferredSellingProfitIncomeBalance_Currency,
              1,
              @UserId,
              @ModificationTime,
              AssetId,
              @NewIncomeScheduleId
              FROM AssetIncomeSchedules 
              WHERE LeaseIncomeScheduleId = @OldIncomeScheduleId AND AssetIncomeSchedules.IsActive=1;
              
              FETCH NEXT FROM IncomeSchedulesCursor INTO @OldIncomeScheduleId;
       END

       CLOSE IncomeSchedulesCursor;
       DEALLOCATE IncomeSchedulesCursor;

       UPDATE AIS SET IsActive = 0, UpdatedById = @UserId, UpdatedTime = @ModificationTime  
       FROM AssetIncomeSchedules AIS
       JOIN @IncomeSchedules Insch ON AIS.LeaseIncomeScheduleId = Insch.Id;
              
       UPDATE LIS SET IsSchedule = 0, UpdatedById = @UserId, UpdatedTime = @ModificationTime   
       FROM LeaseIncomeSchedules LIS
       JOIN @IncomeSchedules Insch ON LIS.Id = Insch.Id;      
END

GO
