SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CreateLeaseAssetIncomeAmort]
(
@AssetIncomeAmorts AssetIncomeAmortTVP READONLY,
@CreatedById BIGINT,
@CreatedTime DATETIMEOFFSET(7),
@IsMigrationCall BIT = 0
)
AS
SET NOCOUNT ON;
BEGIN
DECLARE @SQL NVARCHAR(MAX) = '';
SET @SQL = @SQL + N'
    INSERT INTO AssetIncomeSchedules (
	BeginNetBookValue_Amount,
	BeginNetBookValue_Currency,
	EndNetBookValue_Amount,
	EndNetBookValue_Currency,
	Income_Amount,
	Income_Currency,
	IncomeAccrued_Amount,
	IncomeAccrued_Currency,
	IncomeBalance_Amount,
	IncomeBalance_Currency,
	ResidualIncome_Amount,
	ResidualIncome_Currency,
	ResidualIncomeBalance_Amount,
	ResidualIncomeBalance_Currency,
	OperatingBeginNetBookValue_Amount,
	OperatingBeginNetBookValue_Currency,
	OperatingEndNetBookValue_Amount,
	OperatingEndNetBookValue_Currency,
	Depreciation_Amount,
	Depreciation_Currency,
	RentalIncome_Amount,
	RentalIncome_Currency,
	DeferredRentalIncome_Amount,
	DeferredRentalIncome_Currency,
	Payment_Amount,
	Payment_Currency,
	DeferredSellingProfitIncome_Amount,
	DeferredSellingProfitIncome_Currency,
	DeferredSellingProfitIncomeBalance_Amount,
	DeferredSellingProfitIncomeBalance_Currency,
	IsActive,
	CreatedById,
	CreatedTime,
	AssetId,
	LeaseIncomeScheduleId,
	FinanceBeginNetBookValue_Amount,
    FinanceBeginNetBookValue_Currency,
    FinanceEndNetBookValue_Amount,
    FinanceEndNetBookValue_Currency,
    FinancePayment_Amount,
    FinancePayment_Currency,
    FinanceIncome_Amount,
    FinanceIncome_Currency,
    FinanceIncomeAccrued_Amount,
    FinanceIncomeAccrued_Currency,
    FinanceIncomeBalance_Amount,
    FinanceIncomeBalance_Currency,
    FinanceResidualIncome_Amount,
    FinanceResidualIncome_Currency,
    FinanceResidualIncomeBalance_Amount,
    FinanceResidualIncomeBalance_Currency,
    FinanceRentalIncome_Amount,
    FinanceRentalIncome_Currency,
    FinanceDeferredRentalIncome_Amount,
    FinanceDeferredRentalIncome_Currency,
	LeaseBeginNetBookValue_Amount,
	LeaseBeginNetBookValue_Currency,
    LeaseEndNetBookValue_Amount,
    LeaseEndNetBookValue_Currency,
    LeasePayment_Amount,
    LeasePayment_Currency,
    LeaseIncome_Amount,
    LeaseIncome_Currency,
    LeaseIncomeAccrued_Amount,
    LeaseIncomeAccrued_Currency,
    LeaseIncomeBalance_Amount,
    LeaseIncomeBalance_Currency,
    LeaseResidualIncome_Amount,
    LeaseResidualIncome_Currency,
    LeaseResidualIncomeBalance_Amount,
    LeaseResidualIncomeBalance_Currency,
    LeaseRentalIncome_Amount,
    LeaseRentalIncome_Currency,
    LeaseDeferredRentalIncome_Amount,
    LeaseDeferredRentalIncome_Currency
)
SELECT 
	AIA.BeginNBV,
	AIA.Currency,
	AIA.EndNBV,
	AIA.Currency,
	AIA.Income,
	AIA.Currency,
	AIA.IncomeAccrued,
	AIA.Currency,
	AIA.IncomeBalance,
	AIA.Currency,
	AIA.ResidualIncome,
	AIA.Currency, 
	AIA.ResidualIncomeBalance,
	AIA.Currency,
	AIA.OperatingBeginNBV,
	AIA.Currency,
	AIA.OperatingEndNBV,
	AIA.Currency,
	AIA.Depreciation,
	AIA.Currency,
	AIA.RentalIncome,
	AIA.Currency,
	AIA.DeferredRentalIncome,
	AIA.Currency,
	AIA.Payment,
	AIA.Currency,
	AIA.DSPIncome,
	AIA.Currency,
	AIA.DSPIncomeBalance,
	AIA.Currency,
	1,
	@CreatedById, 
	@CreatedTime,
	AIA.AssetId,
	AIA.LeaseIncomeKey,
	AIA.FinanceBeginNBV,
    AIA.Currency,
    AIA.FinanceEndNBV,
    AIA.Currency,
    AIA.FinancePayment,
    AIA.Currency,
    AIA.FinanceIncome,
    AIA.Currency,
    AIA.FinanceIncomeAccrued,
    AIA.Currency,
    AIA.FinanceIncomeBalance,
    AIA.Currency,
    AIA.FinanceResidualIncome,
    AIA.Currency,
    AIA.FinanceResidualIncomeBalance,
    AIA.Currency,
    AIA.FinanceRentalIncome,
    AIA.Currency,
    AIA.FinanceDeferredRentalIncome,
    AIA.Currency,
	AIA.LeaseBeginNBV,
    AIA.Currency,
    AIA.LeaseEndNBV,
    AIA.Currency,
    AIA.LeasePayment,
    AIA.Currency,
    AIA.LeaseIncome,
    AIA.Currency,
    AIA.LeaseIncomeAccrued,
    AIA.Currency,
    AIA.LeaseIncomeBalance,
    AIA.Currency,
    AIA.LeaseResidualIncome,
    AIA.Currency,
    AIA.LeaseResidualIncomeBalance,
    AIA.Currency,
    AIA.LeaseRentalIncome,
    AIA.Currency,
    AIA.LeaseDeferredRentalIncome,
    AIA.Currency FROM @AssetIncomeAmorts AIA'

IF (@IsMigrationCall = 1)
BEGIN
SET @SQL = @SQL + ' OPTION (LOOP JOIN)'
END

EXECUTE sp_executesql @sql , 
N'
@CreatedById BIGINT , 
@CreatedTime DATETIMEOFFSET , 
@AssetIncomeAmorts AssetIncomeAmortTVP READONLY', 
@CreatedById = @CreatedById,  
@CreatedTime = @CreatedTime , 
@AssetIncomeAmorts = @AssetIncomeAmorts
END

GO
