SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[InsertRemainingNetInvestment]
(
@ExtractedRemainingNetInvestment ExtractedRemainingNetInvestment READONLY,
@RemainingNetInvestmentsIds RemainingNetInvestmentsIds READONLY,
@CreatedById BIGINT,
@CreatedTime DATETIMEOFFSET
)
AS
BEGIN
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

IF EXISTS (SELECT 1 FROM @RemainingNetInvestmentsIds)
BEGIN
Update RemainingNetInvestments SET IsActive = 0, UpdatedById = @CreatedById, UpdatedTime = @CreatedTime
FROM @RemainingNetInvestmentsIds Contract
JOIN RemainingNetInvestments RNI ON Contract.Id = RNI.Id
;
END

INSERT INTO [dbo].[RemainingNetInvestments]
					(IncomeDate,
					ContractType,
					SubType,
					IsOTP,
					IsInNonAccrual,
					NonAccrualDate,
					IsActive,
					Status,
					HoldingStatus,
					RetainedPercentage,
					IsPaymentStreamSold,
					RNIAmount_Amount,
					RNIAmount_Currency,
					ServicedRNIAmount,
					PrincipalBalance,
					DelayedFundingPayables,
					LoanPrincipleOSAR,
					LoanInterestOSAR,
					InterimInterestOSAR,
					IncomeAccrualBalance,
					SuspendedIncomeAccrualBalance,
					ProgressFundings,
					ProgressPaymentCredits,
					TotalFinancedAmount,
					TotalFinancedAmountLOC,
					UnappliedCash,
					GrossWritedowns,
					NetWritedowns,
					IDCBalance,
					SuspendedIDCBalance,
					FAS91ExpenseBalance,
					FAS91IncomeBalance,
					SuspendedFAS91ExpenseBalance,
					SuspendedFAS91IncomeBalance,
					OperatingLeaseAssetGrossCost,
					AccumulatedDepreciation,
					OperatingLeaseRentOSAR,
					InterimRentOSAR,
					DeferredOperatingIncome,
					DeferredExtensionIncome,
					CapitalLeaseContractReceivable,
					UnguaranteedResidual,
					CustomerGuaranteedResidual,
					ThirdPartyGauranteedResidual,
					CapitalLeaseRentOSAR,
					OverTermRentOSAR,
					UnearnedRentalIncome,
					OTPResidualRecapture,
					PrepaidReceivables,
					SyndicatedPrepaidReceivables,
					AccumulatedNBVImpairment,
					FloatRateAdjustmentOSAR,
					FloatRateIncomeBalance,
					SuspendedFloatRateIncomeBalance,
					HeldForSaleValuationAllowance,
					HeldForSaleBalance,
					SyndicatedFixedTermReceivablesOSAR,
					SyndicatedInterimReceivablesOSAR,
					SecurityDeposit,
					SecurityDepositOSAR,
					VendorSubsidyOSAR,
					DelayedVendorSubsidy,
					SalesTaxOSAR,
					SyndicatedSalesTaxOSAR,
					PrincipalBalanceAdjustment,
					CreatedById,
					CreatedTime,
					ContractId,
					InstrumentTypeId,
					CreditProfileId,
					CurrencyId,
					SyndicatedCapitalLeaseContractReceivable,
					IncomeAccrualBalanceFunderPortion,
					PrincipalBalanceFunderPortion,
					PrepaidInterest,
					AccountingStandard,
					FinanceIncomeAccrualBalance,
					SuspendedFinanceIncomeAccrualBalance,
					SyndicatedFinanceIncomeAccrualBalance,
					DeferredSellingProfit,
					SuspendedDeferredSellingProfit,
					FinanceGrossWritedowns,
					FinanceNetWritedowns,
					FinancingContractReceivable,
					SyndicatedFinancingContractReceivable,
					FinanceUnguaranteedResidual,
					FinanceCustomerGuaranteedResidual,
					FinanceThirdPartyGauranteedResidual,
					FinancingRentOSAR,
					FinanceSyndicatedFixedTermReceivablesOSAR,
					BackgroundProcessingPending)

					SELECT 
					IncomeDate,
					ContractType,
					SubType,
					IsOTP,
					IsInNonAccrual,
					NonAccrualDate,
					IsActive,
					Status,
					HoldingStatus,
					RetainedPercentage,
					IsPaymentStreamSold,
					RNIAmount_Amount,
					RNIAmount_Currency,
					ServicedRNIAmount,
					PrincipalBalance,
					DelayedFundingPayables,
					LoanPrincipleOSAR,
					LoanInterestOSAR,
					InterimInterestOSAR,
					IncomeAccrualBalance,
					SuspendedIncomeAccrualBalance,
					ProgressFundings,
					ProgressPaymentCredits,
					TotalFinancedAmount,
					TotalFinancedAmountLOC,
					UnappliedCash,
					GrossWritedowns,
					NetWritedowns,
					IDCBalance,
					SuspendedIDCBalance,
					FAS91ExpenseBalance,
					FAS91IncomeBalance,
					SuspendedFAS91ExpenseBalance,
					SuspendedFAS91IncomeBalance,
					OperatingLeaseAssetGrossCost,
					AccumulatedDepreciation,
					OperatingLeaseRentOSAR,
					InterimRentOSAR,
					DeferredOperatingIncome,
					DeferredExtensionIncome,
					CapitalLeaseContractReceivable,
					UnguaranteedResidual,
					CustomerGuaranteedResidual,
					ThirdPartyGauranteedResidual,
					CapitalLeaseRentOSAR,
					OverTermRentOSAR,
					UnearnedRentalIncome,
					OTPResidualRecapture,
					PrepaidReceivables,
					SyndicatedPrepaidReceivables,
					AccumulatedNBVImpairment,
					FloatRateAdjustmentOSAR,
					FloatRateIncomeBalance,
					SuspendedFloatRateIncomeBalance,
					HeldForSaleValuationAllowance,
					HeldForSaleBalance,
					SyndicatedFixedTermReceivablesOSAR,
					SyndicatedInterimReceivablesOSAR,
					SecurityDeposit,
					SecurityDepositOSAR,
					VendorSubsidyOSAR,
					DelayedVendorSubsidy,
					SalesTaxOSAR,
					SyndicatedSalesTaxOSAR,
					PrincipalBalanceAdjustment,
					@CreatedById,
					@CreatedTime,
					ContractId,
					InstrumentTypeId,
					CreditProfileId,
					CurrencyId,
					SyndicatedCapitalLeaseContractReceivable,
					IncomeAccrualBalanceFunderPortion,
					PrincipalBalanceFunderPortion,
					PrepaidInterest,
					AccountingStandard,
					FinanceIncomeAccrualBalance,
					SuspendedFinanceIncomeAccrualBalance,
					SyndicatedFinanceIncomeAccrualBalance,
					DeferredSellingProfit,
					SuspendedDeferredSellingProfit,
					FinanceGrossWritedowns,
					FinanceNetWritedowns,
					FinancingContractReceivable,
					SyndicatedFinancingContractReceivable,
					FinanceUnguaranteedResidual,
					FinanceCustomerGuaranteedResidual,
					FinanceThirdPartyGauranteedResidual,
					FinancingRentOSAR,
					FinanceSyndicatedFixedTermReceivablesOSAR,
					BackgroundProcessingPending
			FROM @ExtractedRemainingNetInvestment;	
	
	SET NOCOUNT OFF;
END

GO
