SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[InsertAmendmentEntryFromPayoff]
(
@OriginalLeaseFinanceId BIGINT,
@PayoffName NVARCHAR(30),
@CurrentLeaseFinanceId BIGINT,
@ContractAmendmentValuesPayoffType NVARCHAR(30),
@ContractAmendmentStatusValuesApprovedType NVARCHAR(50),
@PayoffEffectiveDate DATETIME,
@PayoffAtInception BIT,
@ReceivableAmendmentType NVARCHAR(60),
@LeasePaymentScheduleId BIGINT = NULL,
@CreatedById BIGINT,
@CreatedTime DATETIMEOFFSET,
@CurrencyCode NVARCHAR(3),
@SalesTaxRemittanceMethod NVARCHAR(30),
@AccountingDate DATETIME,
@CreateCPURestructure BIT
)
AS
BEGIN
SET NOCOUNT ON
INSERT INTO LeaseAmendments (
Name,
LeaseAmendmentStatus,
ReceivableAmendmentType,
AmendmentDate,
AmendmentType,
AmendmentAtInception,
CreatedById,
CreatedTime,
CurrentLeaseFinanceId,
OriginalLeaseFinanceId,
LeasePaymentScheduleId,
HSTTaxPaidtoVendor_Amount,
HSTTaxPaidtoVendor_Currency,
QSTorPSTTaxPaidtoVendor_Amount,
QSTorPSTTaxPaidtoVendor_Currency,
IsTDR,
IsLienFilingException,
IsLienFilingRequired,
TDRReason,
PreRestructureLeaseNBV_Amount,
PreRestructureLeaseNBV_Currency,
PostRestructureLeaseNBV_Amount,
PostRestructureLeaseNBV_Currency,
PreRestructureResidualBooked_Amount,
PreRestructureResidualBooked_Currency,
PostRestructureResidualBooked_Amount,
PostRestructureResidualBooked_Currency,
PreRestructureFAS91Balance_Amount,
PreRestructureFAS91Balance_Currency,
PostRestructureFAS91Balance_Amount,
PostRestructureFAS91Balance_Currency,
NetWritedowns_Amount,
NetWritedowns_Currency,
AccountingDate,
PostDate,
ImpairmentAmount_Amount,
ImpairmentAmount_Currency,
IsLeaseLevelImpairment,
GLTemplateId,
AccumulatedImpairmentAmount_Amount,
AccumulatedImpairmentAmount_Currency,
PreRestructureUnguaranteedResidual_Amount,
PreRestructureUnguaranteedResidual_Currency,
PostRestructureUnguaranteedResidual_Amount,
PostRestructureUnguaranteedResidual_Currency,
PreRestructureClassificationYield,
PreRestructureLessorYield,
TaxPaidtoVendor_Amount,
TaxPaidtoVendor_Currency,
GSTTaxPaidtoVendor_Amount,
GSTTaxPaidtoVendor_Currency,
SalesTaxRemittanceMethod,
LienExceptionReason,
PreRestructureLessorYieldLeaseAsset,
PreRestructureLessorYieldFinanceAsset,
PreRestructureClassificationYield5A,
PreRestructureClassificationYield5B,
FloatRateRestructure,
CreateCPURestructure
)
VALUES
(
@PayoffName,
@ContractAmendmentStatusValuesApprovedType,
@ReceivableAmendmentType,
@PayoffEffectiveDate,
@ContractAmendmentValuesPayoffType,
@PayoffAtInception,
@CreatedById,
@CreatedTime,
@CurrentLeaseFinanceId,
@OriginalLeaseFinanceId,
@LeasePaymentScheduleId,
0.00,
@CurrencyCode,
0.00,
@CurrencyCode,
CAST (0 AS BIT),
CAST (0 AS BIT),
CAST (0 AS BIT),
'_',
0.0,
@CurrencyCode,
0.0,
@CurrencyCode,
0.0,
@CurrencyCode,
0.0,
@CurrencyCode,
0.0,
@CurrencyCode,
0.0,
@CurrencyCode,
0.0,
@CurrencyCode,
@AccountingDate,
NULL,
0.0,
@CurrencyCode,
CAST(0 AS BIT),
NULL,
0.0,
@CurrencyCode,
0.0,
@CurrencyCode,
0.0,
@CurrencyCode,
0.0,
0.0,
0.00,
@CurrencyCode,
0.00,
@CurrencyCode,
@SalesTaxRemittanceMethod,
'_',
0,
0,
0,
0,
0,
@CreateCPURestructure
)
END

GO
