SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[InsertReceivableDetailsForSalesTaxReversalProcess]  
(  
@CTEntityType NVARCHAR(5),  
@CUEntityType NVARCHAR(5),  
@DTEntityType NVARCHAR(5),  
@UnknownTaxExemptionType NVARCHAR(20),  
@NewChunkStatus NVARCHAR(40),  
@ReceivableExists BIT = 0 OUTPUT,  
@JobStepInstanceId BIGINT  
)  
AS  
BEGIN  
SET NOCOUNT ON;  
  
  
INSERT INTO ReceivableDetailsForReversalProcess_Extract (ChunkStatus,ReceivableTaxId,ReceivableTaxDetailId, IsCashPosted, ReceivableDetailId, Currency, TaxAreaId, Cost, ExtendedPrice, FairMarketValue, TaxBasisType,  
AssetId, LocationId, DueDate, ReceivableId, ReceivableCodeId, IsInvoiced, IsExemptAtLease, IsExemptAtAsset, IsExemptAtSundry, Company, Product,   
ContractType, LeaseType, LeaseTerm, TitleTransferCode, TransactionCode, AmountBilledToDate, AssetLocationId, ToState, FromState, SundryReceivableCode,   
IsExemptAtReceivableCode, TransactionType, ReceivableType, IsRental, CustomerId, ContractId, LegalEntityId, EntityType, CountryTaxExempt, StateTaxExempt, CityTaxExempt, CountyTaxExempt,   
CountryTaxExemptRule, StateTaxExemptRule, CityTaxExemptRule, CountyTaxExemptRule, Country, MainDivision, StateId, City, LocationCode, IsVertexSupportedLocation,   
ClassCode, CustomerNumber, TaxRegistrationNumber, ISOCountryCode, PartyName, GrossVehicleWeight, AssetType, SaleLeasebackCode, IsElectronicallyDelivered,   
TaxRemittanceType, SalesTaxExemptionLevel, IsSyndicated, AssetCatalogNumber, AssetTypeId, LeaseUniqueId, ContractTypeValue, LocationEffectiveDate, LienCredit, ReciprocityAmount,  
ReceivableTaxDetailRowVersion,ReceivableTaxRowVersion,ReceivableDetailRowVersion,AssetLocationRowVersion,CreatedById, CreatedTime, JobStepInstanceId  
,Usage, IsTaxExempt,UpfrontTaxSundryId,AcquisitionLocationTaxAreaId,AcquisitionLocationCity,AcquisitionLocationMainDivision,AcquisitionLocationCountry,CommencementDate,MaturityDate,
SalesTaxRemittanceResponsibility,AssetUsageCondition,AssetSerialOrVIN,IsSKU,AssetSKUId,IsExemptAtAssetSKU, UpfrontTaxAssessedInLegacySystem, BusCode)  
SELECT   
 @NewChunkStatus AS ChunkStatus,  
 RI.ReceivableTaxId,   
 RI.ReceivableTaxDetailId,  
 RI.IsCashPosted,   
 RI.ReceivableDetailId,   
 RI.Currency,   
 RI.TaxAreaId,   
 RI.Cost,   
 RI.ExtendedPrice,   
 RI.FairMarketValue,   
 RI.TaxBasisType,  
 RI.AssetId,   
 RI.LocationId,   
 RI.DueDate,   
 RI.ReceivableId,   
 RI.ReceivableCodeId,   
 RI.IsInvoiced,   
 RI.IsExemptAtLease,   
 RI.IsExemptAtAsset,   
 RI.IsExemptAtSundry,   
 RI.Company,   
 RI.Product,   
 RI.ContractType,   
 RI.LeaseType,   
 RI.LeaseTerm,   
 RI.TitleTransferCode,   
 RI.TransactionCode,   
 RI.AmountBilledToDate,   
 RI.AssetLocationId,   
 RI.ToState,   
 RI.FromState,   
 RI.SundryReceivableCode,   
 RI.IsExemptAtReceivableCode,   
 RI.TransactionType,   
 RI.ReceivableType,   
 RI.IsRental,   
 RI.CustomerId,   
 RI.ContractId,   
 RI.LegalEntityId,   
 RI.EntityType,  
 TED.CountryTaxExempt,   
 TED.StateTaxExempt,   
 TED.CityTaxExempt,   
 TED.CountyTaxExempt,   
 TED.CountryTaxExemptRule,   
 TED.StateTaxExemptRule,   
 TED.CityTaxExemptRule,   
 TED.CountyTaxExemptRule,   
 LI.Country,   
 LI.MainDivision,   
 LI.StateId,   
 LI.City,   
 LI.LocationCode,  
 LI.IsVertexSupportedLocation,   
 Customer.ClassCode,   
 Customer.CustomerNumber,   
 Customer.TaxRegistrationNumber,  
 Customer.ISOCountryCode,  
 Customer.PartyName,  
 AF.GrossVehicleWeight,   
 RI.AssetType,   
 AF.SaleLeasebackCode,   
 ISNULL(AF.IsElectronicallyDelivered,CONVERT(BIT,0)) AS IsElectronicallyDelivered,   
 Contract.TaxRemittanceType,   
 AF.SalesTaxExemptionLevel,   
 ISNULL(Contract.IsSyndicated,CONVERT(BIT,0)) AS IsSyndicated,   
 AF.AssetCatalogNumber,  
 AF.AssetTypeId,   
 Contract.LeaseUniqueId,  
 Contract.ContractTypeValue,   
 AL.LocationEffectiveDate,   
 ISNULL(AL.LienCredit,0),   
 ISNULL(AL.ReciprocityAmount,0),  
 RI.ReceivableTaxDetailRowVersion,  
 RI.ReceivableTaxRowVersion,  
 RI.ReceivableDetailRowVersion,  
 RI.AssetLocationRowVersion,  
 1,  
 SYSDATETIMEOFFSET(),  
 @JobStepInstanceId,  
 AF.Usage,  
 CAST(0 AS BIT) AS IsTaxExempt,  
 RI.UpfrontTaxSundryId,  
 AcquisitionLocationDetail.AcquisitionLocationTaxAreaId,  
 AcquisitionLocationDetail.City,  
 AcquisitionLocationDetail.MainDivision,  
 AcquisitionLocationDetail.Country,
 Contract.CommencementDate AS CommencementDate,
 Contract.MaturityDate AS MaturityDate, 
 ISNULL(RI.SalesTaxRemittanceResponsibility,'_') AS SalesTaxRemittanceResponsibility,
 ISNULL(AF.AssetUsageCondition,'_') AS AssetUsageCondition,
 AF.AssetSerialOrVIN,
 ISNULL(AF.IsSKU,0) AS IsSKU,
 AF.AssetSKUId,
 0,
 RI.UpfrontTaxAssessedInLegacySystem,
 RI.BusCode
FROM ReversalReceivableDetail_Extract RI  
INNER JOIN ReversalCustomerDetail_Extract Customer ON RI.CustomerId = Customer.CustomerId AND Customer.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalContractDetail_Extract Contract ON RI.ContractId = Contract.ContractId AND Contract.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalLocationDetail_Extract LI ON RI.LocationId = LI.LocationId AND LI.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalTaxExemptDetail_Extract TED ON RI.ReceivableDetailId = TED.ReceivableDetailId AND (RI.AssetId = TED.AssetId OR RI.AssetId IS NULL) AND TED.JobStepInstanceId = @JobStepInstanceId  
LEFT JOIN ReversalFlexFieldDetail_Extract AF ON AF.AssetId = RI.AssetId AND AF.JobStepInstanceId = @JobStepInstanceId  
LEFT JOIN ReversalAssetLocationDetail_Extract AL ON RI.AssetLocationId = AL.AssetLocationId AND AL.JobStepInstanceId = @JobStepInstanceId  
LEFT JOIN ReversalLocationDetail_Extract AcquisitionLocationDetail ON RI.AcquisitionLocationId = AcquisitionLocationDetail.LocationId AND AcquisitionLocationDetail.JobStepInstanceId = @JobStepInstanceId  
WHERE RI.EntityType = @CTEntityType AND ErrorCode IS NULL AND RI.JobStepInstanceId = @JobStepInstanceId AND (AF.IsSKU = 0 OR RI.IsRental = 0)
;  




INSERT INTO ReceivableDetailsForReversalProcess_Extract (ChunkStatus,ReceivableTaxId,ReceivableTaxDetailId, IsCashPosted, ReceivableDetailId, Currency, TaxAreaId, Cost, ExtendedPrice, FairMarketValue, TaxBasisType,  
AssetId, LocationId, DueDate, ReceivableId, ReceivableCodeId, IsInvoiced, IsExemptAtLease, IsExemptAtAsset, IsExemptAtSundry, Company, Product,   
ContractType, LeaseType, LeaseTerm, TitleTransferCode, TransactionCode, AmountBilledToDate, AssetLocationId, ToState, FromState, SundryReceivableCode,   
IsExemptAtReceivableCode, TransactionType, ReceivableType, IsRental, CustomerId, ContractId, LegalEntityId, EntityType, CountryTaxExempt, StateTaxExempt, CityTaxExempt, CountyTaxExempt,   
CountryTaxExemptRule, StateTaxExemptRule, CityTaxExemptRule, CountyTaxExemptRule, Country, MainDivision, StateId, City, LocationCode, IsVertexSupportedLocation,   
ClassCode, CustomerNumber, TaxRegistrationNumber, ISOCountryCode, PartyName, GrossVehicleWeight, AssetType, SaleLeasebackCode, IsElectronicallyDelivered,   
TaxRemittanceType, SalesTaxExemptionLevel, IsSyndicated, AssetCatalogNumber, AssetTypeId, LeaseUniqueId, ContractTypeValue, LocationEffectiveDate, LienCredit, ReciprocityAmount,  
ReceivableTaxDetailRowVersion,ReceivableTaxRowVersion,ReceivableDetailRowVersion,AssetLocationRowVersion,CreatedById, CreatedTime, JobStepInstanceId  
,Usage, IsTaxExempt,UpfrontTaxSundryId,AcquisitionLocationTaxAreaId,AcquisitionLocationCity,AcquisitionLocationMainDivision,AcquisitionLocationCountry,SalesTaxRemittanceResponsibility,AssetUsageCondition,IsSKU,AssetSKUId,IsExemptAtAssetSKU, UpfrontTaxAssessedInLegacySystem,
AssetSerialOrVIN,BusCode)  
SELECT   
 @NewChunkStatus AS ChunkStatus,  
 RI.ReceivableTaxId,   
 RI.ReceivableTaxDetailId,  
 RI.IsCashPosted,   
 RI.ReceivableDetailId,   
 RI.Currency,   
 RI.TaxAreaId,   
 RS.Cost,   
 RS.ExtendedPrice,   
 RS.FairMarketValue,   
 RI.TaxBasisType,  
 RI.AssetId,   
 RI.LocationId,   
 RI.DueDate,   
 RI.ReceivableId,   
 RI.ReceivableCodeId,   
 RI.IsInvoiced,   
 RI.IsExemptAtLease,   
 RI.IsExemptAtAsset,   
 RI.IsExemptAtSundry,   
 RI.Company,   
 RI.Product,   
 RI.ContractType,   
 RI.LeaseType,   
 RI.LeaseTerm,   
 RI.TitleTransferCode,   
 RI.TransactionCode,   
 RS.AmountBilledToDate,   
 RI.AssetLocationId,   
 RI.ToState,   
 RI.FromState,   
 RI.SundryReceivableCode,   
 RI.IsExemptAtReceivableCode,   
 RI.TransactionType,   
 RI.ReceivableType,   
 RI.IsRental,   
 RI.CustomerId,   
 RI.ContractId,   
 RI.LegalEntityId,   
 RI.EntityType,  
 TED.CountryTaxExempt,   
 TED.StateTaxExempt,   
 TED.CityTaxExempt,   
 TED.CountyTaxExempt,   
 TED.CountryTaxExemptRule,   
 TED.StateTaxExemptRule,   
 TED.CityTaxExemptRule,   
 TED.CountyTaxExemptRule,   
 LI.Country,   
 LI.MainDivision,   
 LI.StateId,   
 LI.City,   
 LI.LocationCode,  
 LI.IsVertexSupportedLocation,   
 Customer.ClassCode,   
 Customer.CustomerNumber,   
 Customer.TaxRegistrationNumber,  
 Customer.ISOCountryCode,  
 Customer.PartyName,  
 AF.GrossVehicleWeight,   
 RI.AssetType,   
 AF.SaleLeasebackCode,   
 ISNULL(AF.IsElectronicallyDelivered,CONVERT(BIT,0)) AS IsElectronicallyDelivered,   
 Contract.TaxRemittanceType,   
 AF.SalesTaxExemptionLevel,   
 ISNULL(Contract.IsSyndicated,CONVERT(BIT,0)) AS IsSyndicated,   
 AF.AssetCatalogNumber,  
 AF.AssetTypeId,   
 Contract.LeaseUniqueId,  
 Contract.ContractTypeValue,   
 AL.LocationEffectiveDate,   
 ISNULL(AL.LienCredit,0),   
 ISNULL(AL.ReciprocityAmount,0),  
 RI.ReceivableTaxDetailRowVersion,  
 RI.ReceivableTaxRowVersion,  
 RI.ReceivableDetailRowVersion,  
 RI.AssetLocationRowVersion,  
 1,  
 SYSDATETIMEOFFSET(),  
 @JobStepInstanceId,  
 AF.Usage,  
 CAST(0 AS BIT) AS IsTaxExempt,  
 RI.UpfrontTaxSundryId,  
 AcquisitionLocationDetail.AcquisitionLocationTaxAreaId,  
 AcquisitionLocationDetail.City,  
 AcquisitionLocationDetail.MainDivision,  
 AcquisitionLocationDetail.Country,
 ISNULL(RI.SalesTaxRemittanceResponsibility,'_') AS SalesTaxRemittanceResponsibility,
 '_' AS AssetUsageCondition,
 AF.IsSKU,
 AF.AssetSKUId,
 RS.IsExemptAtAssetSKU,
 RI.UpfrontTaxAssessedInLegacySystem,
 AF.AssetSerialOrVIN,
 RI.BusCode
FROM ReversalReceivableDetail_Extract RI  
INNER JOIN ReversalReceivableSKUDetail_Extract RS ON RI.ReceivableTaxDetailId = RS.ReceivableTaxDetailId AND RI.JobStepInstanceId = RS.JobStepInstanceId  
INNER JOIN ReversalCustomerDetail_Extract Customer ON RI.CustomerId = Customer.CustomerId AND Customer.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalContractDetail_Extract Contract ON RI.ContractId = Contract.ContractId AND Contract.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalLocationDetail_Extract LI ON RI.LocationId = LI.LocationId AND LI.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalTaxExemptDetail_Extract TED ON RI.ReceivableDetailId = TED.ReceivableDetailId AND (RI.AssetId = TED.AssetId OR RI.AssetId IS NULL) AND TED.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalFlexFieldDetail_Extract AF ON AF.AssetId = RI.AssetId AND RS.AssetSKUId = AF.AssetSKUId AND AF.JobStepInstanceId = @JobStepInstanceId  
LEFT JOIN ReversalAssetLocationDetail_Extract AL ON RI.AssetLocationId = AL.AssetLocationId AND AL.JobStepInstanceId = @JobStepInstanceId  
LEFT JOIN ReversalLocationDetail_Extract AcquisitionLocationDetail ON RI.AcquisitionLocationId = AcquisitionLocationDetail.LocationId AND AcquisitionLocationDetail.JobStepInstanceId = @JobStepInstanceId  
WHERE RI.EntityType = @CTEntityType AND ErrorCode IS NULL AND RI.JobStepInstanceId = @JobStepInstanceId AND AF.IsSKU = 1
;  

  
INSERT INTO ReceivableDetailsForReversalProcess_Extract (ChunkStatus,ReceivableTaxId,ReceivableTaxDetailId, IsCashPosted, ReceivableDetailId, Currency, TaxAreaId, Cost, ExtendedPrice, FairMarketValue, TaxBasisType,  
AssetId, LocationId, DueDate, ReceivableId, ReceivableCodeId, IsInvoiced, IsExemptAtLease, IsExemptAtAsset, IsExemptAtSundry, Company, Product,   
ContractType, LeaseType, LeaseTerm, TitleTransferCode, TransactionCode, AmountBilledToDate, AssetLocationId, ToState, FromState, SundryReceivableCode,   
IsExemptAtReceivableCode, TransactionType, ReceivableType, IsRental, CustomerId, ContractId, LegalEntityId, EntityType, CountryTaxExempt, StateTaxExempt, CityTaxExempt, CountyTaxExempt,   
CountryTaxExemptRule, StateTaxExemptRule, CityTaxExemptRule, CountyTaxExemptRule, Country, MainDivision, StateId, City, LocationCode, IsVertexSupportedLocation,   
ClassCode, CustomerNumber, TaxRegistrationNumber, ISOCountryCode, PartyName, GrossVehicleWeight, IsElectronicallyDelivered,   
IsSyndicated, LocationEffectiveDate, LienCredit, ReciprocityAmount,ReceivableTaxDetailRowVersion,ReceivableTaxRowVersion,ReceivableDetailRowVersion,AssetLocationRowVersion,CreatedById, CreatedTime, JobStepInstanceId, IsTaxExempt,UpfrontTaxSundryId,  
AcquisitionLocationTaxAreaId,AcquisitionLocationCity,AcquisitionLocationMainDivision,AcquisitionLocationCountry,AssetUsageCondition,SalesTaxRemittanceResponsibility,IsSKU,AssetSKUId,IsExemptAtAssetSKU, UpfrontTaxAssessedInLegacySystem, BusCode)  
SELECT   
 @NewChunkStatus AS ChunkStatus,  
 RI.ReceivableTaxId,   
 RI.ReceivableTaxDetailId,  
 RI.IsCashPosted,   
 RI.ReceivableDetailId,   
 RI.Currency,   
 RI.TaxAreaId,   
 RI.Cost,   
 RI.ExtendedPrice,   
 RI.FairMarketValue,   
 RI.TaxBasisType,  
 RI.AssetId,   
 RI.LocationId,   
 RI.DueDate,   
 RI.ReceivableId,   
 RI.ReceivableCodeId,   
 RI.IsInvoiced,   
 RI.IsExemptAtLease,   
 RI.IsExemptAtAsset,   
 RI.IsExemptAtSundry,   
 RI.Company,   
 RI.Product,   
 RI.ContractType,   
 RI.LeaseType,   
 RI.LeaseTerm,   
 RI.TitleTransferCode,   
 RI.TransactionCode,   
 RI.AmountBilledToDate,   
 RI.AssetLocationId,   
 RI.ToState,   
 RI.FromState,   
 RI.SundryReceivableCode,   
 RI.IsExemptAtReceivableCode,   
 RI.TransactionType,   
 RI.ReceivableType,   
 RI.IsRental,   
 RI.CustomerId,   
 RI.ContractId,   
 RI.LegalEntityId,   
 RI.EntityType,  
 TED.CountryTaxExempt,   
 TED.StateTaxExempt,   
 TED.CityTaxExempt,   
 TED.CountyTaxExempt,   
 TED.CountryTaxExemptRule,   
 TED.StateTaxExemptRule,   
 TED.CityTaxExemptRule,   
 TED.CountyTaxExemptRule,   
 LI.Country,   
 LI.MainDivision,   
 LI.StateId,   
 LI.City,   
 LI.LocationCode,  
 LI.IsVertexSupportedLocation,   
 Customer.ClassCode,   
 Customer.CustomerNumber,   
 Customer.TaxRegistrationNumber,  
 Customer.ISOCountryCode,  
 Customer.PartyName,  
 CAST(0 AS BIT) AS GrossVehicleWeight,   
 CAST(0 AS BIT) AS IsElectronicallyDelivered,    
 CAST(0 AS BIT) AS IsSyndicated,    
 CAST(NULL AS DATE) AS LocationEffectiveDate,   
 0.00 AS LienCredit,   
 0.00 AS ReciprocityAmount,  
 RI.ReceivableTaxDetailRowVersion,  
 RI.ReceivableTaxRowVersion,  
 RI.ReceivableDetailRowVersion,  
 RI.AssetLocationRowVersion,  
 1,  
 SYSDATETIMEOFFSET(),  
 @JobStepInstanceId,  
 CAST(0 AS BIT) AS IsTaxExempt,  
 RI.UpfrontTaxSundryId,  
 AcquisitionLocationDetail.AcquisitionLocationTaxAreaId,  
 AcquisitionLocationDetail.City,  
 AcquisitionLocationDetail.MainDivision,  
 AcquisitionLocationDetail.Country,
 '_' AS AssetUsageCondition,
ISNULL(RI.SalesTaxRemittanceResponsibility,'_') AS SalesTaxRemittanceResponsibility,
 0,
 NULL,
 0,
 RI.UpfrontTaxAssessedInLegacySystem,
 RI.BusCode
FROM ReversalReceivableDetail_Extract RI  
INNER JOIN ReversalCustomerDetail_Extract Customer ON RI.CustomerId = Customer.CustomerId AND Customer.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalLocationDetail_Extract LI ON RI.LocationId = LI.LocationId AND LI.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalTaxExemptDetail_Extract TED ON RI.ReceivableDetailId = TED.ReceivableDetailId AND (RI.AssetId = TED.AssetId OR RI.AssetId IS NULL) AND TED.JobStepInstanceId = @JobStepInstanceId  
LEFT JOIN ReversalLocationDetail_Extract AcquisitionLocationDetail ON RI.AcquisitionLocationId = AcquisitionLocationDetail.LocationId AND AcquisitionLocationDetail.JobStepInstanceId = @JobStepInstanceId  
WHERE RI.EntityType = @CUEntityType AND ErrorCode IS NULL AND RI.JobStepInstanceId = @JobStepInstanceId  
  
INSERT INTO ReceivableDetailsForReversalProcess_Extract (ChunkStatus,ReceivableTaxId,ReceivableTaxDetailId, IsCashPosted, ReceivableDetailId, Currency, TaxAreaId, Cost, ExtendedPrice, FairMarketValue, TaxBasisType,  
AssetId, LocationId, DueDate, ReceivableId, ReceivableCodeId, IsInvoiced, IsExemptAtLease, IsExemptAtAsset, IsExemptAtSundry, Company, Product,   
ContractType, LeaseType, LeaseTerm, TitleTransferCode, TransactionCode, AmountBilledToDate, AssetLocationId, ToState, FromState, SundryReceivableCode,   
IsExemptAtReceivableCode, TransactionType, ReceivableType, IsRental, CustomerId, ContractId, LegalEntityId, EntityType, CountryTaxExempt, StateTaxExempt, CityTaxExempt, CountyTaxExempt,   
CountryTaxExemptRule, StateTaxExemptRule, CityTaxExemptRule, CountyTaxExemptRule, Country, MainDivision, StateId, City, LocationCode, IsVertexSupportedLocation,   
ClassCode, CustomerNumber, TaxRegistrationNumber, ISOCountryCode, PartyName, GrossVehicleWeight, IsElectronicallyDelivered,   
IsSyndicated, LocationEffectiveDate, LienCredit, ReciprocityAmount,ReceivableTaxDetailRowVersion,ReceivableTaxRowVersion,ReceivableDetailRowVersion,AssetLocationRowVersion,CreatedById, CreatedTime, JobStepInstanceId,  
IsTaxExempt,UpfrontTaxSundryId,AcquisitionLocationTaxAreaId,AcquisitionLocationCity,AcquisitionLocationMainDivision,AcquisitionLocationCountry,AssetUsageCondition,SalesTaxRemittanceResponsibility,IsSKU,AssetSKUId,IsExemptAtAssetSKU, UpfrontTaxAssessedInLegacySystem, BusCode)  
SELECT   
 @NewChunkStatus AS ChunkStatus,  
 RI.ReceivableTaxId,   
 RI.ReceivableTaxDetailId,  
 RI.IsCashPosted,   
 RI.ReceivableDetailId,   
 RI.Currency,   
 RI.TaxAreaId,   
 RI.Cost,   
 RI.ExtendedPrice,   
 RI.FairMarketValue,   
 RI.TaxBasisType,  
 RI.AssetId,   
 RI.LocationId,   
 RI.DueDate,   
 RI.ReceivableId,   
 RI.ReceivableCodeId,   
 RI.IsInvoiced,   
 RI.IsExemptAtLease,   
 RI.IsExemptAtAsset,   
 RI.IsExemptAtSundry,   
 RI.Company,   
 RI.Product,   
 RI.ContractType,   
 RI.LeaseType,   
 RI.LeaseTerm,   
 RI.TitleTransferCode,   
 RI.TransactionCode,   
 RI.AmountBilledToDate,   
 RI.AssetLocationId,   
 RI.ToState,   
 RI.FromState,   
 RI.SundryReceivableCode,   
 RI.IsExemptAtReceivableCode,   
 RI.TransactionType,   
 RI.ReceivableType,   
 RI.IsRental,   
 RI.CustomerId,   
 RI.ContractId,   
 RI.LegalEntityId,   
 RI.EntityType,  
 TED.CountryTaxExempt,   
 TED.StateTaxExempt,   
 TED.CityTaxExempt,   
 TED.CountyTaxExempt,   
 TED.CountryTaxExemptRule,   
 TED.StateTaxExemptRule,   
 TED.CityTaxExemptRule,   
 TED.CountyTaxExemptRule,   
 LI.Country,   
 LI.MainDivision,   
 LI.StateId,   
 LI.City,   
 LI.LocationCode,  
 LI.IsVertexSupportedLocation,   
 Customer.ClassCode,   
 Customer.CustomerNumber,   
 Customer.TaxRegistrationNumber,  
 Customer.ISOCountryCode,  
 Customer.PartyName,  
 CAST(0 AS BIT) AS GrossVehicleWeight,   
 CAST(0 AS BIT) AS IsElectronicallyDelivered,    
 CAST(0 AS BIT) AS IsSyndicated,    
 CAST(NULL AS DATE) AS LocationEffectiveDate,   
 0.00 AS LienCredit,   
 0.00 AS ReciprocityAmount,  
 RI.ReceivableTaxDetailRowVersion,  
 RI.ReceivableTaxRowVersion,  
 RI.ReceivableDetailRowVersion,  
 RI.AssetLocationRowVersion,  
 1,  
 SYSDATETIMEOFFSET(),  
 @JobStepInstanceId,  
 CAST(0 AS BIT) AS IsTaxExempt,  
 RI.UpfrontTaxSundryId,  
 AcquisitionLocationDetail.AcquisitionLocationTaxAreaId,  
 AcquisitionLocationDetail.City,  
 AcquisitionLocationDetail.MainDivision,  
 AcquisitionLocationDetail.Country,
 '_' AS AssetUsageCondition,
 ISNULL(RI.SalesTaxRemittanceResponsibility,'_') AS SalesTaxRemittanceResponsibility,
 0,
 NULL,
 0,
 RI.UpfrontTaxAssessedInLegacySystem,
 RI.BusCode
FROM ReversalReceivableDetail_Extract RI  
INNER JOIN ReversalCustomerDetail_Extract Customer ON RI.CustomerId = Customer.CustomerId AND Customer.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalLocationDetail_Extract LI ON RI.LocationId = LI.LocationId AND LI.JobStepInstanceId = @JobStepInstanceId  
INNER JOIN ReversalTaxExemptDetail_Extract TED ON RI.ReceivableDetailId = TED.ReceivableDetailId AND (RI.AssetId = TED.AssetId OR RI.AssetId IS NULL) AND TED.JobStepInstanceId = @JobStepInstanceId  
LEFT JOIN ReversalLocationDetail_Extract AcquisitionLocationDetail ON RI.AcquisitionLocationId = AcquisitionLocationDetail.LocationId AND AcquisitionLocationDetail.JobStepInstanceId = @JobStepInstanceId  
WHERE RI.EntityType = @DTEntityType AND ErrorCode IS NULL AND RI.JobStepInstanceId = @JobStepInstanceId  
  
  
UPDATE ReceivableDetailsForReversalProcess_Extract  
SET IsTaxExempt = 1  
FROM ReceivableDetailsForReversalProcess_Extract RD  
INNER JOIN ReceivableTaxDetails RTD ON RD.ReceivableDetailId = RTD.ReceivableDetailId  
INNER JOIN ReceivableTaxImpositions RTI ON RTD.Id = RTI.ReceivableTaxDetailId  
WHERE RTI.ExemptionType != @UnknownTaxExemptionType AND RD.JobStepInstanceId = @JobStepInstanceId  
  
UPDATE ReceivableDetailsForReversalProcess_Extract  
SET VertexBilledRentalReceivableId = BRR.Id,  
 VertexBilledRentalReceivableRowVersion = BRR.RowVersion   
FROM ReceivableDetailsForReversalProcess_Extract RRD  
INNER JOIN VertexBilledRentalReceivables BRR ON RRD.ReceivableDetailId = BRR.ReceivableDetailId  
WHERE RRD.JobStepInstanceId = @JobStepInstanceId AND RRD.IsRental = 1 
  
IF EXISTS(Select 1 from ReceivableDetailsForReversalProcess_Extract WHERE JobStepInstanceId = @JobStepInstanceId)  
BEGIN  
 SELECT @ReceivableExists = CAST(1 AS BIT)  
END  
  
END

GO
