SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



Create   proc [dbo].[PopulatePresetTableConfig]
as
truncate table [PresetTableConfigs];
declare @Today datetime =getdate();

INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ActivityEntityConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ActivityStatusConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ActivitySubSystemConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('AdjustmentReasonConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ApprovalConditionConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('AssetGroupByOptions',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('AuditEntityConfigs',1,@Today,'','Update AuditEntityConfigs set IsEnabled=0 where IsEnabled=1')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('Authorities',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('AuthorityTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('BankAccountCategories',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('BusinessCalendarDetails',1,@Today,'BusinessCalendarId>1','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('BusinessCalendars',1,@Today,'Id>1','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('BusinessDeclineReasonCodeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('BusinessTypeNAICSCodes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('BusinessTypesSICsCodes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('BusinessUnits',1,@Today,'Id>1','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CashTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ChargeOffReasonCodeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CIPDocumentSourceConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CommentEntityConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CommentEntityRelationConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CommentSubSystemConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ContactTypesForEntityTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ContractAmendmentReasonCodes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('Countries',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CountryCurrencyRelationships',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('Currencies',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CurrencyCodes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CustomerApprovedExchangesConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CustomerApprovedRegulatorsConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('CustomerClasses',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DefaultTaxTypeForReceivableTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DocumentBusinessEntityConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DocumentBusinessEntityRelationConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DocumentEntityConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DocumentEntityEmailConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DocumentEntityRelationConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DocumentStatusConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DocumentStatusSubSystemConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('DocumentSubSystemConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('EmailTemplateEntityConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('EmailTemplateTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('EntityAccessScopeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('EntityConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('EntityEnumFields',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('EnumConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('EnumValues',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ExternalBusinessTypeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ExternalTaxFields',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('GLAccountTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('GLEntryItems',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('GLMatchingEntryItems',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('GlobalParameters',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('GLSegmentTypeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('GLSegmentTypeDetails',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('GLSegmentTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('GLTransactionTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('InvoiceFormats',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('InvoiceGroupingParameters',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('InvoiceTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('JobTaskConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('JobTaskSubSystemConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('LanguageConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('LegalFormationTypeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('LienFilingOrderStatusCodes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('LienReferenceFieldConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('LienResponseStatusCodeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('LockboxFileFormatConfigDetails',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('LockboxFileFormatConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('MasterConfigDetails',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('MasterConfigEntities',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('MasterConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('NachaFileFormatConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('NotificationEventConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('OriginationSourceTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PayableTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PayoffTemplateTerminationTypeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PayoffTerminationExpressions',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PayoffTerminationOptions',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PortfolioParameterConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PortfolioParameters',1,@Today,'PortfolioId>1','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('Portfolios',1,@Today,'Id>1','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('Presettableconfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PrincipalDeclineReasonCodeConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PropertyTaxParameters',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('PurgeTableConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('RACRuleConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReceiptTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReceivableCategories',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReceivableTypeBlendingConfigTables',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReceivableTypeLabelConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReceivableTypeLanguageLabels',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReceivableTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReleaseVersions',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReportPreferenceConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('RoleFunctions',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('Roles',1,@Today,'Id>2','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('RolesForUsers',1,@Today,'UserId>2 or IsActive=0','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('SalesTaxExemptionLevelConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('SecurityConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('SequenceGenerators',1,@Today,'','update SequenceGenerators set Next=0')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('States',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('SubSystemConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TaxAuthorityConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TaxBasisTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TaxImpositionTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TaxProductTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TaxTypes',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TerminationTypeParameterConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TimeZones',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TransactionConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('TransactionStageConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('UserEmailAddresses',1,@Today,'UserId>2','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('UserHistories',1,@Today,'UserId>2','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('UserNotificationPreferences',1,@Today,'UserId>2','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('Users',1,@Today,'Id>2','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('UserPasswordHistories',1,@Today,'UserId>2','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('UserSiteAccesses',1,@Today,'UserId>2','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('UserTypeMappings',1,@Today,'UserId>2','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('WorkItemActionConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('WorkItemConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('WorkItemSubSystemConfigs',1,@Today,'','')
INSERT INTO [dbo].[PresetTableConfigs]  ([Name],[CreatedById],[CreatedTime] ,[DeleteWhereClause],[UpdateSQL]) VALUES ('ReleaseVersionDetails',1,@Today,'','')

GO
