SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[VP_GetBusinessTypeDetails]
AS
BEGIN
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT
BT.Name AS Name,
BT.IsActive AS IsActive,
BT.Description AS Description
FROM Businesstypes BT
WHERE BT.IsActive = 1
END

GO
